### ISSUE TITLE
CPU frequency limits are too slow

### ISSUE THREAD

**Issue by Sadoon-AlBader** [secureblue/secureblue#109]
For some reason, CPU frequency limits are much slower than what they should be. This is probably a kernel issue.

Haswell laptop with SecureBlue:
```
cat /sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq
900000
```
Haswell laptop with Fedora Kinoite:
```
cat /sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq
3000000
```

Same with my Alder Lake laptop, which should boost to 4.7GHz but is limited to 2.1
This is an issue across all cpufreq governors, I've tested them all :')
I wouldn't have noticed had I not tried to use my Haswell laptop, which is horrendously slow at 900MHz.
This is very reproducible but I can't figure out why it happens.

Also, I haven't set the kargs using just on the Haswell laptop yet, but did so on Alder Lake. Doesn't seem to be the issue though.

**Comment by RoyalOughtness** [comment]
If you ran set-kargs-hardening, it's probably one of those kargs. 

You can test removing them one at a time using this functionality:

https://docs.fedoraproject.org/en-US/fedora-coreos/kernel-args/#_removing_existing_kernel_arguments

My guess would be that it's partially nosmt that's doing this. Up to 40% impact is expected when nosmt is enabled. However, it provides a massive security improvement.

If you can confirm that it's nosmt, then this is expected behavior and this can be closed. If you find that it's something else, more investigation will be needed. That impact seems significantly over the expected impact for nosmt, so do let me know what you find.

**Comment by RoyalOughtness** [comment]
I missed your most recent edit about not setting kargs. That is strange. Let me check whether i can repro.

**Comment by RoyalOughtness** [comment]
@Sadoon-AlBader can you provide the contents of /proc/cmdline for both laptops?

**Comment by RoyalOughtness** [comment]
@Sadoon-AlBader also, by any chance are you testing these unplugged from their charger? If so then TLP is probably throttling the cpu to save battery. TLP isn't used in stock kinoite so that would explain it.

**Comment by Sadoon-AlBader** [comment]
> @Sadoon-AlBader also, by any chance are you testing these unplugged from their charger? If so then TLP is probably throttling the cpu to save battery. TLP isn't used in stock kinoite so that would explain it.

Confirmed that TLP is what's causing this.
On charger, clocks are normal.
Upon setting:
`tlp ac`
Clocks are also back to normal
Upon setting:
`tlp start`
Which sets it in auto mode, clocks are back down.

This is all with kargs hardening, I highly doubt they have anything to do with this because the other laptop has no kargs hardening yet.

This issue is probably due to upstream Fedora using very conservative battery profiles in tlp

**Comment by Sadoon-AlBader** [comment]
The relevant tlp configuration is in /etc/tlp.d/50-laptop.conf

The most relevant options are:

```
CPU_ENERGY_PERF_POLICY_ON_BAT
CPU_MAX_PERF_ON_BAT
CPU_BOOST_ON_BAT
CPU_HWP_DYN_BOOST_ON_BAT
```

My suggestion is to not enable tlp by default because Fedora upstream sets extreme defaults. On newer laptops it's much less noticeable though.

**Comment by RoyalOughtness** [comment]
> The relevant tlp configuration is in /etc/tlp.d/50-laptop.conf
> 
> The most relevant options are:
> 
> ```
> CPU_ENERGY_PERF_POLICY_ON_BAT
> CPU_MAX_PERF_ON_BAT
> CPU_BOOST_ON_BAT
> CPU_HWP_DYN_BOOST_ON_BAT
> ```
> 
> My suggestion is to not enable tlp by default because Fedora upstream sets extreme defaults. On newer laptops it's much less noticeable though.

The defaults are coming from ublue, here: https://github.com/ublue-os/bling/blob/main/files/laptop/usr/etc/tlp.d/50-laptop.conf

The goal here being to save battery, I think the settings make sense. If you want to have them changed though, please file an issue upstream.

**Comment by RoyalOughtness** [comment]
@Sadoon-AlBader I'm gonna add a separate set of -laptop images.  This will 2x the image quantity, but it's fine. TLP really shouldn't be included at all for desktops anyways, and this will give users the option to not have TLP even if they do use a laptop.

**Comment by Sadoon-AlBader** [comment]
> @Sadoon-AlBader I'm gonna add a separate set of -laptop images. This will 2x the image quantity, but it's fine. TLP really shouldn't be included at all for desktops anyways, and this will give users the option to not have TLP even if they do use a laptop.

I think that will add too much burden, perhaps it's better to either keep it disabled and/or inform the user through the first-use app? Limiting a laptop to 900MHz when its minimum is 800MHz is going to save battery but it makes it pretty much unusable, even typing into the terminal was slow.
That and I'll also file an issue on ublue as well when I'm free.

**Comment by RoyalOughtness** [comment]
> > @Sadoon-AlBader I'm gonna add a separate set of -laptop images. This will 2x the image quantity, but it's fine. TLP really shouldn't be included at all for desktops anyways, and this will give users the option to not have TLP even if they do use a laptop.
> 
> I think that will add too much burden, perhaps it's better to either keep it disabled and/or inform the user through the first-use app? Limiting a laptop to 900MHz when its minimum is 800MHz is going to save battery but it makes it pretty much unusable, even typing into the terminal was slow. That and I'll also file an issue on ublue as well when I'm free.

Already added laptop images 😄
