### ISSUE TITLE
bubblewrap-suid COPR

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#11]
So bubblewrap-suid looks like a fork of bubblewrap. A possible way could be to just repackage the Arch build.

https://gitlab.archlinux.org/archlinux/packaging/packages/bubblewrap

https://archlinux.org/packages/extra/x86_64/bubblewrap-suid/

**Comment by wandapeter** [comment]
Thanks fot the help, i am on it. :smile:

**Comment by RoyalOughtness** [comment]
@34N0 confirming you are working on this?

**Comment by RoyalOughtness** [comment]
also, @34N0 as mentioned in the other thread by rusty-snake:

> bubblewrap-suid is nothing more than but bubblewrap + chown root:root (better safe than sorry) + chmod u+s.

> Just pick https://src.fedoraproject.org/rpms/bubblewrap/blob/rawhide/f/bubblewrap.spec, add chown+chmod and change the name, description, ....

**Comment by wandapeter** [comment]
https://github.com/34N0/bubblewrap-suid-rpm

Not yet working. Gnome crashes after reboot with user.max_user_namespaces = 0

**Comment by RoyalOughtness** [comment]
> https://github.com/34N0/bubblewrap-suid-rpm
> 
> Not yet working. Gnome crashes after reboot with user.max_user_namespaces = 0

max_user_namespaces is already set to 0 in this project. are you saying this is already happening for you for gnome images? or only with bubblewrap-suid?

**Comment by wandapeter** [comment]
oh to clarify:

i know the parameter is allready set. I just spun up a base silverblue vm to test the suid variant. so i had to set the argument after i was able to have the correct permissions on the `/usr/bin/bwrap` from overriding `bubblewrap` with a locally built `bubblewrap-suid`. I was able to use flatpaks with the argument set to 0.

As of now i have a working secureblue vm with `bubblewrap-suid` installed and i am reinstalling flatpak to test further.

**Comment by wandapeter** [comment]
https://copr.fedorainfracloud.org/coprs/34n0s/bubblewrap-suid/

i'll work on reenabling flatpak in the builds next

**Comment by RoyalOughtness** [comment]
@34N0 thank you so much for this important and impactful work!

**Comment by wandapeter** [comment]
All good it's cold outside and good fun :smiley: 

I am running into troubles reenabling flatpak on kionite. It seems like to build the image most of the removed package have to be reenabled. Tbh i do not really know what i am doing since i never used KDE. I'll simply submit a PR installing `bubblewrap-suid` for now. 

This even seems cleaner since we can close this issue and test further steps individually

**Comment by RoyalOughtness** [comment]
> All good it's cold outside and good fun 😃
> 
> I am running into troubles reenabling flatpak on kionite. It seems like to build the image most of the removed package have to be reenabled. Tbh i do not really know what i am doing since i never used KDE. I'll simply submit a PR installing `bubblewrap-suid` for now.
> 
> This even seems cleaner since we can close this issue and test further steps individually

That could work but I can also help you work through the issues with the package removals. You will need to remove the removals of several packages to add back flatpak.

Do you use discord? It might be time for me to set one up for development. Ublue already has one anyways.

**Comment by wandapeter** [comment]
I do not use Discord actually. Do you use Matrix? :smile: 

I'll probably continue the work in this on tuesday. You can Merge or Close whatever you think makes more sense going further.

**Comment by RoyalOughtness** [comment]
> I do not use Discord actually. Do you use Matrix? 😄

I don't, but please feel free to just add back any packages you need to get flatpak working. Or we can just merge bubblewrap-suid first like you mentioned and then I can take a look at it

**Comment by wandapeter** [comment]
Ok i'll just keep working on it. You decide what you want to do with pr #45
