### ISSUE TITLE
fix chkrootkit root password

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#12]
```
[Desktop Entry]
Encoding=UTF-8
Name=chkrootkit
Comment=Locally check for signs of a rootkit
Icon=chkrootkit
Exec=pkexec chkrootkit
Terminal=true
Type=Application
Categories=Application;System;
X-Desktop-File-Install-Version=0.26
```

This needs to override the desktop entry to make it work from a GUI

```
cp /usr/share/applications/chkrootkit.desktop ~/.local/share/applications/
sed -i 's/Exec=chkrootkit/Exec=pkexec chkrootkit/' ~/.local/share/applications/chkrootkit.desktop
```

**Comment by wandapeter** [comment]
Tested and confirmed.

Seems kinda hacky though. One possibility would be to create a COPR maybe called `chkrootkit-ostree` which installs chkrootkit with the correct Exec command. This would then also be usable by people using other `rpm-ostree` distributions.

The easier solution would to create a script called `checkrootkit.sh` which gets called during build. You could submit a pull request doing the following for now. @qoijjj  what do you think?

**Comment by boredsquirrel** [comment]
no the pkexec is just to launch the app with polkit, granting sudo permissions, not root. Normal installs dont have a root accout, so this applies to all fedora.

Another way would be to just change the upstream code to use sudo, as this should work pretty much everywhere.

It is hacky like this, but needed for working GUI.

Not sure how to do this, one way would be with a script ran when the user first boots up, or I think `/etc/skel.d/.local/share/applications` will also be copied there?

**Comment by RoyalOughtness** [comment]
> Tested and confirmed.
> 
> Seems kinda hacky though. One possibility would be to create a COPR maybe called `chkrootkit-ostree` which installs chkrootkit with the correct Exec command. This would then also be usable by people using other `rpm-ostree` distributions.
> 
> The easier solution would to create a script called `checkrootkit.sh` which gets called during build. You could submit a pull request doing the following for now. @qoijjj what do you think?



> ```
> [Desktop Entry]
> Encoding=UTF-8
> Name=chkrootkit
> Comment=Locally check for signs of a rootkit
> Icon=chkrootkit
> Exec=pkexec chkrootkit
> Terminal=true
> Type=Application
> Categories=Application;System;
> X-Desktop-File-Install-Version=0.26
> ```
> 
> This needs to override the desktop entry to make it work from a GUI
> 
> ```
> cp /usr/share/applications/chkrootkit.desktop ~/.local/share/applications/
> sed -i 's/Exec=chkrootkit/Exec=pkexec chkrootkit/' ~/.local/share/applications/chkrootkit.desktop
> ```

Why would you need to overwrite a desktop file in ~/.local/share/applications ?

The chkrootkit desktop file is in /usr/share/applications, which should make this much more straightforward (like so: https://github.com/ublue-os/bluefin/pull/668/files#diff-5fcdf9b4580789697d834d1456a22bcfaa236d668fc180cad4775afc36ed5914)

**Comment by RoyalOughtness** [comment]
You can also overwrite files in /usr by just dropping them into the corresponding directory in this repo.

**Comment by RoyalOughtness** [comment]
However, on second thought this really seems like something that the chkrootkit package maintainer should fix. Have you notified them of this issue?

**Comment by RoyalOughtness** [comment]
closing as this is an upstream issue to do with chkrootkit's compatibility with immutable fedora

**Comment by boredsquirrel** [comment]
old issue, but this is not due to immutable fedora but using sudo instead of polkit.

polkit is used for GUI running, where it seems sudo doesnt work. It seems their desktop icon is useless in that case so it should be an easy fix

https://bugzilla.redhat.com/show_bug.cgi?id=2253108

**Comment by RoyalOughtness** [comment]
> old issue, but this is not due to immutable fedora but using sudo instead of polkit.
> 
> polkit is used for GUI running, where it seems sudo doesnt work. It seems their desktop icon is useless in that case so it should be an easy fix
> 
> https://bugzilla.redhat.com/show_bug.cgi?id=2253108

Please file this upstream.
