### ISSUE TITLE
remove rpm-ostree backends for GNOME Software and KDE Discover

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#122]
The Stores do not use Packagekit but own backends. They work well but have problems:

- when starting the store, an rpm-ostree query is initiated. This is not an update, but it looks for an update and takes forever. It is very bad UX but intended upstream. This is cosmetical though
- users will have two sources for apps like Libreoffice, Thunderbird etc if the Appstream metadata matches. Installing those apps would mean layering RPMs, and many many RPMs would be shown alongside Flatpaks. there would be no indication, that Flatpak apps are preferred.
- layering RPMs through a GUI store is really inefficient and bad UX, as you can only layer a single one at a time. Updating manually is also bad, as this will be unnecessary load on the store, while automatic staging updates are already enabled

So in the end it might be good for upstream to have these backends, but for users and for making clear what apps to install and what not, it would have advantages to remove them from the base.

The security benefit is relying on Flathub and Bubblewrap for Sandboxing only.

**Comment by RoyalOughtness** [comment]
I'm very skeptical that any of this is a real issue, but even if it is, it's entirely upstream

**Comment by boredsquirrel** [comment]
so... that I am unblocked...

Following this argumentation, any change in defaults that could also be implemented upstream should be reported there. The argumentation was clear, at least I hope so:
- rpm-ostree installs of packages should not be suggested
- updates are automatic on ublue, unlike upstream where they depend on the software stores
- upstream does not work for nonwheel users at all, not even the updating works, the issue is inactive since forever

those are the reasons. Using nonwheel user accounts with the new polkit rule will make the software stores work, but the updates are automatic anyways so this is unnecessary deduplication, and the "install app" button will work for flatpak but not for rpm-ostree which can be seen as confusing.

especially confusing as the local user flathub remote is installed. this means all rpm-ostree installs would be done on an administrative user, but that one cannot install any flatpaks as they would not show up on the regular user. So you would have a store that does
- 1 thing on the one profile (rpm-ostree)
- (but doing the other thing here is a mistake) (flatpak)

and
- 1 thing on the other profile (flatpak)
- and doing the other thing will result in an error message (rpm-ostree)

this is horrible UX...

**Comment by RoyalOughtness** [comment]
I still don't understand what the core issue is.

> rpm-ostree installs of packages should not be suggested

According to who? Layering packages is fine

> updates are automatic on ublue, unlike upstream where they depend on the software stores

Automatic staging of updates is the default behavior for upstream, upstream ublue, and secureblue

> upstream does not work for nonwheel users at all, not even the updating works, the issue is inactive since forever

sure but this is already fixed

> the "install app" button will work for flatpak but not for rpm-ostree which can be seen as confusing.

If users take the additional step to designate a separate wheel user, then this is expected and not confusing. It would be confusing and a security issue if the app stores still worked for layering packages for nonwheel users. But we still need the ostree backends for the appstores in the event that a user logs in using their wheel user. 

>  this means all rpm-ostree installs would be done on an administrative user, but that one cannot install any flatpaks as they would not show up on the regular user. 

Correct. Layering is a privileged action, installing user flatpaks isn't. Using a separate nonwheel user has significant usability setbacks, I agree. But the suggestions in this issue do nothing to address it. It's not really an addressable problem. It's a user choice to sacrifice usability for additional security.


> this is horrible UX...

Using a separate wheel account is _inherently_ worse for usability. If the user wants to do so for the security benefits, they can. If not, they don't have to. It's up to the user to choose whether or not to sacrifice some usability for security benefit.
