### ISSUE TITLE
Implement automatic warnings when users do manual changes

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#123]
Some way to detect changes BEFORE the binaries appear in the system (when it is already too late) would be good.

Example: detect enabled userns while bubblewrap-suid is installed.

What to do: a big popup dialog warning people, they need to click okay or even enter "I understand the consequences" to proceed.

How? Kdialog and zenity, or layer zenity everywhere.

edit: is the specific bubblewrap case already covered?

**Comment by RoyalOughtness** [comment]
There's already a warning here: https://github.com/secureblue/secureblue/blob/live/config/files/usr/etc/sysctl.d/hardening.conf#L32

Any further warning for users is out of scope. If a user is technical enough to be making sysctl changes, they are technical enough to read the warning above.
