### ISSUE TITLE
PAM DoS Vulnerability

### ISSUE THREAD

**Issue by wandapeter** [secureblue/secureblue#127]
>Brute force protection by locking user accounts for 24 hours after 50 failed login attempts,

I am currently developing a PAM module fixing this. It will take some while and ofc we will have to decide we'll implement it.

https://github.com/34N0/pam-authramp

**Comment by wandapeter** [comment]
:tada: today i released an alpha version. I invite anyone to look at the code and give some feedback. These screenshots show the account lock after 7 and 60 failed tries using the default configuration.
![lock_7](https://github.com/secureblue/secureblue/assets/92182849/5ece4e96-b8ad-439c-aa3c-af63010334d0)
![lock_60](https://github.com/secureblue/secureblue/assets/92182849/01cfec13-b34e-4221-b4cc-708bfc46ab10)

Is this something you would consider implementing in the future?
https://github.com/34N0/pam-authramp/#threat-model

**Comment by RoyalOughtness** [comment]
Looks good!

> Is this something you would consider implementing in the future?

Is what something I would consider implementing? This module? Yes.

**Comment by wandapeter** [comment]
Ok so i released a beta version of the module. 
The COPR is https://copr.fedorainfracloud.org/coprs/34n0s/pam-authramp/
What are your requirements for an inclusion in the staging builds?

**Comment by RoyalOughtness** [comment]
@34N0 this is _awesome_!

We can add it to staging now. I assume you'll have to remove the existing login.defs and other changes to replace them with this package. Please submit a PR into staging.

**Comment by RoyalOughtness** [comment]
merged https://github.com/secureblue/secureblue/pull/165 into staging, thanks again to @34N0 for this incredibly impactful work!

I encourage everyone following this issue to switch to staging and test it out over the coming days. I'll leave this issue open untill it's in `live` as well

**Comment by wandapeter** [comment]
all good i had a good time writing the module :smile:

**Comment by trytomakeyouprivate** [comment]
is this error message related to this module?

```
kscreenlocker_greet[13143]: PAM unable to dlopen(/usr/lib64/security/pam_console.so): /usr/lib64/security/pam_console.so: could not open shared-object file: file or directory not found
kscreenlocker_greet[13143]: PAM adding faulty module: /usr/lib64/security/pam_console.so
```

**Comment by DimSystem** [comment]
> Looks good!
> 
> > Is this something you would consider implementing in the future?
> 
> Is what something I would consider implementing? This module? Yes.



https://github.com/nuvious/pam-duress, also? Similar to grapheneOS duress passwords? Also, maybe, updates via TOR socks (kicksecure style)?

**Comment by RoyalOughtness** [comment]
> duress passwords

please open a new issue for this to track it separately

> updates via TOR socks (kicksecure style)?

not in scope

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/pull/301

**Comment by wandapeter** [comment]
Sadly, for the next few weeks, I won't be able to work more on https://github.com/34N0/pam-authramp. The last few bug reports concern me and make me feel like it needs a bigger refactor.

In the meantime, I looked at the faillock code and realized the faillock tally gets stored in /var/run, which means it should get deleted after a reboot. This implies that the lockout is lifted after a reboot. On systems with FDE, there's still a DoS vulnerability, but it's only because the system needs to be shut off. However, it's actually strong.

This means the situation isn't as bad for now. I still feel like there's merit in developing authramp further, especially in the near future when FDE encryption gets replaced with homed encryption.

Can you assign #310 to me? I will look into this.

**Comment by wandapeter** [comment]
> In the meantime, I looked at the faillock code and realized the faillock tally gets stored in /var/run, which means it should get deleted after a reboot. This implies that the lockout is lifted after a reboot. On systems with FDE, there's still a DoS vulnerability, but it's only because the system needs to be shut off. However, it's actually strong.

I'll let it up to you if this merits closing this issue

**Comment by RoyalOughtness** [comment]
@34N0 I'll do both. We can reopen this once you think pam-authramp is mature enough
