### ISSUE TITLE
Add Discussions?

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#132]
I can imagine some topics dont fit in the issue form, and I understand that issues should be very clean to stop cluttering.

Having some form of conversation about the project would be great, and Github Discussions could be one. Others could be a Matrix or SimpleX group.

**Comment by RoyalOughtness** [comment]
The only topics of discussion should be ones that fit into issues:

- suggestions for new functionality or config
- suggestions for new spins
- critiques/concerns with existing functionality or config

There's already a uBlue discord for more general conversation.
