### ISSUE TITLE
Security research / pentest variant

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#133]
Would a variant similar to Kali be in scope?

Kali itself seems to rely on a lot of outdated technology, so a security optimized variant could be nice.

I dont know much about the Fedora Security Lab, it also has nearly no media coverage.

- preinstall loads of tools, hopefully from official repos. in KDE and the like the app menu could be adapted to sort them by task
- maybe recreate some other things
  -  systemwide torproxy (for example using carburetor flatpak and systemd-resolved)

**Comment by RoyalOughtness** [comment]
Creating a new immutable pentesting spin of fedora isn't at all in scope for this project, but someone could use ublue's [startingpoint](https://github.com/ublue-os/startingpoint) to create one or work with the Fedora Security Lab SIG to get it done upstream.
