### ISSUE TITLE
use the hardened kernel on main

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#135]
As far as I remember the reason to not use the hardened kernel was the nvidia drivers not working with it.

~~Currently as far as I can see nvidia and main are not separated, so this cant be solved, but separating could, right?~~

Could this be as little as creating a hardened-kernel.yml file, and using that in all but the nvidia recipes?

**Comment by RoyalOughtness** [comment]
> As far as I remember the reason to not use the hardened kernel was the nvidia drivers not working with it.

That's half of the reason. The other half is that the kernel-hardened package last I did a comparison doesn't provide significant security advantages over fedora kernel + sysctl changes + kargs changes.

If you have evidence to the contrary, please provide evidence with a list of security advantages provided by the linux-hardened kernel over fedora's with sysctl and kargs changes.

**Comment by RoyalOughtness** [comment]
see above, reopen if there is evidence to the contrary

**Comment by RoyalOughtness** [comment]
this tool is available to assist with analysis: https://github.com/a13xp0p0v/kernel-hardening-checker
