### ISSUE TITLE
Fix Flatpak remote-modify not working

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#137]
found this issue

https://github.com/flatpak/flatpak/issues/5637

remote-modify does not seem to work. So users will have the limited Flathub selection, but with remote-modify cant opt-in to all Flatpaks.

This means they need to delete the repo and all the apps coming with it, add the other repo and apply the malloc override again (?).

This is an upstream issue but we should be aware of it and follow a fix in the future.

**Comment by RoyalOughtness** [comment]
Most of that is untrue. Users can just add another remote and have both flathub and flathub-verified. This is a non-issue.
