### ISSUE TITLE
removal of kwalletmanager5 breaks many things

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#138]
Some apps, wifi passwords and more are stored in kwallet. I have no idea why `kwalletmanager5` is removed, but its lack causes wifi passwords not being saved and for some reason not even being possible to temporarily enter.

Also the systemsettings page (KCM) is missing. This causes the PAM unlock of the wallet to fail, as at least in GUI the wallet it set as "default" in there. So there is no wallet, or it is not set, and this breaks many things

https://github.com/coreos/rpm-ostree/issues/4554

you cant reinstall `override-remove`d software, so this is a problem. Why would this be removed? I propose to remove that line

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/cc69b3bd0f8cad9f526d990e05156ce0f44366e1
