### ISSUE TITLE
Document surrounding security settings outside of the OS

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#140]
- updated Bios / UEFI
- no boot from usb or network allowed
- secureboot enabled
- strong user and luks passwords
- no root account

all those things cannot be changed by the OS, some way of informing, like a wiki in this repo, may help.

**Comment by RoyalOughtness** [comment]
We could add a PREINSTALL-README.md or something like that that guides users during the initial installation. We could then link to that file from the README.md.

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/8a6b21bb75b5df547a0f24520892dbd6eaba8bde
