### ISSUE TITLE
Chromium: VAAPI vs Wayland platform

### ISSUE THREAD

**Issue by Sadoon-AlBader** [secureblue/secureblue#142]
So the default chromium settings on secureblue enable VAAPI, I prefer to enable wayland for better security (and scaling, especially when connecting and disconnecting external monitors).

It seems only one can stay for now as enabling wayland breaks VAAPI in chromium. My suggestion is to stick with wayland as modern CPUs can handle software decoding just fine.

Thoughts?

**Comment by RoyalOughtness** [comment]
Maybe I'm looking at the wrong settings, but I have Ozone set to Wayland and yet I'm still seeing hardware acceleration in chrome://gpu:

![image](https://github.com/secureblue/secureblue/assets/129108030/0f4056c3-b282-4ac6-a28d-ad3250022570)


Is this inaccurate?

**Comment by Sadoon-AlBader** [comment]
> Maybe I'm looking at the wrong settings, but I have Ozone set to Wayland and yet I'm still seeing hardware acceleration in chrome://gpu:
> 
> ![image](https://private-user-images.githubusercontent.com/129108030/292689358-0f4056c3-b282-4ac6-a28d-ad3250022570.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NTM0ODEsIm5iZiI6MTcwMzQ1MzE4MSwicGF0aCI6Ii8xMjkxMDgwMzAvMjkyNjg5MzU4LTBmNDA1NmMzLWIyODItNGFjNi1hMjhkLWFkMzI1MDAyMjU3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQyMTI2MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDZjNmRlMTdhOTdmNDI1NjE2YjY4ZjFhOTRjNmI1YTkzZmU5MmFkNGEwYzA0YzZiOGM2N2QyNzY0YTliZGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t4ofXQKM4Gahnsy37P37gs4rAV1UduVgOuwKSJlEgc4)
> 
> Is this inaccurate?

Yup unfortunately. It shows as enabled but if you try to load any video and check F12 > 3 dots > more tools > media it will show that hardware decoding is not working.
Well known issue with chromium.

**Comment by RoyalOughtness** [comment]
> > Maybe I'm looking at the wrong settings, but I have Ozone set to Wayland and yet I'm still seeing hardware acceleration in chrome://gpu:
> > ![image](https://private-user-images.githubusercontent.com/129108030/292689358-0f4056c3-b282-4ac6-a28d-ad3250022570.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NTM0ODEsIm5iZiI6MTcwMzQ1MzE4MSwicGF0aCI6Ii8xMjkxMDgwMzAvMjkyNjg5MzU4LTBmNDA1NmMzLWIyODItNGFjNi1hMjhkLWFkMzI1MDAyMjU3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQyMTI2MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDZjNmRlMTdhOTdmNDI1NjE2YjY4ZjFhOTRjNmI1YTkzZmU5MmFkNGEwYzA0YzZiOGM2N2QyNzY0YTliZGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t4ofXQKM4Gahnsy37P37gs4rAV1UduVgOuwKSJlEgc4)
> > Is this inaccurate?
> 
> Yup unfortunately. It shows as enabled but if you try to load any video and check F12 > 3 dots > more tools > media it will show that hardware decoding is not working. Well known issue with chromium.

I see, yes please feel free to submit a PR to set the ozone platform to wayland by default.

**Comment by boredsquirrel** [comment]
has anything changed since Chromium now has official Wayland support? Can VAAPI be enabled again, or is that flag obsolete?

**Comment by RoyalOughtness** [comment]
> has anything changed since Chromium now has official Wayland support? Can VAAPI be enabled again, or is that flag obsolete?

My understanding is that the flag itself doesn't do anything and won't until the issue is resolved in chromium itself. @Sadoon-AlBader can probably comment better than me on this
