### ISSUE TITLE
USBGuard

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#15]

**Comment by boredsquirrel** [comment]
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/protecting-systems-against-intrusive-usb-devices_security-hardening

https://wiki.archlinux.org/title/USBGuard

https://usbguard.github.io/documentation/configuration

**Comment by RoyalOughtness** [comment]
@trytomakeyouprivate 

Please stop bumping issues unless there is something of substance you are adding. Posting a collection of documentation links with no other substance will be considered spam.

**Comment by boredsquirrel** [comment]
[There is something going on upstream fedora](https://pagure.io/fedora-workstation/issue/401)

The issues are
- installing packages
- enabling services
- set polkit rules to allow usbguard
- whitelist all devices by default

GNOME has GUI integration of this, not sure about KDE.

Having it solved upstream would be great

**Comment by RoyalOughtness** [comment]
added and disabled by default: https://github.com/secureblue/secureblue/commit/50f836b4f1751a0bb05ab9181b50775ee8a332d8
