### ISSUE TITLE
Consider using hosts file for system-wide OOTB ads/malware block

### ISSUE THREAD

**Issue by fiftydinar** [secureblue/secureblue#153]
Most popular one for blocking ads & malware:
https://github.com/StevenBlack/hosts

There is probably some other updated hosts file which is better suited for this project (malware only).

This can be achieved by simple script which wgets file from link to /usr/etc/hosts.

Like this:

```
#!/usr/bin/env bash

set -oue pipefail

wget https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts -O /usr/etc/hosts
```

**Comment by RoyalOughtness** [comment]
This is an interesting idea but there are a couple considerations to keep in mind. One is that if we were to do this, we're trusting this hosts file not to contain any malicious redirects itself. This could be mitigated by validating that the only ip addresses present in the file are 0.0.0.0. Two is that we would need to be very careful not to block any legitimate sites. I'm not familiar with this hosts file but it seems like it has a relatively good reputation.

**Comment by RoyalOughtness** [comment]
Discussed on discord. 

https://github.com/secureblue/secureblue/commit/b557ad4e786ef007a2dc3dfa7a7930198e2bc7e5
