### ISSUE TITLE
Improve / fix a nonwheel user account

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#154]
#150 it is necessary and completely fine for regular usage to use a nonwheel user account for most things

This is a change in workflow and includes some problems that have to be addressed, both in breakages of core functionalities, and in overall UX

### rpm-ostree
I again ask for removal of the backends (`gnome-software-rpm-ostree` `plasma-discover-rpm-ostree`).

- Installing apps will not be possible for the nonwheel user, so there will be an option that is not usable
- It pretends that layering packages is just as good as installing Flatpaks, which is often not the case
- it duplicates the efford to update rpm-ostree which is already done automatically, so its completely useless on all ublue variants

this will not be done upstream, as upstream is against automatic updates, thus GUI integration is needed. (I guess this is the argumentation)

### Flatpak
As Flatpak apps are not system Flatpaks, installing them on the initial Yafti makes no sense, as they will only be there. 

I want to discuss why user flatpaks should be more secure, as I dont know any reasons. The data is in the user account, so multiple users can use the same app and not share the data and configs.

Also I had some weird installation problems on GNOME software with many password prompts last time I tried it. Have to search more why and what caused it.

## 2. Polkit rules
There are some things on Fedora that require sudo authentication without a good reason I think. It would make using a nonwheel user a pain. In `/etc/polkit-1/rules.d` :

```
cat 80-udisks2-encrypted-unlock.rules 
polkit.addRule(function(action, subject) {
  if ((action.id == "org.freedesktop.udisks2.encrypted-unlock-system" ||
    action.id =="org.freedesktop.udisks2.encrypted-lock-others") &&\
    subject.isInGroup("wheel")) {
      return polkit.Result.YES;
  }
});
```

```
cat 80-udisks2-mount.rules 
polkit.addRule(function(action, subject) {
  if (action.id == "org.freedesktop.udisks2.filesystem-mount-system" && subject.local && subject.active && subject.isInGroup("wheel")) {
      return polkit.Result.YES;
  }
});
```
These two rules are needed to avoid a password prompt when mounting and unlocking external storage media (not flash media).

I am not sure of security implications of allowing this, maybe add a new group and add the rule to allow all users in group `udisks` or something. In theory being able to use such privileged software as nonroot could increase attack surface (a problem of user namespaces) but it is a huge usability issue if this does not work, especially for encrypted local backups.

So I would say add a group `udisks`, add the matching rules and in the yafti creation allow adding the user to that group or not.

---

```
cat 80-udisks2-mount.rules 
polkit.addRule(function(action, subject) {
  if (action.id == "org.freedesktop.udisks2.filesystem-mount-system" && subject.local && subject.active && subject.isInGroup("wheel")) {
      return polkit.Result.YES;
  }
});
```
This one is needed to access KDE Partitionmanager. I saw the rules for gparted once, but can't find them. They are seperated for all the actions and not the entire app.

It may be okay to only allow wheel to use the partition manager.

### libvirt
For using virt-manager the user needs to be in the libvirt group, as the Images are stored in `/var/lib/libvirt/images/` etc.

### plugdev
This is needed (once udev rules are fixed) to do things like install GrapheneOS on a phone. I think Secureblue should add this functionality, as the dependend packages (`android-tools`, udev rules) are upstream and would simply be preconfigured, and a Laptop is needed for initial installation of GrapheneOS, so the OS should support it.

The user has to be in the `plugdev` group normally, although Daniel Mikay said its not needed, not sure. 

This may add some attack surface, but unsure which.

### flatpak
I assume this is only needed for nonwheel users using systemwide flatpak installations. So if this would be chosen, it is needed, if user Flatpaks are kept it is not.

**Comment by RoyalOughtness** [comment]
1 remains not a real issue and has an existing ticket. For the 10th time, please stop opening issues for existing topics

2  is an entirely personal preference and has no bearing on security. Please review the code of conduct again.

3 is both upstream and a user preference. 


You are hereby banned for 72 hours for your repeated and persistent violations of the code of conduct after half a dozen formal warnings. Please review the code of conduct and reconsider your motivations for contributing.
