### ISSUE TITLE
keep kde printing tools installed as cups is disabled

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#164]
I am confused

```
kde-print-manager-23.08.4-1.fc39.x86_64
kde-print-manager-libs-23.08.4-1.fc39.x86_64
```

why are specifically those removed? Is this simply a leftover from the previous cups cleaning, and should these be kept as they are neutered already? I worry that this will break printing.

**Comment by RoyalOughtness** [comment]
Good find, I had no idea these were still removed. Adding them back now.

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/b97c2069b6dae496fab72f87fc44ebf439cab452

**Comment by boredsquirrel** [comment]
thanks! I played around with secureblue and tried Virtual machines, flatpaks and a bit more, and I can rebase to secureblue kinoite now!

I got a lot of errors when using nonwheel users, and I will report them here.

**Comment by boredsquirrel** [comment]
Just not really sure what is wanted and what not, the README  states 

> Avoid sacrificing usability for most use cases where possible

as you literally forbid me to say anything or explain, after locking the thread where I tried to give constructive ideas... I am unsure what is actually wanted.

- Is the easy possibility to enable and disable adb wanted or not?
- Should services that can be opt-in enabled in yafti have no just as easy way to disable them again? Why the one-way toggles?
- should users be able to do encrypted backups on an external drive?
- should users be able to install tails or fedora on a usb stick to share the system they are using with others?

All those would require some form of privilege management, controlled increase and decrease again. They can be done manually, but they are way more accessible if there are tools for it.

**Comment by RoyalOughtness** [comment]
> I got a lot of errors when using nonwheel users, and I will report them here.

Please only report them if they're unexpected. Using a nonwheel primary user will cause "issues" in that you'll need to use the nonwheel user in a TTY to perform admin operations. This is expected and intentional, so please don't report issues in this category.

**Comment by RoyalOughtness** [comment]
> Is the easy possibility to enable and disable adb wanted or not?

adb meaning android debug bridge?

**Comment by RoyalOughtness** [comment]
> should users be able to do encrypted backups on an external drive?
> should users be able to install tails or fedora on a usb stick to share the system they are using with others?

If by users you mean non-wheel users, by default those are operations restricted to wheel users. If users prefer to allow nonwheel users to do this, they can add a polkit rule enabling that. secureblue needs to consider that only some users will use separate wheel accounts and accommodate both use cases. Individual users can always modify that with overrides in /etc if they prefer other configurations.

**Comment by boredsquirrel** [comment]
yes, see [here](https://discussion.fedoraproject.org/t/is-adb-supported-out-of-the-box/98352/2)

adb and fastboot on Fedora are still a bit broken. Adb may be added upstream in ublue just. If it is fixed (something with [bad fastboot packaging](https://bugzilla.redhat.com/show_bug.cgi?id=2245557)) then it would require symlinking udev rules / or enabling adb.service

this would increase attack surface but needed for installing GrapheneOS for example. So it would be best as a temporary increase of attack surface, and then disabling it again easily

**Comment by boredsquirrel** [comment]
To the wheel user configs, it would be great to have the setup of an unprivileged user in yafti.

- add user (enter the name?)
- add its password
- add it to certain groups with opt-in (this has to be seperated, so by default ship rules that allow for example mounting, and then make it possible to add a user to the matching group to allow only this action)

This is a mix of upstream and not, as secureblue is faster at adopting these changes

**Comment by RoyalOughtness** [comment]
> Should services that can be opt-in enabled in yafti have no just as easy way to disable them again? Why the one-way toggles?

yafti is a one-time setup tool, so I'm confused why there would be a need to have a two way set of commands. if the user has no use for printers, they can skip it, if they do, they can enable it.

> adb and fastboot on Fedora are still a bit broken. Adb may be added upstream in ublue just. If it is fixed (something with [bad fastboot packaging](https://bugzilla.redhat.com/show_bug.cgi?id=2245557)) then it would require symlinking udev rules / or enabling adb.service

Again, fixing upstream breakage and usability issues is something you should report upstream and fix locally in the meantime. This repo isn't a place for you to catalog issues you run into with your use case or otherwise try to shoehorn in your specific use cases. It's specifically to provide hardened versions of the upstream images without **breaking** existing UX as much as possible. Do not make me repeat this.

**Comment by RoyalOughtness** [comment]
> To the wheel user configs, it would be great to have the setup of an unprivileged user in yafti.
> 
> * add user (enter the name?)
> * add its password
> * add it to certain groups with opt-in (this has to be seperated, so by default ship rules that allow for example mounting, and then make it possible to add a user to the matching group to allow only this action)

There is already a very simple UX for this and it's already documented. 

> This is a mix of upstream and not, as secureblue is faster at adopting these changes

That isn't an excuse for continuing to shoehorn in your out of scope requests.

**Comment by boredsquirrel** [comment]
So, without adding any changes to secureblue, would a guide here be wished, explaining how to add a user and what groups are needed for what tasks?

Also you didn't address the issue with a special group for actions that simply require wheel in upstream. I can report this there with a possible solution for sure.

**Comment by RoyalOughtness** [comment]
> So, without adding any changes to secureblue, would a guide here be wished, explaining how to add a user and what groups are needed for what tasks?

We already have it: https://github.com/secureblue/secureblue/blob/live/POSTINSTALL-README.md#create-a-separate-wheel-account-for-admin-purposes

What groups are needed will vary from use case to use case.

> Also you didn't address the issue with a special group for actions that simply require wheel in upstream. I can report this there with a possible solution for sure.

I did address it. It is up to the user.

**Comment by RoyalOughtness** [comment]
If you want to add more details there, feel free to suggest additions to the documentation.

**Comment by boredsquirrel** [comment]
https://github.com/secureblue/secureblue/pull/166/commits/b00310d926d4904dbb3a51357cbe79291d96ea16

**Comment by boredsquirrel** [comment]
oh and to the "one time setup" I would simply like a way to disable stuff like cups afterwards.

I dont think its "office" and "normie", most use laptops and will need printing like once a year. same for bluetooth, same for kde connect if a good working switch is found.

Adding these specific things to just would keep the coherent UX of just. In the end the best way would be to integrate it into desktop GUIs.

[ublue upstream actively refuses to support disabling cups in just](https://github.com/ublue-os/config/issues/177)

**Comment by RoyalOughtness** [comment]
> I dont think its "office" and "normie", most use laptops and will need printing like once a year. 

I see. Yeah then I guess we can add disable-cups as long as it's just the inverse of enable-cups.
