### ISSUE TITLE
force sddm to use wayland on Sericea

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#168]
@Sadoon-AlBader did you already find the right command to replicate 

```
[Wayland]
CompositorCommand=kwin_wayland --drm --no-lockscreen --no-global-shortcuts --locale1
```

using sway? This would be a great fix, as the current SDDM will use X.org right?

https://github.com/secureblue/secureblue/pull/141

**Comment by RoyalOughtness** [comment]
SDDM on sericea uses wayland.

https://packages.fedoraproject.org/pkgs/sway-config-fedora/sddm-wayland-sway/
