### ISSUE TITLE
Unsure: apply kernel hardening only after rebase to signed image

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#170]
Currently yafti pops up the first boot, but then the image is still unverified.

If possible I suppose it should only pop up after the rebase to signed, to have the 3rd reboot for the kernel arguments.

**Comment by RoyalOughtness** [comment]
This shouldn't matter, rebasing to signed after applying the kargs shoudl generate a new deployment using the signed base image and the kargs.
