### ISSUE TITLE
Very slow startup time

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#173]
I suppose this is due to using hardened_malloc as it even occurs before applying the kernel hardening.

The time to
- show the luks dialog
- unlock the luks volume and show sddm
- after SDDM show the cursor, then load the plasma desktop

those are at least twice as long as on regular Fedora Kinoite. I am wondering if this could be optimized, the speed of regular usage in the end seems normal and I will try to do some benchmarks on the same hardware.

**Comment by RoyalOughtness** [comment]
This is almost certainly because of entropy generation time due to distrusting the cpu and bootloader. It is expected and needed.

**Comment by boredsquirrel** [comment]
Okay, I think it could help adding something about this to the README, so that people *worship* the delay instead of complaining ;D

I am also not fully sure what this means, so linking some Docs would be highly appreciated.

**Comment by RoyalOughtness** [comment]
>  so that people worship the delay 

The delay isn't desirable, but it is expected and needed.

> I am also not fully sure what this means, so linking some Docs would be highly appreciated.

https://en.wikipedia.org/wiki/Entropy_(computing)
https://wiki.archlinux.org/title/Random_number_generation
https://github.com/QubesOS/qubes-issues/issues/6941

**Comment by adrelanos** [comment]
Could this be related to my cryptsetup bug report [cryptsetup luksFormat slowdown of factor ~ 6 when using hardened memory allocator Hardened Malloc](https://gitlab.com/cryptsetup/cryptsetup/-/issues/617)?

In that case, entropy was unrelated. Plenty of entropy was available / /dev/random was very fast. Yet, this slowdown was consistently reproducible.

(Note: The linked cryptsetup ticket got closed but not solved.)

**Comment by RoyalOughtness** [comment]
@adrelanos Not sure. Your ticket refers to luksFormat, not opening a drive. 

I'm assuming you weren't running that within seconds of booting, so plenty of entropy was already available. At boot, lack of entropy is a common issue if you're distrusting the cpu https://gitlab.alpinelinux.org/alpine/aports/-/issues/9960

**Comment by adrelanos** [comment]
The days where `cat /dev/random` requires more than a minute or so to fill up the screen are over. Nowadays that takes less than a second.

Nowadays thanks to `systemd-random-seed.service` and/or `jitterentropy` (or similar), the entropy pool should be full right after boot long before the LUKS password prompt.

You could test that by opening a recovery console or so at that time and then check `/proc/sys/kernel/random/entropy_avail` or test the speed with something like `pv /dev/random > /dev/null`. If it's fast, then sufficient entropy is available.

If entropy is slow, then that's a bug. And fixable, nowadays.
