### ISSUE TITLE
Add bluefin-dx-* variants.

### ISSUE THREAD

**Issue by CornPopGuy** [secureblue/secureblue#175]
Hi, please add the buefin developer experience editions: add bluefin-dx-* variants.

**Comment by RoyalOughtness** [comment]
Here you go: https://github.com/secureblue/secureblue/commit/e35c28293a4ad19bb77ed45bb21e784ffe4afcda

**Comment by RoyalOughtness** [comment]
FYI, I only added userns variants for bluefin-dx since the entire point of dx is to include packages that depend on userns.
