### ISSUE TITLE
Rebasing breaks the internet connection

### ISSUE THREAD

**Issue by aunefyren** [secureblue/secureblue#181]
Hey, very new to Fedora and rebasing, but want to give SecureBlue a try for my upcoming laptop.

Now, I am installing this in a VM, so this could be a non issue when installing on my laptop, but I wanted to check out the system first. I had some issues getting it installed on Hyper-V, but when I used VM Generation 2 and disabled secure boot, everything went well.

So after installing SilverBlue using the ISO, I run this command:
```
rpm-ostree rebase ostree-unverified-registry:ghcr.io/secureblue/silverblue-main-hardened:latest
```

After this I reboot. Upon system start up, the internet connection is gone and no amount of tweaking brings it back. I am hoping this is some VM issue, but I am not entirely sure. Does anyone know what could be happening?

Hope someone can help me out.

**Comment by wandapeter** [comment]
hello :-)

Im guessing this might be a HyperV problem. Maybe the required virtualization drivers are nor part of ublue.

could you maybe check the NetworkManager logs for any obvious errors?

**Comment by RoyalOughtness** [comment]
@aunefyren What @34N0 is correct. This is expected. I should probably remove the note to test on a VM first, that's from upstream but not an appropriate recommendation for secureblue because of the changes we make.

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/4fb96f6f6fdfa16d2e6999a11fbdf5615ff1096b

**Comment by aunefyren** [comment]
Thank you so much for the replies. I'll give it a go on a laptop. Cheers
