### ISSUE TITLE
Use initramfs for modifications instead of kargs as much as possible

### ISSUE THREAD

**Issue by fiftydinar** [secureblue/secureblue#182]
# Advantage
More reliable track of system changes with clean tracking & untracking of modification files in /etc.

# Solution
In this current state, it is not possible to have inbuilt kargs & initramfs modifications in image build-time.

Until then, use automated `initramfs-setup` as a more reliable solution (unofficial).

You included `modprobe` modification for Nvidia images, but it won't take effect until initramfs is rebuilt. The same thing is needed if you are using `modules-load.d` & `dracut` modifications.

You can use my unofficial module to solve that

This will also improve experience for LUKS users, which are one of the most frequent users of SecureBlue, by solving these issues:

https://bugzilla.redhat.com/show_bug.cgi?id=1801539
https://github.com/fedora-silverblue/issue-tracker/issues/3

To solve those 2 issues, just include those 2 files into `initramfs-setup` module:
`/etc/crypttab`
`/etc/vconsole.conf`

With this, we can also include some potential manual-setup kargs into initramfs, so they would be automatic.

F.e., you can include `nvidia` initramfs modification to apply automatically instead of user manually doing this:

```
rpm-ostree kargs \
    --append=rd.driver.blacklist=nouveau \
    --append=modprobe.blacklist=nouveau \
    --append=nvidia-drm.modeset=1
```

# More details about unofficial `initramfs-setup` module

https://github.com/ublue-os/bling/issues/101

# Is it reliable enough?
Mostly yes.

But my advice is to test & review this in `staging` before landing.

I would be very grateful for additional feedback!

**Comment by RoyalOughtness** [comment]
This is interesting. One note though is that the nvidia changes are indeed being applied despite not manually regenerating the initramfs:

```
 cat /proc/driver/nvidia/gpus/0000\:01\:00.0/power
Runtime D3 status:          Enabled (fine-grained)
Video Memory:               Active
```

This is the expected result of

`options nvidia NVreg_DynamicPowerManagement=0x02`

**Comment by RoyalOughtness** [comment]
Also, this project follows upstream as closely as possible and deviates only to make security improvements. We will look into pulling in this change if and when it becomes a part of ublue officially.

**Comment by fiftydinar** [comment]
> This is interesting. One note though is that the nvidia changes are indeed being applied despite not manually regenerating the initramfs:
> 
> ```
>  cat /proc/driver/nvidia/gpus/0000\:01\:00.0/power
> Runtime D3 status:          Enabled (fine-grained)
> Video Memory:               Active
> ```
> 
> This is the expected result of
> 
> `options nvidia NVreg_DynamicPowerManagement=0x02`

Hmm, I did not have this experience with my modprobe changes. Maybe some karg is doing it or something.
Other guides also mention that initramfs should be rebuilt when adding modprobe.

> Also, this project follows upstream as closely as possible and deviates only to make security improvements. We will look into pulling in this change if and when it becomes a part of ublue officially.

Understandable. Maybe this issue can be reopened if official state ever happens.
Cheers!

**Comment by RoyalOughtness** [comment]
> Hmm, I did not have this experience with my modprobe changes. Maybe some karg is doing it or something. Other guides also mention that initramfs should be rebuilt when adding modprobe.

My hunch is that it's because setting kargs in rpm-ostree regenerates the initramfs

**Comment by boredsquirrel** [comment]
so  should this be requested upstream in ublue?

**Comment by fiftydinar** [comment]
I would want to comment something on this issue, since rebuilding initramfs inside the image is possible & very easy now with this script at the end of the pipeline:

```
#!/usr/bin/env bash

set -euo pipefail

rpm-ostree cliwrap install-to-root /
QUALIFIED_KERNEL="$(rpm -qa | grep -P 'kernel-(\d+\.\d+\.\d+)' | sed -E 's/kernel-//')"
/usr/libexec/rpm-ostree/wrapped/dracut --no-hostonly --kver "${QUALIFIED_KERNEL}" --reproducible -v --add ostree -f "/lib/modules/${QUALIFIED_KERNEL}/initramfs.img"
chmod 0600 "/lib/modules/${QUALIFIED_KERNEL}/initramfs.img"
```

This would assure that modprobe changes would be applied.
