### ISSUE TITLE
Chromium crashes

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#185]
```
[25810:25888:0129/040905.056301:ERROR:mime_util_xdg.cc(136)] Invalid mime.cache file does not contain null prior to ALIAS_LIST_OFFSET=44
Warning: disabling flag --expose_wasm due to conflicting flags
Fontconfig error: Cannot load default config file: No such file: (null)
[25810:25810:0129/040924.022603:ERROR:interface_endpoint_client.cc(702)] Message 0 rejected by interface blink.mojom.WidgetHost
Warning: disabling flag --expose_wasm due to conflicting flags
# then Wayland reported the connection was lost
```

Using kinoite-laptop-userns-hardened.

Chromium is constantly crashing when using Github. Installed Extensions: NoScript, UBlock Origin. 

Also Tabs are crashing when trying to write something on GrapheneOS Discuss.

``` gdb chromium-browser ```

Didnt work.

**Comment by RoyalOughtness** [comment]
unable to repro. are you setting any custom config?

**Comment by boredsquirrel** [comment]
I will try a vanilla profile

**Comment by RoyalOughtness** [comment]
Closing for housekeeping reasons. Please reopen if you can repro on a vanilla config.
