### ISSUE TITLE
Pixelated font on stock chrmoum

### ISSUE THREAD

**Issue by Hasunemiku2015** [secureblue/secureblue#187]
I dont' know if it is clear on the screenshots, but the font on the chromium installed is a bit blurry... It shows when you zoom in on the images. The view on a flatpak google chrome is given for reference.

![Screenshot from 2024-01-30 12-39-32](https://github.com/secureblue/secureblue/assets/25132274/5f52724e-0dd0-4c73-9258-0bc9a315b44d)
![Screenshot from 2024-01-30 12-39-23](https://github.com/secureblue/secureblue/assets/25132274/5f8e327b-87e1-496f-ba0f-e6a45099c866)

I use wayland as a windowing system.
![image](https://github.com/secureblue/secureblue/assets/25132274/343446f0-1048-4a4c-a760-3ca17ad8bc0f)

**Comment by RoyalOughtness** [comment]
I can't repro, @34N0 are you able to? 

Also @Hasunemiku2015 do you have fractional scaling on?

**Comment by storopoli** [comment]
Could be fractional scaling. I remember having these issues when I was using Fractional Scaling.

**Comment by czhang03** [comment]
Might be related: https://www.reddit.com/r/Fedora/comments/15tu5o3/solution_to_blurry_wayland_applications/

I had the same issue on fedora workstation with wayland and proprietary nvdia driver (without fractional scaling IIRC) on electron app, and it is resolved by the command in the above post.

**Comment by RoyalOughtness** [comment]
Yeah, the only part that would still not make sense is why flatpak Chrome doesn't have the problem.

**Comment by RoyalOughtness** [comment]
@Hasunemiku2015 are you able to repro this on regular uBlue silverblue or upstream fedora silverblue? If so, this is likely a bug that needs to be filed against the upstream chromium package, which you can do [here](https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&component=chromium&product=Fedora&query_format=advanced). If you're unable to repro on regular uBlue silverblue, please reopen this issue.
