### ISSUE TITLE
[Image request] Build a Minimal Variant

### ISSUE THREAD

**Issue by czhang03** [secureblue/secureblue#189]
Hi, thank you for these great images. However, personally, I am neither a developer nor a system admin, I don't even use terminal at all during my daily routine.

So I was wondering if it is possible to build a minimal variant, without all the admin tools, like kernel-tools, vim, fzf etc from upstream. 

Also I was wondering if package like chkroot and yt-dlp can be removed if I almost never open terminal. I personally believe yt-dlp should be removed as its functionality is largely covered by FreeTube Flatpak.

Incentive for this variant:
- The more package we have, the harder it is for the package manager to find a up-to-date combo. In fact, I just switched from ublue to silverblue, and several package got updated.
- Less attack surface if we have less package on disk.

**Comment by RoyalOughtness** [comment]
This is out of scope, but I'm struggling to comprehend the rationale here.

> The more package we have, the harder it is for the package manager to find a up-to-date combo.

That's not how that works. The latest fedora packages are always pulled during the build. When you rebased, you were most likely not rebooted into the latest silverblue image, so rpm-ostree showed you upgrades.

> Less attack surface if we have less package on disk.

Attack surface is brought by running services, not files on disk.

**Comment by czhang03** [comment]
Thank you for your reply. I am not a security professional, so my understanding probably is misguided. 

Thanks for your correction.

**Comment by RoyalOughtness** [comment]
> Thank you for your reply. I am not a security professional, so my understanding probably is misguided.
> 
> Thanks for your correction.

No problem. That said, if you still want to remove packages just so you don't have to look at them, you can do so in startingpoint using secureblue as a base image. You can also use local layers. Just note that this doesn't reduce the image size, it just hides those packages in the resulting system.

**Comment by boredsquirrel** [comment]
Afaik yt-dlp was removed from the images.

Secureblue doesnt really add opinionated terminal packages by default, if those are there, discuss with upstream ublue about them. Have a look at the installed packages for each variant here:

https://github.com/secureblue/secureblue/tree/live/config/common

But I think having a "core" image without any desktop and specific packages, just like ublue-main, would be really handy. Not sure if this is needed to build something else, and you already added a ton of images!

Still, I suppose there would be use cases for a "core" variant.

**Comment by RoyalOughtness** [comment]
> But I think having a "core" image without any desktop and specific packages, just like ublue-main, would be really handy. 

There is no such thing. ublue's [main](https://github.com/ublue-os/main) is just a repo that builds all of ublue's images.

> Still, I suppose there would be use cases for a "core" variant.

There already is. The server variants of secureblue are downstream of [ucore](https://github.com/ublue-os/ucore)
