### ISSUE TITLE
Ensure gaming works

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#19]
Requirements for these new images are:

- Should include steam and lutris
- Should consistently build successfully
- Steam and Lutris should run successfully and run at least one game successfully

**Comment by boredsquirrel** [comment]
What is the state of using Steam Flatpak? @smcv might be helpful here

Lutris is also available as a Flatpak. Including ProtonUp* and Bottles may be useful

**Comment by RoyalOughtness** [comment]
> What is the state of using Steam Flatpak? @smcv might be helpful here
> 
> Lutris is also available as a Flatpak. Including ProtonUp* and Bottles may be useful

flatpak or not, it needs to work with hardened_malloc, which will require significant testing

**Comment by RoyalOughtness** [comment]
closing as we'll be handling this using flatpak

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/blob/live/FAQ.md#why-wont-flatpak-steam-run

**Comment by RoyalOughtness** [comment]
Gaming versions not required, use flatpak steam and follow the instructions above
