### ISSUE TITLE
Flatpak Hardening Give All Apps Host File System Permission

### ISSUE THREAD

**Issue by czhang03** [secureblue/secureblue#190]
In [this line](https://github.com/secureblue/secureblue/blob/de9b5a7aebc54e02466142861fb07e2b2b68fba7/config/files/usr/share/ublue-os/just/60-custom.just#L32), the parameter `--filesystem=host-os:ro` gives readonly file system permission to all packages.

**Comment by RoyalOughtness** [comment]
Yes, this is required to give flatpaks access to the hardened_malloc binary.

This has been discussed extensively here: https://github.com/secureblue/secureblue/issues/67

**Comment by boredsquirrel** [comment]
Have I understood correctly that `host-os` means just the `/usr` directory? This in read-only would allow to see the binaries and kind of fingerprint the system, but nothing else. This seems uncritical.

But the good solution is [here](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1680)

**Comment by storopoli** [comment]
> Have I understood correctly that `host-os` means just the `/usr` directory? This in read-only would allow to see the binaries and kind of fingerprint the system, but nothing else. This seems uncritical.

Oh if this is true then `--filesystem=host-os:ro` is not that scary

**Comment by wandapeter** [comment]
Giving access to `/usr` should still be considered a sandbox escape. Until there is a way for flatpaks to honour `LD_PRELOAD` without this escape our implementation is a security trade off. 

I haven't played around myself but depending on the binaries accessible in `/usr/bin` a further escape and unprivileged data access might be possible from within the flatpak sandbox.

Let me know if any of you want to give this a shot yourself. This experiment could be interesting in evaluating the current flatpak implementation. :)

**Comment by RoyalOughtness** [comment]
> Giving access to /usr should still be considered a sandbox escape. 

Yes

>  Until there is a way for flatpaks to honour LD_PRELOAD without this escape our implementation is a security trade off.

Or preferably, making hardened_malloc available as a flatpak :)

> I haven't played around myself but depending on the binaries accessible in /usr/bin a further escape and unprivileged data access might be possible from within the flatpak sandbox.

If anyone can demonstrate this, then sure. But if anything that would demonstrate a security flaw in flatpak's enforcement of the `ro` parameter. If that parameter is enforced properly, then at worst this setting permits only readonly access to a readonly-mounted filesystem (usr). So the tradeoff here is a very real benefit (using hardened_malloc in flatpaks/userspace applications) in exchange for a very theoretical downside (if any).

**Comment by boredsquirrel** [comment]
Wait, aren't filepicker portals doing that? Granting access to a specific file without any static permissions?

Afaik they also grant persistent permissions, sometimes. If there was a way to hook into the different xdg-desktop-portals and make them grant all installed flatpaks this exact filesystem access this could work or not?

(if not persistent then on every startup like a "getting Flatpak apps ready..." dialog)

**Comment by RoyalOughtness** [comment]
> grant all installed flatpaks this exact filesystem access this could work or not?

I asked about this upstream and they said it's not supported and to use the solution we're already using: https://github.com/flatpak/flatpak/issues/5575#issuecomment-1791018132

But again, this isn't even a theoretical security problem yet let alone a demonstrated one. Please bump this ticket only if upstream supports more granular control over /usr/bin, which they aren't planning, if hardened_malloc becomes available as a flatpak extension, or if you have concrete evidence of a security problem here.
