### ISSUE TITLE
The instructions for creating a separate wheel account for admin purposes in the POSTINSTALL-README are not dummy-proof

### ISSUE THREAD

**Issue by throwaway43** [secureblue/secureblue#197]
Found over [here](https://github.com/secureblue/secureblue/blob/live/POSTINSTALL-README.md#create-a-separate-wheel-account-for-admin-purposes)*.

If the instructions found below are followed to the letter, then the user might lock themselves out without assigning a password to the admin account and thus prevent a user from engaging in any activities on their machine that would otherwise have been a `sudo`/`pkexec` away. I don't think this is intended as the creation of the admin account wouldn't make any sense otherwise. 

1. `adduser admin`
2. `usermod -aG wheel admin`
3. `gpasswd -d {your username here} wheel`
4. `reboot`

Possible solution would be to include the `passwd admin` command somewhere in-between the first and the third command, with which the admin account is created properly.

FWIW, I've just freed myself from the above-mentioned situation. Fortunately, it's not crazy hard; but the 'rescue-operation' through a live USB was a lot less straightforward than other experiences I've had on distros that were not based on Fedora Atomic.

**Comment by boredsquirrel** [comment]
https://github.com/secureblue/secureblue/pull/198
