### ISSUE TITLE
Improved chromium solution

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#20]
We need one of the following:

- (Strongly preferred) Convince / work with upstream fedora chromium packagers to improve the security patching cadence, since the fedora chromium rpm is consistently behind
- Include Brave instead, requires using [optfix](https://github.com/ublue-os/bling/blob/f0c0192e100a01a507c72b80625c04d4688d3044/modules/rpm-ostree/rpm-ostree.sh#L17) and most likely some other creative methods
- Package Vanadium in copr

**Comment by boredsquirrel** [comment]
also having some privacy presets would be important when using upstream chromium. Like all the set Flags, "Chromium Webstore" preinstalled, restricted connections to Google etc. This is quite untransparent in Chromium, using Brave may remove the need for this though.

**Comment by RoyalOughtness** [comment]
> also having some privacy presets would be important when using upstream chromium. Like all the set Flags, "Chromium Webstore" preinstalled, restricted connections to Google etc. This is quite untransparent in Chromium, using Brave may remove the need for this though.

Privacy is not in scope for this project as is stated in the readme. We have a working up-to-date upstream build tag to use now, so this issue is resolved.

**Comment by monsieuremre** [comment]
With user name spaces disabled, I am pretty sure at least some but possibly more than just some of the chromium sandboxing features get weakened or disabled. Not sure tho, did not test. Just FYI.

**Comment by RoyalOughtness** [comment]
@monsieuremre please do not bump unrelated issues. If you have evidence that improvements can be made here, open a new issue.
