### ISSUE TITLE
Blacklisting Thunderbolt Module Causes AMD Device Not Entering s2idel properly

### ISSUE THREAD

**Issue by czhang03** [secureblue/secureblue#200]
According to the [official diagnostic script](https://gitlab.freedesktop.org/drm/amd/-/blob/master/scripts/amd_s2idle.py#L202) for AMD s2idle, AMD computers needs to use the thunderbolt kernel module to enter s2idel properly. The check for thunderbolt module can be found [here](https://gitlab.freedesktop.org/drm/amd/-/blob/master/scripts/amd_s2idle.py#L1339).

And I have indeed noticed a unusual amount of battery drain during suspend (only s2idel option avaliable). I was wondering is it possible to have this blacklist removed, or how should I manually enable the kernel module on my machine?

**Comment by RoyalOughtness** [comment]
You can remove it from `/etc/modprobe.d/blacklist.conf`.

**Comment by secretmango** [comment]
A better solution would be to add an `99-override.conf` in the same directory. If you edit a file in /etc, it will not be updated anymore. I am not sure if files in /etc will be updated at all?

**Comment by czhang03** [comment]
@secretmango Yes, now there is a ujust script that automates the override of kernel modules.
