### ISSUE TITLE
[NOTICE] debugfs=off breaks boot on the most recent Fedora images for iwlwifi hardware, temporary fix available below

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#204]
https://bugzilla.redhat.com/show_bug.cgi?id=2263692

Temporary fix: `rpm-ostree kargs --delete=debugfs=off`

**Comment by boredsquirrel** [comment]
Affected Kernels: 6.7x, rawhide 6.8x

**Comment by boredsquirrel** [comment]
note: it doesnt break boot, but prevents the wifi card from seeing any networks also on a Qualcomm Atheros card. Disabling the karg fixed it.

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/6d4884e3ada6ae7ea23341b4457823590a7eed1a
