### ISSUE TITLE
Networkmanager/kernel with kargs prevent boot since kernel 6.7

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#205]
https://bugzilla.redhat.com/show_bug.cgi?id=2263770

This is a pretty big issue. I tested Secureblue and Kinoite prerelease with the same kargs, and in both cases (kernel 6.7, 6.8) it does not boot. When not using the kargs it boots.

the old Kernel (update 2d or so ago) booted normally with the kargs.

This gave a clear "this is a kernel bug" error, so I assume this is a bug that is simply not bypassed when using the secure kernel arguments. I could do a binary search again which karg causes that issue, as its pretty critical.

It is reproducible on 2 seperate installs
- `Intel Wi-Fi 6 AX200`
- `Intel i7-1165G7` with internal Graphics
- all kargs applied as my Novacustom Firmware is not broken

**Comment by RoyalOughtness** [comment]
duplicate https://github.com/secureblue/secureblue/issues/204
