### ISSUE TITLE
[NOTICE] Bluetooth kernel modules to be disabled by default

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#213]
To enable them, simply comment out these lines in `/etc/modprobe.d/blacklist.conf`

```
install bluetooth /bin/false
install btusb /bin/false
```

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/2984116ec2a0e02b9e9969fab669c06792f5d93a

**Comment by trytomakeyouprivate** [comment]
For understanding:
- does this only include custom protocols or all bluetooth? What protocols are affected / unaffected?
- from that: my bluetooth still works, without ever changing that file, why?

**Comment by boredsquirrel** [comment]
I would like to discuss the nessecity of this. Even though it can be enabled back, this means users will not receive any updates for this blacklist.conf. (This has to be mentioned at least).

All the images use systemd, so instead I would propose to preconfigure this:

```
systemctl disable --now bluetooth.service
systemctl mask bluetooth.service
```

This should already be enough to ensure it is off, and users can change this (again, I think a `just enable-bluetooth` and a `just disable-bluetooth` are needed to switch on on demand, and then back off) without the problem mentioned above.

The mentioned bluetooth vulnerabilities are general attacks afaik, not related to "disabled service but enabled kernel module", is that right?

**Comment by RoyalOughtness** [comment]
> The mentioned bluetooth vulnerabilities are general attacks afaik, not related to "disabled service but enabled kernel module", is that right?

Nope, https://www.stigviewer.com/stig/red_hat_enterprise_linux_6/2018-11-28/finding/V-38682

> this means users will not receive any updates for this blacklist.conf.

Already asked and answered. https://github.com/secureblue/secureblue/issues/214#issuecomment-1961914624

**Comment by RoyalOughtness** [comment]
@trytomakeyouprivate it just occurred to me you can do this rather easily, just add:

```
install bluetooth /sbin/modprobe --ignore-install bluetooth
install btusb /sbin/modprobe --ignore-install btusb

```

in `/etc/modprobe.d/zz-bluetooth.conf`

If it works please add a general note about it in your PR in the FAQ.md.

**Comment by RoyalOughtness** [comment]
@trytomakeyouprivate I just tested this:

```
install bluetooth /sbin/modprobe --ignore-install bluetooth
install btusb /sbin/modprobe --ignore-install btusb
```
in `/etc/modprobe.d/99-bluetooth.conf`

it works.

**Comment by boredsquirrel** [comment]
yes got the same idea too. I think we should document this solution, where an alphabetically higher file will overwrite previous configs.

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/195d2e90ff5d79a07b8681419e972f5d2836ef1f
