### ISSUE TITLE
Chromium: "DefaultJavascriptJitSetting":2 breaks BigBlueButton

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#214]
Happened recently, BBB website didnt load any UI, did not initiate portal/permission requests and the site stayed blank.

Meanwhile on self compiled Firefox (using hardened-malloc) they worked perfectly.

The profile was vanilla, excluded from using the VPN using `mullvad-exclude chromium` (as this is also my vanilla profile).

This report is incomplete and I will add terminal output, test if it was the VPNs fault (maybe blocked nonproxied WebRTC?) and also test on upstream Fedora. I could not see which part failed, WebRTC most likely. 

(Btw on Vanadium (GrapheneOS) BBB works.)

Image used: kinoite-laptop-userns-main-hardened, a week ago.

**Comment by RoyalOughtness** [comment]
please confirm that you can't repro this on a regular ublue image.

**Comment by boredsquirrel** [comment]
is logging disabled for chromium? I couldnt get any output with `chromium-browser --enable-logging=stderr --v=1 &> ~/file.log`

On regular Fedora Kinoite (tested on rawhide after adding rpmfusion and libavcodec-freeworld) it shows logs always and videocalls work normally.

```
[2944:2944:0222/195946.652592:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[2944:2944:0222/195946.654694:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[2944:2944:0222/195946.655548:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

This was the only thing showing up, when in the videocall.

So vanilla Chromium on Kinoite rawhide works normally. Did not test with Kinoite 39 yet but I assume the same. 

Now I would like to get logs, do I need to disable a policy and overwrite it?

---

Okay seems I had another policyset with more settings, removed those policies so now only hardening.json and the readme are in there. Still the same result, only logs I got where

```
Some Chrome remote stuff disabled, warning!
Warning: disabling flag --expose_wasm due to conflicting flag
[Repeat once]
```

Okay its JIT... removing that policy line and allowing JIT makes it work again.

Would be very good to have something to change that. I mean videocalls are essential, and there are quite some sites reportedly broken without JIT

**Comment by boredsquirrel** [comment]
Some ideas:

Have multiple policy files (I had one that disabled logs lol, so that works normally). One like the "extreme kargs" that disables JIT and more.

Advise users to rename that file to .json.disabled or something to stop it from getting loaded.

Or add a 2 desktop entries, one that disables JIT, one that doesnt, rename them accordingly and give them different icons (like a warning sign on the one with JIT).

Those would be identical but would allow to use JIT when needed.

The best solution would be a dynamic GUI switch of course. I dont have a Google Account though.

**Comment by RoyalOughtness** [comment]
The solution here is for users who need JIT to enable it locally by overriding/editing the relevant files in `/etc`.

**Comment by boredsquirrel** [comment]
How would users change that without breaking updates? And what about the ideas I proposed, I think separating the JIT policy would make that a lot easier.

**Comment by RoyalOughtness** [comment]
Added an FAQ on enablement

https://github.com/secureblue/secureblue/blob/live/FAQ.md#i-need-javascript-jit-in-chromium-how-do-i-enable-it

**Comment by RoyalOughtness** [comment]
> How would users change that without breaking updates? And what about the ideas I proposed, I think separating the JIT policy would make that a lot easier.

If the user is changing their local config to an unsupported use case, it is their responsibility to maintain it. 

Literally any config item could cause issues, and by your logic we would have to have separate files for each of them. 

I've lost count of the number of times we've had this conversation.

**Comment by boredsquirrel** [comment]
The question was, how are those files handled? They are included in the images, if I leave the hardening.json file alone, will it be updated? And if I change it, will it stop getting any updates? I think thats the case.

We didnt have this conversation, this is just about JIT. It is a problem and afaik Edge has a toggle to enable or disable JIT (not sure though).

I think a separation into two policy files, one general and one for the "problem settings" is totally reasonable, and so far I only know JIT that is that problematic (videocalls, tutanota and more will not work). 

It would be easy to separate this, and add in a readme that disabling that file will fix those issues. I can do that, I just want to clear up what the best solution for that would be, as currently its either very secure or totally unsupported.

So, would you support a PR where I separate only that JIT config into a policy "extreme-hardening.json", add a readme explaining the reasoning and how to disable it, and add a readme somewhere at the front on how to troubleshoot these specific issues?

In general, is there a TROUBLESHOOT.md ? I would like to help make one.

**Comment by RoyalOughtness** [comment]
> And if I change it, will it stop getting any updates? I think thats the case.

Correct, for the second time, it's up to the user to manage.

> We didnt have this conversation

Yes we did, because it's yet another example of your prioritization of your own interests over community goals and norms.

> I think a sepatation into two policy files, one general and one for the "problem settings" is totally reasonable

It is not, because every change we make from upstream isn't the upstream default because it's a setting that can cause problems for some use cases.

**Comment by RoyalOughtness** [comment]
coincidentally, upstream chrome changed how JIT is managed and I removed the command line switch, so you can now configure allowing V8 per-site by adding your own separate policies file and adding sites to `JavaScriptJitAllowedForSites`

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/99aaa5b802953f5291fe2cab5691c9c9a976a9af

**Comment by boredsquirrel** [comment]
> prioritization of your own interests

I am pretty sad that you repeat this accusation. Having sites work (as an opt-in, easily doable and not by default, but also without being completely on their own) is not "my personal opinion". People need a secure OS that works.

Very happy about this new change! This will make specific sites work and it is the best solution. 

I suppose this will be different per action, here a seperate policy works, in other locations is may not, for example will users get updates to the `/etc/modprobe.d/blacklist.conf` after enabling bluetooth?

I will not open another issue, but the problem is "How to allow users to change presets and still receive all the other changes made upstream?"

I hope you understand the reasoning and it is totally not some random personal choice to need specific changes to make sites work.

**Comment by RoyalOughtness** [comment]
> is not "my personal opinion".
> I hope you understand the reasoning and it is totally not some random personal choice to need specific changes to make sites work.

It is a personal choice in that you are focused on getting your own local changes into their own separate files, without thinking about what this means for the broader project. For every single line of the chromium config file, the modprobe blacklist, and the sysctl file, someone might need to flip the setting back to how it was by default. This means having a separate file for every single configuration line, meaning hundreds of separate files. But you haven't even acknowledged this because you are just asking for your own personal changes to have separate files without caring about the broader implications.

>  for example will users get updates to the /etc/modprobe.d/blacklist.conf after enabling bluetooth?
>  "How to allow users to change presets and still receive all the other changes made upstream?"

No, they would have to maintain it themselves. This is due to the nature of how rpm-ostree systems work. All users still get updates in `/usr`, and it's up to the user to merge that with local changes they've made if any.

This isn't ideal but I'm not aware of a way around this. What we would need is patchfiles instead of full overrides. As far as I'm aware, there's nothing like this that's supported.

**Comment by boredsquirrel** [comment]
I understand that not every setting can be in a seperate file. This would be a separation right at this setting, as it is a common issue and the other things are way less problematic at least it seems like that. But I get your point.

I see you use the FAQ.md for these troubleshooting questions.

**Comment by boredsquirrel** [comment]
note: When checking `journalctl -f | grep chromium` I see this:

```
Feb 26 17:10:37 PC chrome[25157]: [25157:25157:0226/171037.679823:WARNING:config_dir_policy_loader.cc(136)] Failed to read configuration file /etc/chromium/policies/managed/hardening.json.readme.md: Line: 1, column: 1, Unexpected token.
Feb 26 17:10:42 PC chrome[25157]: [25157:25220:0226/171042.136597:WARNING:config_dir_policy_loader.cc(136)] Failed to read configuration file /etc/chromium/policies/managed/hardening.json.readme.md: Line: 1, column: 1, Unexpected token.
```

Also Chromium tends to freeze (but no journal output)  when I load an image from Dolphin either into fedora discuss or into the image viewer, using drag&drop.

okay read that "readme.md", strange that it still tries to read it but should be okay.

**Comment by RoyalOughtness** [comment]
> Also Chromium tends to freeze (but no journal output) when I load an image from Dolphin either into fedora discuss or into the image viewer, using drag&drop.

I am able to repro this. Can you check whether you can repro with a blank policy file and without hardened_malloc on a standard ublue image?

If you can repro with that setup, then please cut a ticket to the fedora chromium package or possibly to upstream chromium. If you can't please open a new issue here.

 You can also try using `nix` to install chromium to check for a repro with the nix chromium package, and if you can repro there as well, then definitely create an issue to upstream chromium at https://issues.chromium.org/issues

**Comment by RoyalOughtness** [comment]
In case anyone comes across this thread, you can accomplish local overrides using additional files that are later in the alphabet, like so: https://github.com/secureblue/secureblue/issues/213#issuecomment-1975266245

**Comment by boredsquirrel** [comment]
I think adding such a policy is not trivial so I would like to add it to the FAQ (a big PR is in the making), is this policy formatting okay?

```
{
    "JavaScriptJitAllowedForSites": [
        "https://example.com",
        "https://*.meet.example.net"]
}
```

Some things:
- always only allow https sites
- create such a alist
- some websites do load balancing, are those * working? I am not sure if I can try it as somehow that BBB site appeared to work again, even though I use secureblue policy and no override to that time.
