### ISSUE TITLE
The inclusion of `mitigations=auto,nosmt` as a kernel argument has started to cause peculiar behaviour on my system

### ISSUE THREAD

**Issue by throwaway43** [secureblue/secureblue#215]
Image: bluefin-dx-main-laptop-userns-hardened
CPU: AMD Ryzen™ 5 3500U with Radeon™ Vega Mobile Gfx × 8

Since about a week (at least since the 18th of February) I've noticed the following changes to how my system boots up:
- After the password for LUKS has been filled in, it takes about 5-15 minutes of time before GDM shows itself. Before, this used to take about a minute maximum.
- Right before GDM shows up, for about a second, Plymouth reveals itself and shows a bunch of text (mostly green) and goes away.
- Furthermore, my system normally defaults to Wayland. However, together with the aforementioned issues, an X11 session is started instead and I have to log out in order to return to my Wayland session. Peculiarly, it seems as if the Wayland session is still the default; however it seems as if it simply resorts to X11 because the Wayland session couldn't be established the first time around.

I've waited a couple of days in hopes that it would be resolved eventually, but as a solution didn't come I tried to troubleshoot it myself. What I did:
- `rpm-ostree reset` and reset the kernel arguments to their default values with `rpm-ostree kargs --editor`. With this, all the problems were resolved.
- I added my layers with the `rpm-ostree install ...` command. The following packages were installed that way: `bat` `corectrl` `gnome-shell-extension-caffeine` `gnome-shell-extension-dash-to-panel` `gnome-shell-extension-just-perfection` `gnome-shell-extension-pop-shell` `gnome-shell-extension-vertical-workspaces` `lsd` `stow` `tealdeer` and `zoxide`. I rebooted and everything still functioned as it should.
- Then I only added the kernel arguments that come with `ujust set-kargs-hardening` and right away the issue had shown itself again. After some back and forth, I eventually found the culprit; namely `mitigations=auto,nosmt`.
- Finally, I reapplied all the kernel arguments that I had previously, but which I had removed initially for troubleshooting purposes. And even with all of them back, the system continued to work as it should.

So at this point, I'm positive that `mitigations=auto,nosmt` is at least part of the problem. Ideally, the troubleshooting efforts should be redone, but this time I should add the kernel arguments right after the `rpm-ostree reset`, so before any layers are added, in hopes of (potentially) finding a package that simply doesn't play nice with `mitigations=auto,nosmt`. Furthermore, I should check if `mitigations=auto,nosmt` still continues to work on my laptop with any of the upstream projects as the fault is likely to be found there. Perhaps I might return back to this, but I have some deadlines that have be met in the upcoming days. So, only after those have been dealt with.

For whatever it's worth, I didn't layer any new packages between the last known (pre-bad) good state (at the 15th of February) and the first known bad state (at the 18th of February).

**Comment by RoyalOughtness** [comment]
So just to confirm, if you reapply mitigations=auto,nosmt, **all** of the behavior you listed comes back? And without it, it **all** goes away?

**Comment by RoyalOughtness** [comment]
also, please confirm that this still happens on a `silverblue` or `kinoite` image. If it doesn't, this should be reported to bluefin instead.

**Comment by throwaway43** [comment]
> So just to confirm, if you reapply mitigations=auto,nosmt, **all** of the behavior you listed comes back? And without it, it **all** goes away?

Exactly.

> also, please confirm that this still happens on a silverblue or kinoite image. If it doesn't, this should be reported to bluefin instead.

Great catch! Will do.

**Comment by boredsquirrel** [comment]
I have a Thinkpad T495 with the same hardware. I can try to reproduce this but from external SSD as I will sell it.

I had strange things with kinoite too, and I think this may be related (something strange happening with sddm and gdm?)

On my side SDDM
- doesnt show the user pictures anymore (I already switched themes, stayed the same)
- has a different layout, not the "scroll through users horizontally" but username prefilled with a dropdown menu, password empty.
- my BIOS output (boot logo or last messages) is shown right after I log in and SDDM disappears. Before that it was black, always. 

Those happened a while ago and dont cause big issues like that, but I will test and remove that karg.

Also afaik, `mitigations=auto,nosmt` are two configs, you might test both seperately to get a closer scope (`mitigations=auto`, `mitigations=nosmt`)

**Comment by RoyalOughtness** [comment]
> Also afaik, mitigations=auto,nosmt are two configs, you might test both seperately to get a closer scope (mitigations=auto, mitigations=nosmt)

That is not correct. The only valid values for `mitigations` are `off`, `auto`, and `auto,nosmt`.

https://www.kernel.org/doc/html/latest/admin-guide/kernel-parameters.html?highlight=auto,nosmt

**Comment by RoyalOughtness** [comment]
Also, please do not clutter existing issues with unrelated bugs.

**Comment by throwaway43** [comment]
So..., I did some testing and the results can be found below.

In all cases (unless stated otherwise), the images didn't have any layered packages nor did they have any (additional) kernel arguments except for `mitigations=auto,nosmt` (it's literally just (so without comments) `rd.luks.uuid=luks-... rhgb quiet root=UUID=... rootflags=subvol=root rw mitigations=auto,nosmt`). Furthermore, if 'issues' are present, then all the issues found in [the original 'post'](https://github.com/secureblue/secureblue/issues/215#issue-2149291337) are implied. Perhaps important to note, I also observed that **the fans of the laptop make substantial more noise in the phase between filling in the LUKS-password and the appearance of GDM whenever the issues are present**.

Up to the tests (in order of operation):
- `ostree-image-signed:docker://ghcr.io/secureblue/bluefin-dx-main-laptop-userns-hardened:latest` : **issues are present**
- `ostree-image-signed:docker://ghcr.io/ublue-os/silverblue-main:39` : **issues are absent**
- `ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:39` : during first reboot; after LUKS-password was filled in, it "updated kargs" (which in reality meant that `rd.luks.options=discard` was added, a kernel argument that I usually have as well and which I didn't remove for subsequent tests). After it had "updated kargs", it did another reboot and **issues are absent**.
 - `ostree-image-signed:docker://ghcr.io/secureblue/silverblue-main-laptop-userns-hardened:latest` : **issues are absent**
 - `ostree-image-signed:docker://ghcr.io/secureblue/bluefin-dx-main-laptop-userns-hardened:latest` : (did a 360 and returned back to where I had initially started) **issues are present**
 
I think the results speak for themselves.

**Comment by RoyalOughtness** [comment]
@throwaway43 The results are actually somewhat confusing. The issues are absent on other secureblue images like silverblue, and absent on the regular bluefin-dx image, but present on the secureblue bluefin image. This means that some package bluefin includes conflicts with some changes secureblue makes. This could be any number of things as Bluefin makes tons of changes compared to silverblue.

**Comment by throwaway43** [comment]
My apologies! Perhaps I should have put more thought on the chosen words. But, with *"the results speak for themselves"*, I meant the implication that's also found in your most recent comment. So, while it didn't provide any directives to pinpoint the problem, it at least narrowed down the possibilities.

FWIW, I did some more testing (for completeness' sake): the issues persist on both `ostree-image-signed:docker://ghcr.io/secureblue/bluefin-dx-main-userns-hardened:latest` and `ostree-image-signed:docker://ghcr.io/secureblue/bluefin-main-laptop-hardened:latest`. Furthermore, as uBlue allows tagging days, it made sense to utilize that functionality in order to do a better job at pinpointing the *location* of the *breaking point* and this allowed the discovery of the following insight:
- `ostree-image-signed:docker://ghcr.io/secureblue/bluefin-dx-main-laptop-userns-hardened:20240216` : **issues are absent**
- `ostree-image-signed:docker://ghcr.io/secureblue/bluefin-dx-main-laptop-userns-hardened:20240217` : **issues are present**

Between these two upgrades, the following packages got an upgrade:
`git-core 2.43.0-1.fc39 -> 2.43.2-1.fc39`
`git-core-doc 2.43.0-1.fc39 -> 2.43.2-1.fc39`
`python3-rpm 4.19.1-2.fc39 -> 4.19.1.1-1.fc39`
`rpm 4.19.1-2.fc39 -> 4.19.1.1-1.fc39`
`rpm-build-libs 4.19.1-2.fc39 -> 4.19.1.1-1.fc39`
`rpm-libs 4.19.1-2.fc39 -> 4.19.1.1-1.fc39`
`rpm-plugin-selinux 4.19.1-2.fc39 -> 4.19.1.1-1.fc39`
`rpm-sign-libs 4.19.1-2.fc39 -> 4.19.1.1-1.fc39`
***
`cockpit-machines 306-1.fc39 -> 307-1.fc39`
`kcli 99.0.0.git.202402152143.320dce8-0.fc39 -> 99.0.0.git.202402161852.c7fa6c6-0.fc39`
`raft 0.18.3-0.2.fc39 -> 0.22.0-0.1.fc39`
`tcpdump 14:4.99.4-2.fc39 -> 14:4.99.4-3.fc39`
`vim-common 2:9.1.031-1.fc39 -> 2:9.1.076-2.fc39`
`vim-data 2:9.1.031-1.fc39 -> 2:9.1.076-2.fc39`
`vim-enhanced 2:9.1.031-1.fc39 -> 2:9.1.076-2.fc39`
`vim-minimal 2:9.1.031-1.fc39 -> 2:9.1.076-2.fc39`

I was able to downgrade the packages found above the horizontal line through `rpm-ostree override replace ...` (`git` and `rpm` respectively), but alas... it didn't matter. I tried the same for the latter half, but they didn't seem to be affected by it or (instead) the command gave an error; which occurred for `vim`.

Honestly, I'm a bit lost at this point. What would be the best course of action on my side of things?

**Comment by throwaway43** [comment]
> I was able to downgrade the packages found above the horizontal line through `rpm-ostree override replace ...` (`git and rpm respectively`)

The *"..."* aren't replaced by `git` and `rpm`, but by their respective builds found on [Koji](https://koji.fedoraproject.org/koji/). Wanted to make that clear*.

**Comment by RoyalOughtness** [comment]
@throwaway43 It might not be a package upgrade. It could be a config change.

You should look through the bluefin and secureblue change history to try to identify the root cause. I'm not sure what else to recommend.

**Comment by throwaway43** [comment]
> I have a Thinkpad T495 with the same hardware. I can try to reproduce this but from external SSD as I will sell it.

@trytomakeyouprivate Thank you for your considerations! I believe this is a vital step to determine if it's even reproducible on other devices. Because if that's not the case, then I don't see any reason why this issue should remain open.

@qoijjj Thank you for pointing that out! Yesterday, before posting my most recent comment, I did look into the change histories for both projects. And if memory serves me right, there were little to no changes reported for Secureblue and those that were didn't strike me as particularly interesting as so far as being the cause for the issues. For Bluefin(-dx), there were more substantial changes, but I wasn't able to find anything useful beyond that. It's worth noting that I'm just a pleb and thus my evaluations don't hold much value, if at all :sweat_smile:.

Unfortunately, I don't have an additional device to test if this issue is even reproducible on other devices. On that note, for whatever it's worth, if no one can demonstrate that the issue is reproducible on other devices, then I don't see any reason for this issue to remain open.

Finally, I've actually personally given up on further troubleshooting efforts for now; I will simply not rely on the use of `mitigations=auto,nosmt` on my laptop.

**Comment by RoyalOughtness** [comment]
@throwaway43 you mentioned that the issue is present on `20240217`

Did you check both `auto,nosmt` **and** `auto` for that build?

**Comment by throwaway43** [comment]
> Did you check both `auto,nosmt` and `auto` for that build?

I actually hadn't checked `auto` for that build. Thanks for pointing that out! So I've just checked that now and `mitigations=auto` doesn't cause any issues.

**Comment by throwaway43** [comment]
Btw, am I correct to assume that the inclusion of `mitigations=auto` is strictly better than its absence? And thus, even if the issues with `mitigations=auto,nosmt` persists, this should not deter me from relying on `mitigations=auto`?

**Comment by RoyalOughtness** [comment]
> am I correct to assume that the inclusion of mitigations=auto is strictly better than its absence

No, it's the kernel default

**Comment by RoyalOughtness** [comment]
Based on the previous comments, this is only reproducible on bluefin. This means that bluefin makes changes that are incompatible with `auto,nosmt`. Please open a ticket capturing this on the bluefin issues tracker: https://github.com/ublue-os/bluefin/issues
