### ISSUE TITLE
[BUG] Impossible to rebase from a fresh Silverblue 39 system

### ISSUE THREAD

**Issue by diogotavc** [secureblue/secureblue#216]
Not sure this is a secureblue issue, so sorry if it isn't.

I was thinking about switching to secureblue from workstation, on my main machine, but wanted to make sure everything worked properly, for my use case, before jumping ship. Tested it in a VM, all good, then tried it on my old laptop (HP EliteBook 9470m with the vulnerable i5-3427u) and failed miserably. Waited a ton to make sure I was up-to-date (not sure it made much of a difference, just felt like torturing myself) and, once updates applied, I couldn't rebase.

1. Update Silverblue to the latest release
2. Attempt to rebase to _ostree-unverified-registry:ghcr.io/secureblue/silverblue-main-laptop-userns-hardened:latest_

I was expecting it to work and prompt me to `systemctl reboot` but, instead:
```
error: Executing %transfiletriggerin for glibc-common: bwrap(/usr/bin/sh): Child process killed by signal 4; run `journalctl -t 'rpm-ostree(glibc-common.transfiletriggerin)'` for more information
```
Here's my `rpm-ostree status`. I'm still on vanilla Silverblue.

```
State: idle
Deployments:
● fedora:fedora/39/x86_64/silverblue
                  Version: 39.20240225.0 (2024-02-25T01:01:41Z)
               BaseCommit: 8eedb59ec7974a78d5ede6217d87c96f0b46f721096faafb0037fc63ce66d1f4
             GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
          LayeredPackages: langpacks-en_GB
```

**Comment by diogotavc** [comment]
After successfully rebasing to bluefin (for testing purposes), another attempt at rebasing to secureblue was made, now met with another error:

```error: Sanity-checking final rootfs: bwrap(/usr/bin/true): Child process killed by signal 4```

It was noticed that, since the CPU (Intel i5-3427u, released in 2012) was so old, the problem was likely to be some sort of incompatibility with hardened_malloc. And sure enough, removing it was enough to complete the rebase.

**Comment by RoyalOughtness** [comment]
resolving since hardened_malloc was the issue

**Comment by boredsquirrel** [comment]
so if you remove hardened_malloc you can still use the system? This may reduce the systems security a bit, but documenting how this can be done can be still useful, as better use secureblue without hardened_malloc than dont use it.

**Comment by RoyalOughtness** [comment]
@trytomakeyouprivate I'm very hesitant to document this for a few reasons. One, it could lead to users abandoning hardened_malloc for unrelated issues. Two, even if the issue is hardened_malloc, there could be more specific solutions like overriding the LD_PRELOAD for a specific application. Or in the case of wireplumber a month or so ago, a genuine upstream bug.

If we document this, we will lose out on being able to look at issues case-by-case, which adds valuable data here especially when it comes to detecting and submitting upstream fixes for memory issues.

**Comment by boredsquirrel** [comment]
@34N0 no idea how this is related? Documenting something like "If you are certain that hardened_malloc is incompatible with your hardware, here is what you do. Do this as a last resort".

**Comment by wandapeter** [comment]
@trytomakeyouprivate sorry for the confusion. But the referenced commit in my fork isn't mine i had to rebase my fork and cherry pick a commit to be able to reopen an already merged pr. Creating this reference was unintended and i am unsure why it even exists.

Imo @qoijjj is right on this. One thing we could do is create a list containing known unsupported hardware.

**Comment by diogotavc** [comment]
@34N0 That'd be incomplete unless we diagnose why it's incompatible first. I can try and see why, for example, my i5-3427U is unsupported, so that we can put in the README.md how to check whether the CPU is supported or not before pulling.

**Comment by wandapeter** [comment]
Correct. Did you ever create an issue with the hardened malloc project?

**Comment by boredsquirrel** [comment]
Yes I think it would be best to have such a list / a list of features making hardware not work on their repo.

It is a general purpose allocator so not sure if they would do that.

@diogotavc thats 3rd gen (already v3 support but still old) and the u series. I can try on a Thinkpad i5-3320m in the future

**Comment by diogotavc** [comment]
Yes, it's very old.

Also, m series shouldn't have anything that u series doesn't have regarding hardened_malloc compatibility, but give it a try and report back.

**Comment by RoyalOughtness** [comment]
FYI for those following this thread, I've made some changes to the rpm spec that should enable older chipsets to use hardened_malloc.
