### ISSUE TITLE
[BUG] Cannot Enable Power Profiles Daemon

### ISSUE THREAD

**Issue by czhang03** [secureblue/secureblue#217]
**Describe the bug**
I cannot seem to find a way to enable `power-profiles-daemon` in secureblue. 

In the silverblue-main image, it seems like `power-profiles-daemon` is included, and enabled by default:
```
$ systemctl | grep power-profile
  power-profiles-daemon.service                                                                                                      loaded active running   Power Profiles daemon

$ rpm -q power-profiles-daemon
power-profiles-daemon-0.20-1.fc39.x86_64
```
However, in secureblue, `power-profiles-daemon` cannot be installed and it is not running:
```
$ rpm-ostree install power-profiles-daemon
Inactive requests:
  power-profiles-daemon (already provided by power-profiles-daemon-0.20-1.fc39.x86_64)
Checking out tree ...

$ rpm -q power-profiles-daemon
package power-profiles-daemon is not installed
```

**To Reproduce**
1. Start with ublue image `silverblue-main`
2. Rebase onto `silverblue-main-laptop-userns-hardened`
3. Noticed that `power-profiles-daemon` is removed
4. Restart, and notice that `power-profile-daemon` is not installed and cannot be installed

**Expected behavior**
Either `power-profile-daemon` is installed by default or can be overlaid

**Actual behavior**
`power-profile-daemon` neither installed by default nor can be overlaid

**Your current image**
```
● ostree-unverified-registry:ghcr.io/secureblue/silverblue-main-laptop-userns-hardened:latest
                   Digest: sha256:89d8b4ee809f96c9247aaaf4c6eb91d78b4f55686a59c845933876c8f590de7b
                  Version: 39.20240224.0 (2024-02-25T17:30:09Z)
          LayeredPackages: codium git-lfs libreoffice
```

**Comment by RoyalOughtness** [comment]
This is deliberate. Laptop images replace PPD with TLP for improved performance and battery life. If you want to use PPD, use a desktop image:

https://github.com/secureblue/secureblue/blob/live/config/recipes/laptop/laptop-bling.yml#L3

**Comment by RoyalOughtness** [comment]
also on an unrelated note, you're using the unverified image: `ostree-unverified-registry`. You should rebase to the signed image as described in the README.

**Comment by czhang03** [comment]
Thank you so much, I must have accidentally copied the unverified command when I was testing. 

Just FYI, for framework AMD in particular, [framework recommend strongly against using TLP](https://knowledgebase.frame.work/en_us/optimizing-fedora-battery-life-r1baXZh). So the decision to call this image "laptop" can be confusing to framework AMD users. If the PPD v.s. TLP is the only difference between the two image, maybe consider naming them "...-PPD" and "...-TLP" image?

**Comment by RoyalOughtness** [comment]
if you're using a framework laptop, you should be using a framework image.

Thanks for letting me know about the amd issue with TLP for framework images. I've added `-amd` framework images. You should rebase to:

`rpm-ostree rebase ostree-image-signed:docker://ghcr.io/secureblue/silverblue-framework-amd-hardened:latest`

**Comment by czhang03** [comment]
Thank you so much! 

However, as per upstream, the framework AMD version are recommended to use the `main` image. Hence, building a new image might not be strictly necessary. Maybe just some documentation could be enough?

**Comment by RoyalOughtness** [comment]
@czhang03 can you link the documentation that says amd frameworks shouldn't use the framework images?

**Comment by czhang03** [comment]
I am sorry, I was planning to attach the documentation, but forgot https://universal-blue.org/images/framework/

> Framework recommends NOT using tlp on the new AMD-based Framework 13. These images use tlp, so it is currently recommended to use the non-framework images if you own an AMD Framework 13. Check the community thread for the latest information.

**Comment by RoyalOughtness** [comment]
I see, okay. I will undo those changes and add docs

**Comment by RoyalOughtness** [comment]
Fixed: https://github.com/secureblue/secureblue/commit/1d54e521240bdd69e02c70a45608a28ae65ac3e7

**Comment by boredsquirrel** [comment]
Just fyi, Fedora 40 will likely switch from powerprofilesdaemom to tuned, [relevant thread](https://discussion.fedoraproject.org/t/f40-change-proposal-tuned-replaces-power-profiles-daemon-self-contained/94995)

**Comment by czhang03** [comment]
@trytomakeyouprivate I think I read somewhere that this is rejected for fedora 40, but I cannot find the source now. Anyhow, this change is not in the fedora 40 final change set. However, ublue do have plan to switch to tuned and retire framework image with its tlp config: https://github.com/ublue-os/framework/issues/73 and https://github.com/ublue-os/framework/issues/72

**Comment by py9mrg** [comment]
Hello,

Just FYI the ppd -> tuned switch has happened as of Fedora 41 so maybe something needs updating with these (and the wayblue) images?

**Comment by RoyalOughtness** [comment]
@py9mrg possibly, but this issue is almost certainly unrelated as it's very old. If you're seeing problems please open a new issue.

**Comment by czhang03** [comment]
@py9mrg I think this is caused by the conflict between TLP (used to be in the laptop image) vs PPD. I don't think we even have a laptop image anymore, nor do we use either TLP or PPD. so I don't think this relavent.
