### ISSUE TITLE
SDDM user list removal explanation?

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#222]
I am pretty certain `/etc/sddm.conf.d/kde_settings.conf` is causing that change in appearance:

![IMG_20240223_203205_243](https://github.com/secureblue/secureblue/assets/113100745/8d31868a-3c0d-4107-8fd2-2bd65f207d6a)

Normally there is a profile image, a button in the bottom right to change between the "fancy" mode and this view.

Is there a reason for this? The username is already filled in, so I see no security benefit (by requesting both username and password)

This happens only on Secureblue

**Comment by RoyalOughtness** [comment]
Unable to repro, and we don't make any such change.

The only change we make directly to sddm is to make it use kwin_wayland. Perhaps there is an upstream bug when using sddm with kwin_wayland:

<https://github.com/secureblue/secureblue/blob/live/config/files/kinoite/usr/etc/sddm.conf.d/10-wayland.conf>

**Comment by boredsquirrel** [comment]
very strange. I will ask in Discuss what could cause this.

**Comment by RoyalOughtness** [comment]
@trytomakeyouprivate thanks, I was able to repro but only on a specific monitor. So perhaps screen size is related? Just a hunch though.
