### ISSUE TITLE
Change issue templates to yaml

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#229]
Markdown is nice to write but the experience when creating issues is way worse. 

Examples:
- text input fields instead of removing placeholders
- required boxes that have to be checked
- a box with dropdown menu (select your image)

That would be a small cosmetical improvement, but may have advantages in the future, I could rewrite the templates.

**Comment by RoyalOughtness** [comment]
no thank you :)

**Comment by boredsquirrel** [comment]
I mean, there already were occasions where people just left the placeholders there etc. Having such input boxes is helpful especially on mobile
