### ISSUE TITLE
add clamav + configuration. 

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#23]
+ maybe clamtk as well

**Comment by boredsquirrel** [comment]
https://docs.clamav.net/manual/Usage/Configuration.html

https://www.howtoforge.com/tutorial/configure-clamav-to-scan-and-notify-virus-and-malware/

**Comment by RoyalOughtness** [comment]
Closing as this wouldn't add much and potentially adds attack surface

https://portswigger.net/daily-swig/cisco-clamav-anti-malware-scanner-vulnerable-to-serious-security-flaw
