### ISSUE TITLE
I want to contribute!

### ISSUE THREAD

**Issue by JohnyClassic** [secureblue/secureblue#232]
Not code, but I've been facing a severe cyber attack for 7 months... it won't stop. They're very well resourced and always find a way to breach hardened OSs. Qube OS is the only one they couldn't breach(i think)... but Qubes is a nightmare all on its own. Lol I installed silverblue last night and by this morning they were already in!! If you are interested in a real live case study, this would be a damn good one. I'm going to install secureblue as soon as I can. If they manage to breach it. I'll share the OS images so you can learn from them. If they don't well you know you're on to something!! I'll know pretty quick. That's for sure :/

**Comment by MkKvcs** [comment]
Just out of curiosity, how do you know you were breached? This sounds weird

**Comment by qoijjj** [comment]
This makes very little sense.

**Comment by JohnyClassic** [comment]
I'm sure it does sound odd. But the people involved have money and man power. I don't know how they got in. But I know they're in because once they're in what they want is always the same. They want to delete files and watch what I'm doing so they can stop it. So they always install apps and libraries related to streaming media and data off my comps. They usually start by placing the apps in the shared or public folder as a staging point. Even if they're disabled. I also start seeing these apps running in activity monitor. I'm no expert in this, but I've started to notice their strategies.

**Comment by JohnyClassic** [comment]
You guys tell me, are all these apps supposed to be in silverblues share folder?
![Uploading 20240307_100807.jpg…]()
![Uploading 20240307_100802.jpg…]()

**Comment by qoijjj** [comment]
@JohnyClassic Spreading FUD and baseless conspiracy theories is not welcome here. This is your first and final warning. A single additional comment or post on this subject or alluding to it at all again will result in a permanent ban.

**Comment by JohnyClassic** [comment]
What? It's one thing to not agree or not be interested. But I'm a real person with a real and very serious problem that I need to learn more about. And I definitely need a secure os. If you see something I got wrong, teach me. But I can assure you it's real because our local police is on this. But that doesn't change the fact that I need to protect my family in the meantime. Ban me, I'm not interested in ignorance.
