### ISSUE TITLE
[BUG] Server images contain docker even when no-userns selected

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#235]
The server images also include docker, which is a ublue decision. This means the "remove podman, toolbx, distrobox" is not sufficient for the "server" variant, being the only one that also has docker installed.

This would mean the server variants need a different removal to also include docker in the no-userns variant. Or remove docker, but especially docker-compose is pretty important and I suppose people prefer it over podman sometimes.

**Comment by RoyalOughtness** [comment]
I was working on this but based on the docs it seems docker can be used without userns. If this is inaccurate, please reopen.
