### ISSUE TITLE
Question: is LD_PRELOAD only set for already installed flatpaks?

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#236]
I had Thunderbird working normally before, then for some reason yafti appeared again, and I enabled "harden flatpaks". This caused Thunderbird to not start.

I guess that Thunderbird didnt have the LD_PRELOAD before, as `jemalloc` is not compatible with hardened_malloc and it always crashes. So I guess from that that the LD_PRELOAD only applies for already installed flatpaks?

2 things:
- notify users that they need to reapply this hardening
- maybe automate the hardening so newly installed apps also get it? but what about opt-outs?
- does it even make sense to do it in yafti, when this is often a setup where no apps are installed?

If this is not the case, I can't explain the thunderbird issue.

**Comment by mkkvcs** [comment]
No, LD_PRELOAD applies to apps installed after setting it as well

**Comment by RoyalOughtness** [comment]
@MkKvcs is correct. Yafti reappears if you rebase or if the config changes, and the config changed a bit recently.

The LD_PRELOAD setting is set globally and this can be confirmed in Flatseal
