### ISSUE TITLE
Enable Podman with suid

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#24]

**Comment by RoyalOughtness** [comment]
Is there evidence that this is possible? This issue contradicts what you mentioned previously:

> But as this doesnt even remotely exist for Podman

**Comment by boredsquirrel** [comment]
> I don't think it is even possible to write podman like this. If the user namespace is created as root then only root is the owner and can manage it, thus it would mean we cannot drop the privs right away and need them to setup everything, we could only drop them for the container. And this functionality already exists in the form of `sudo podman run --userns=auto` or `sudo podman run --subuidname <user>` if you want the mapping from a specific user.

[Link](https://github.com/containers/podman/issues/20720#issuecomment-1824697373)

So I guess we would need to try that out. Or follow their recommendation and just disable this limitation.

I still didnt completely get what this means, but it would require the use of sudo to create containers, but setting their user namespace to the current user sounds like it could be automated.

Toolbox is currently removed, distrobox is not. I guess one could modify distrobox to support this, as it sounds this would break some features. So for sure this requires some testing

**Comment by boredsquirrel** [comment]
https://kinvolk.io/blog/2020/12/improving-kubernetes-and-container-security-with-user-namespaces/

https://www.redhat.com/en/blog/whats-next-containers-user-namespaces

https://tore.tuhh.de/handle/11420/7891 [PDF](https://tore.tuhh.de/dspace-cris-server/api/core/bitstreams/615c067a-05ba-45c7-9433-bedee599778b/content)

**Comment by RoyalOughtness** [comment]
> > I don't think it is even possible to write podman like this. If the user namespace is created as root then only root is the owner and can manage it, thus it would mean we cannot drop the privs right away and need them to setup everything, we could only drop them for the container. And this functionality already exists in the form of `sudo podman run --userns=auto` or `sudo podman run --subuidname <user>` if you want the mapping from a specific user.
> 
> So I guess we would need to try that out. Or follow their recommendation and just disable this limitation.
> 
> I still didnt completely get what this means, but it would require the use of sudo to create containers, but setting their user namespace to the current user sounds like it could be automated.
> 
> Toolbox is currently removed, distrobox is not. I guess one could modify distrobox to support this, as it sounds this would break some features. So for sure this requires some testing

So podman with suid is already supported then? That's great news.

For distrobox you're correct, it probably should be removed until we have a demonstrated method of it working. Let me know if you find a way to get toolbox and/or distrobox working without unprivileged userns

**Comment by boredsquirrel** [comment]
I would not remove random packages because they are currently broken. Lets wait a bit, I guess some way will be possible.

For example creating the podman container manually and afterwards using distrobox could be imaginable

**Comment by ArtikusHG** [comment]
Podman (and distrobox/toolbox) are *fundamental* to the immutable distro model, and many programs are basically unusable without those, even with layering mechanisms in place (not to mention that layering too many packages makes updates much less reliable). Why is this closed as completed? Podman is currently being removed from the image. Upstream distrobox currently doesn't support suid, but we should at least look into getting podman working.

**Comment by RoyalOughtness** [comment]
> Why is this closed as completed?

@ArtikusHG This was originally closed as not planned, but I attached it to a PR which when closed moved it to completed :smile:

> Podman (and distrobox/toolbox) are fundamental to the immutable distro model

While they're certainly very useful, saying they're fundamental is a bit of a stretch. Flatpak and layering can cover all use cases, albeit with less convenience.

> Podman is currently being removed from the image. 

Yes because it doesn't function properly so there's no use including it. Per the issue thread on the podman page, there is a way to use it without user namespaces, but it requires running podman as root. This seems arguably worse than just enabling usernamespaces depending on the use case.

> Upstream distrobox currently doesn't support suid, but we should at least look into getting podman working.

I agree, I had originally closed it as not planned because it seems like this is an upstream issue where this feature simply isn't available. I can reopen it though if you're interested in working on getting it working.

**Comment by boredsquirrel** [comment]
@qoijjj 

> Flatpak and layering can cover all use cases

Not true for Software not in Fedora, like stuff directly available as a Docker/Podman container, or software from other distros. This would mean introducing maybe less secure libraries etc, so understablable if not wanted.

>  there is a way to use it without user namespaces, but it requires running podman as root

as far as I understood it requires setting the namespace as the same as the users or setting a custom namespace for the container with root, but the container could be rootless.

So making it work easily and documented is upstream. But tbh the developers didnt seem interested in doing so, as afaik Browsers, Flatpak, Podman, Docker etc. all rely on user namespaces and they are seen as "secure enough compared to their benefits"

**Comment by RoyalOughtness** [comment]
> Not true for Software not in Fedora, like stuff directly available as a Docker/Podman container, or software from other distros.

Sure, there are probably some examples of that. It would still be beneficial to get podman etc working, but it seems like it's unsupported at this time.

> This would mean introducing maybe less secure libraries etc, so understablable if not wanted.

No that's not a point of concern here.

> afaik Browsers, Flatpak, Podman, Docker etc. all rely on user namespaces and they are seen as "secure enough compared to their benefits"

Flatpak and browsers don't all rely on userns. But yes, the support for this needs to come from upstream.

**Comment by boredsquirrel** [comment]
I am wondering and couldnt find anything about this. Chromium normally uses userns for every tab, to isolate them from another.
Isnt the tab sandbox broken by disabling it? And what about Flatpak, are these apps all run as root?

**Comment by RoyalOughtness** [comment]
> I am wondering and couldnt find anything about this. Chromium normally uses userns for every tab, to isolate them from another. Isnt the tab sandbox broken by disabling it? 

No, open chrome://sandbox

It uses the suid sandbox. https://github.com/chromium/chromium/blob/main/docs/linux/sandboxing.md#The-setuid-sandbox


> And what about Flatpak, are these apps all run as root?

No, bubblewrap just uses suid instead.
