### ISSUE TITLE
[FEAT] Disable KDE Store integrations for Kinoite

### ISSUE THREAD

**Issue by starkle** [secureblue/secureblue#242]
**Describe the benefit this feature would provide to the project**
The [KDE Store](https://store.kde.org) is a repository for themes and other add-ons to various components of the Plasma desktop. Unfortunately, by design, this user-submitted content often runs arbitrary code. Recently this Reddit user reported on a faulty script which immediately wiped all their drives: 

https://old.reddit.com/r/openSUSE/comments/1biunsl/hacked_installed_a_global_theme_it_erased_all_my/

This has sparked a conversation among KDE developers about what can be done to mitigate this risk. This [blog post](https://blog.davidedmundson.co.uk/blog/kde-store-content/) from David Edmondson gives a good overview. However, even if content moderation and add-on sandboxing improves, secureblue users should likely not be exposed to this attack vector at all.

**Describe the solution you'd like**
From the blog post above:

> If you're a sys-admin you might want to consider adding the following to block users installing addons with the following [kiosk](https://develop.kde.org/docs/administration/kiosk/introduction/) snippet.

    /etc/xdg/kdeglobals

    [KDE Action Restrictions][$i]
    ghns=false

I've confirmed this will disable the "Get New ____" options within System Settings and Dolphin. Discover still shows the categories for Plasma Addons and Application Addons, but nothing appears when exploring them or searching.

**Describe alternatives you've considered**
This is a similar threat model to GNOME extensions. I haven't confirmed if secureblue disables those, but the Brace project does for similar reasons.

**Declaration**
- [x] I declare that I have read the README and my feature request is in-scope.

**Comment by RoyalOughtness** [comment]
Thank you for bringing this up. The fact that themes for plasma are allowed to execute scripts in a broad context is appalling. 

Disabling gnome extensions probably falls into a similar boat.

I assume some users will want to be able to re-enable this, however, so I'll be adding `ujust` commands to do so as well. I will have this out shortly.

**Comment by starkle** [comment]
I was reading the Kiosk documentation and it looks like if you remove `[$i]` the key is no longer immutable, meaning the user config in $XDG_CONFIG_HOME can override it. This might be an easier way to re-enable this for users who want it.

    /etc/xdg/kdeglobals
    [KDE Action Restrictions]
    ghns=false

    ~/.config/kdeglobals
    ...
    [KDE Action Restrictions]
    ghns=true

https://develop.kde.org/docs/administration/kiosk/introduction/#kdes-configuration-file-structure-and-hierarchy

https://develop.kde.org/docs/administration/kiosk/keys/#ghns

**Comment by RoyalOughtness** [comment]
@starkle Then it's being set in not just two (/usr/etc and /etc) but three places.

A just command seems much simpler and more user friendly

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/cb67ab87f690c34297f5abaa8db6a78593c791c0

**Comment by fiftydinar** [comment]
> Disabling gnome extensions probably falls into a similar boat.

Gnome extensions are more secure because they are reviewed by the team before extension is allowed to be on https://extensions.gnome.org/

Users rarely download extensions from 3rd parties, they just use Gnome Extensions app or Extension Manager, which uses https://extensions.gnome.org/ platform for viewing & managing extensions.

F.e. Rounded Window Corners extension did not pass review for Gnome 45 due to code quality in some areas.
So reviewing team can be strict.

**Comment by RoyalOughtness** [comment]
@34N0 that's good to know, thanks.

**Comment by wandapeter** [comment]
> @34N0 that's good to know, thanks. 

I think you mean @fiftydinar :-)

**Comment by RoyalOughtness** [comment]
Whoops, yes 😄 

☕
