### ISSUE TITLE
Sudo on every execution

### ISSUE THREAD

**Issue by bigpod98** [secureblue/secureblue#243]
So while i do understand the reasoning why it would seem good to force password on every sudo usage but as with almost any such prompt, prompting way too much can lead to fatigue.
This can be specially problematic when you need to run multiple sudo commands one after another this policy would be annoying and cause fatigue, which is why finding a reasonable default with short timeframe that still allows for burst usage without multiple prompts.

Result of such fatigue is likely to be user switching to root often which can and should be considered worse outcome then having no prompt for short period of time.

**Comment by RoyalOughtness** [comment]
I agree with you. The default of 15 minutes is still excessive, but 0 is probably too aggressive. 

Maybe 1?

**Comment by bigpod98** [comment]
yea 1 minute seems pretty ok

**Comment by RoyalOughtness** [comment]
I'll update this shortly. If you have any other suggestions please feel free to open issues

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/67e114ce4b8ff50ce9a3e13f0170ac5ab42cda7e
