### ISSUE TITLE
[BUG] I need help to figure out why Firefox (RPM) refuses to start after applying some hardening tweaks

### ISSUE THREAD

**Issue by cig0** [secureblue/secureblue#246]
**Describe the bug**
Hi :wave: 

First and foremost, congratulations and thanks a lot for `secureblue` :blue_heart:

I'm cherry-picking some of your tweaks and applying them to my images (the whole combo is a bit restrictive for me):
- https://github.com/cig0/bluebuild/tree/main/config/scripts
- https://github.com/cig0/bluebuild/tree/main/config/files

**Actual behavior**
When applying the hardening tweaks mentioned above, Firefox refuses to launch with the following message:

![Spectacle-Screenshot_20240330_190812](https://github.com/secureblue/secureblue/assets/394089/23a042e9-fe80-4d4b-b166-0b7cdc2142ea)

I tried launching Firefox from the CLI, hoping to see some error logs, but all I got is:

```
~ % firefox
ExceptionHandler::GenerateDump cloned child 7496
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
```

(_Note: it is worth mentioning Firefox is installed as an RPM as part of the upstream `kinoite-{main,nvidia}` images; I haven`t replaced it yet with the Flatpak version._)

**Your current image**
```
% rpm-ostree status   
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/cig0/perrrkele:39
                   Digest: sha256:f63eb9f93bec20c97ed5c2881a2977adf28390e22fe073ad735ba9b09d8c3989
                  Version: 39.20240329.0 (2024-03-29T17:08:23Z)
          LayeredPackages: osquery sublime-merge sublime-text warp-terminal

  ostree-image-signed:docker://ghcr.io/cig0/perrrkele:39
                   Digest: sha256:6c0308b75fe26c75cf580fa5c413de89f5c098e94f153034e03058c3f0b51cba
                  Version: 39.20240330.0 (2024-03-30T21:41:04Z)
          LayeredPackages: osquery sublime-merge sublime-text warp-terminal
```

**For all images**
- Confirm you cannot repro on a uBlue base image: **The problem only presents when applying the hardening tweaks**

---

I'm scratching my head here trying to understand which changes break Firefox, but none of them is evident to me!

Thanks

**Comment by cig0** [comment]
All right, the issue seems to be related to the file `ld.so.preload`, forcing the apps to use the hardened memory allocation library, I presume?

FWIW, the `hardened_malloc` package seems to be correctly installed:

```
% rpm -qa | gi malloc   
jemalloc-5.3.0-4.fc39.x86_64
mimalloc-2.1.2-2.fc39.x86_64
hardened_malloc-12-6.fc39.x86_64
```

**Comment by RoyalOughtness** [comment]
Yes, firefox has a history of issues with hardened_malloc: https://github.com/GrapheneOS/hardened_malloc/issues/123

Which adds to the already long list of reasons to prefer chromium over firefox if you care about security :smile:

> applying them to my images (the whole combo is a bit restrictive for me):

Even if so, I strongly recommend for your own sake that you follow the recommendation in https://github.com/secureblue/secureblue?tab=readme-ov-file#customization and use secureblue as a base image. Any changes you dislike you can still overwrite in your custom image. But this way, you don't have to constantly check the secureblue repo for changes.

**Comment by RoyalOughtness** [comment]
Also, FYI, your build has several redundancies.

For example you're adding gstreamer plugins, but they're all already included in all ublue base images: https://github.com/cig0/bluebuild/blob/main/config/modules/rpm-ostree-general-cli.yml#L25

**Comment by cig0** [comment]
Thanks for the heads up! I identified those overlapping `gstreamer1` packages:

![Spectacle-Screenshot_20240331_025811](https://github.com/secureblue/secureblue/assets/394089/d021773a-2cc2-4aa1-965c-e11153e5560b)

**Comment by RoyalOughtness** [comment]
There are others, too, like `gstreamer1-plugins-ugly` which is the unmaintained rpmfusion version of `gstreamer1-plugins-ugly-free`. There isn't really any reason to pull in the unmaintained version.

**Comment by cig0** [comment]
@monsieuremre thank you so much for taking the time to stop by and share this significant bit 🙌

_**TIL**_

**Comment by RoyalOughtness** [comment]
@monsieuremre Do not spread baseless misinformation on this project. Also, fingerprinting has nothing to do with security.
