### ISSUE TITLE
Adding aurora and its variants would improve the project

### ISSUE THREAD

**Issue by CornPopGuy** [secureblue/secureblue#248]
**Describe the benefit this feature would provide to the project**
A clear and concise description of the benefit.
- Allow users to benefit from KDE and bluefin.

**Describe the solution you'd like**
A clear and concise description of what specific change you would like.
- Add aurora and all of its variants (such as aurora-dx-*, aurora-*) from https://github.com/NiHaiden/aurora to secureblue.

**Describe alternatives you've considered**
- Use bluefin secureblue variants, till aurora images are added.

**Declaration**
- [x] I declare that I have read the README and my feature request is in-scope.

**Comment by nicknamenamenick** [comment]
I'm not part of the secureblue project, but I would hold off adding Aurora for a little longer.  There is a good chance that it will be part of Bluefin [soon](https://github.com/ublue-os/main/issues/533).

**Comment by RoyalOughtness** [comment]
@nicknamenamenick which just means we'll need to change the base image when that happens right?

**Comment by RoyalOughtness** [comment]
That doesn't seem like a blocker, if so.

**Comment by nicknamenamenick** [comment]
> @nicknamenamenick which just means we'll need to change the base image when that happens right?

Yeah it's moving to the Bluefin repository eventually.  If that isn't much of a problem, then it should be fine to add Aurora if you want to.

**Comment by RoyalOughtness** [comment]
@nicknamenamenick yeah it should be fine. the only weird bit is I think we're going to need to add it alongside wayblue to the set of images not signed by ublue: https://github.com/secureblue/secureblue/blob/live/.github/workflows/build.yml#L99

@MkKvcs fyi

**Comment by RoyalOughtness** [comment]
thanks @MkKvcs for taking care of this
