### ISSUE TITLE
[FEAT] A separate browserless images

### ISSUE THREAD

**Issue by ghost** [secureblue/secureblue#250]
**Describe the benefit this feature would provide to the project**

Browser less image would let people unsatisfied with a browser at rpm-ostree level have a possibility to have an image that do not need layering to use, of course I do know the problem linked with flatpak browser, but at lease this browser less images (why not the one based on fedora gnome), would remove every package useless for browser in flatpak.

Reducing the surface attack for people who don't' want to use chrome, but also let those same people have the layering disabled in rpm-ostree.

**Describe the solution you'd like**

An image version who do not ship any browser or dependency browser related not needed by flatpak browser.

**Disclamer**

I do know that using flatpak browser have drawback and they will not be hardened, if this image is done I can help to create a wiki page (if not already here) how to harden flatpak browser as much as possible.
I do also know that username space will be needed for this image and so no version without it can be safely done.

I know replacing or modify the default browser is not in scope, but having an image without any browser may be (why I ask and why I would totally understand a refusal)

**Declaration**

- [x] I declare that I have read the README and my feature request is in-scope.

**Comment by mkkvcs** [comment]
Deliberately making images less secure by forcing users to use browsers in flatpak is not only not in scope, but against everything this project stands for. This also makes very little sense overall.

**Comment by ghost** [comment]
> Deliberately making images less secure by forcing users to use browsers in flatpak is not only not in scope, but against everything this project stands for. This also makes very little sense overall.

When it's true if you think about chromium based browser and the clash between both sandbox but that is quite false in case (of mine) where it's firefox that will be used as flatpak.

But even in case of chromium this kind of compromise is "technically" better than layering, also "again technically" base browser always have access to full home when flatpak one can be tweaked to avoid it.

So in this case I think (but some may think I'm wrong) we are more in the "what do I prefer to" case.

**Comment by mkkvcs** [comment]
How is it even technically better than layering? This makes no sense. The chromium sandbox is not for you to deny /home access to the browser. Running chromium as a flatpak severely reduces the effectiveness of the chromium sandbox, thus should be avoided. Using firefox is a security nightmare as a whole. Please read the README, this is specifically answered.

**Comment by ghost** [comment]
> How is it even technically better than layering? This makes no sense. The chromium sandbox is not for you to deny /home access to the browser. Running chromium as a flatpak severely reduces the effectiveness of the chromium sandbox, thus should be avoided. Using firefox is a security nightmare as a whole. Please read the README, this is specifically answered.

So if I understand well you solely decide that no images will never be browser less...
Ok it seem I'm in a project of security people that cannot tolerate that other people have different threats model.

I don't have the time for that kind of pointless debate.

But funnily but forcing out people with other threats model you only will reduce their security since they will use the basic fedora without hardening.

An so you will do the exact opposite of the goal of this project
Congratulations I guess ?

**Comment by mkkvcs** [comment]
I am not the maintainer, I do not decide anything.

**Comment by RoyalOughtness** [comment]
> threat model

The largest attack surface of the overwhelming majority of desktop use cases is the browser. As a result, you'll notice this project and projects like GrapheneOS providing a maximally hardened browser experience out of the box. You don't see GrapheneOS shipping browserless images :slightly_smiling_face: because that would be irresponsible. A maximally hardened project should be especially focused on hardening the largest attack surface in the image. Removing the browser completely would do exactly the opposite of this.

> it's firefox that will be used as flatpak

There is nothing preventing you from using firefox as a flatpak on secureblue today. Having chromium installed does not increase attack surface in the same way it would on android where the default browser is used as a webview. This isn't the case on desktop linux. If you don't want to use chromium, then don't use it. Just don't expect support for other browsers.

Your repetition of "other people have different threats model" means you fundamentally misunderstand what a threat model is and what attack vectors are present in a browser. If we're both using a browser to browse the web, we have at a bare minimum highly overlapping threat models.

> But funnily but forcing out people with other threats model you only will reduce their security since they will use the basic fedora without hardening.

Anyone neglecting to protect themselves against the largest point of attack surface in their system never had security as their top priority to begin with. They are not the target audience of this project

**Comment by ghost** [comment]
@qoijjj 
First for : Having chromium installed does not increase attack surface is not true ANY software unused is a surface attack because it can have security hole.

So : 
What do you think about a browser less image but with the hack some use (using toolbox or distrobox as way to install any other browser) ?

with the addition of : 
$ toolbox run mkdir /home/foo 
$ toolbox run env HOME=/home/foo bash 

Or some trick in the file in /etc/profile.d inside the toolbox to override $HOME

I would give a way to have a browser less image, Browser and their dependency isolated, do not rely on flatpak and have a way to easily change browser and finally isolating making more difficult to the browser to have access to user home without broking the sandbox ?

Of course this toolbox may need a copy of the hardening done for chromium but it's more a detail rather than a major block

The post install could automate this kind of toolbx creation

**Comment by RoyalOughtness** [comment]
>  is not true ANY software unused is a surface attack because it can have security hole.

If the software is simply present on the disk but never run, then this is very theoretical. But again, you are asking for support for an unsupported use case. You are welcome to use bluebuild to make an image based on secureblue for your own use case.

> What do you think about a browser less image 

As I already said above: "anyone neglecting to protect themselves against the largest point of attack surface in their system never had security as their top priority to begin with. They are not the target audience of this project"

> I would give a way to have a browser less image

It is not in scope. You are welcome to use blue-build to use secureblue as a base image to make your own, per <https://github.com/secureblue/secureblue?tab=readme-ov-file#customization>. Several other users are already doing this.
