### ISSUE TITLE
Issue with nix installer via just/ujust

### ISSUE THREAD

**Issue by olmet** [secureblue/secureblue#251]
**Describe the bug**
You wrote here:
https://github.com/secureblue/secureblue/issues/9#issuecomment-1826166818

> The nix installer is already available in the justfiles. Type "just" in the terminal

When I enter "just" in the terminal appears:

```
/user$ just nix
error: Justfile does not contain recipe `nix`.

/user$ just
error: Justfile contains no default recipe.
```
Can anyone help, how can I install the nix installer?

**Your current image**
ostree-image-signed:docker://ghcr.io/secureblue/kinoite-nvidia-userns-hardened:latest
39.20240404.0 (2024-04-05T01:17:23Z)

**Comment by RoyalOughtness** [comment]
Try `ujust`

**Comment by mkkvcs** [comment]
If you are not in your default home directory, `just` looks for justfiles in the current one.

**Comment by olmet** [comment]
Thanks for your help, but I am in my default home directory. Many options are displayed via "ujust", e.g:

> Available commands:
>  - bios                           # Boot into this device's BIOS/UEFI screen
>  - changelogs                     # Show the changelog
>  - changelog                      # alias for `changelogs`
>  - check-local-overrides          # Check for local overrides
> .
> .
> .


And where can I find the option for the nix installer? I am a bit confused.

**Comment by RoyalOughtness** [comment]
Looks like upstream dropped the just command for this :thinking: 

I'm asking them why this was done and what the alternative is.

**Comment by RoyalOughtness** [comment]
@olmet 

The nix installer was dropped because it broke SELinux policies: https://github.com/ublue-os/config/pull/226

Given the nature of this project, we won't be adding the installer back. 

However, what package are you trying to install? You could use `brew` depending on the package.

**Comment by RoyalOughtness** [comment]
Closing as upstream removed it due to selinux breakage

**Comment by storopoli** [comment]
The determinate systems nix installer (https://github.com/DeterminateSystems/nix-installer)
works flawlessly in my ublue-nvidia desktop.

Can you try it, @olmet?

**Comment by RoyalOughtness** [comment]
@storopoli that's the same installer that was previously used in the ublue command, which was removed for breaking SELinux.

It should be discouraged especially if there's another way to install the same packages, like `brew`
