### ISSUE TITLE
[Question] Testing Fedora 40 With SecureBlue

### ISSUE THREAD

**Issue by czhang03** [secureblue/secureblue#252]
Is it possible to test Fedora 40 Beta with secure blue? I noticed there is a `br-f40-40` image: https://github.com/secureblue/secureblue/pkgs/container/silverblue-main-userns-hardened/200236139?tag=br-f40-40

Is this the image to try?

**Comment by RoyalOughtness** [comment]
Yes

**Comment by czhang03** [comment]
Hi, I was wondering why the naming is this unintuitive. I think on the upstream it is just called `40`: https://github.com/ublue-os/main/pkgs/container/silverblue-main/199137971?tag=40

**Comment by RoyalOughtness** [comment]
Upstream doesn't use bluebuild, secureblue does. Bluebuild doesn't support multi-versioned base images, so we use a branch tag.

**Comment by RoyalOughtness** [comment]
https://github.com/blue-build/cli/issues/140

**Comment by czhang03** [comment]
Thanks!
