### ISSUE TITLE
Hardened malloc miss a configuration (from the official doc)

### ISSUE THREAD

**Issue by ghost** [secureblue/secureblue#262]
Hello I seen in the official doc of the hardened malloc :

Make sure to raise vm.max_map_count substantially too to accommodate the very large number of guard pages created by hardened_malloc. As an example, in /etc/sysctl.d/hardened_malloc.conf:

vm.max_map_count = 1048576

But I do not see this change in secureblue, is it forgotten or on purpose (if on purpose don't hesitate to close this issue).

Source : https://github.com/GrapheneOS/hardened_malloc?tab=readme-ov-file#traditional-linux-based-operating-systems

**Comment by mkkvcs** [comment]
[It is already the default since Fedora 39](https://fedoraproject.org/wiki/Changes/IncreaseVmMaxMapCount)

**Comment by ghost** [comment]
> [It is already the default since Fedora 39](https://fedoraproject.org/wiki/Changes/IncreaseVmMaxMapCount)

oh ok my bad I close so thanks
