### ISSUE TITLE
Question - Server

### ISSUE THREAD

**Issue by ghost** [secureblue/secureblue#265]
Hello I have a question,
I know that the sever edition is based on coreOS with the auto upgrade disabled, to you happen to know if we must update like we do in silverblue (rpmostree upgrade ?)

Thanks for the answer !

**Comment by ghost** [comment]
For people who ask themselves the question rpm-ostree upgrade is the way to go :)

**Comment by RoyalOughtness** [comment]
The default is to stage, but if you want automatic reboots daily, just change it to `apply` in /etc/rpm-ostreed.conf

**Comment by RoyalOughtness** [comment]
https://www.mankier.com/5/rpm-ostreed.conf
