### ISSUE TITLE
[BUG] Issue with rtkit-daemon

### ISSUE THREAD

**Issue by ghost** [secureblue/secureblue#266]
**Describe the bug**
When I rebase on server version 2 packages fail to load, the first one is user based (witch is not an issue since user is already created and the error disappear after a reboot)
The second one is rtkit-daemon that resist to reboot and only disappear if the service is disabled

**Expected behavior**
If the package is not used have it disabled by default, if it's used find why it fail to start

**Actual behavior**
have it logged as failed unit started in terminal.

**Your current image**
* ostree-image-signed:docker://ghcr.io/secureblue/server-main-userns-hardened:latest
                   Digest: sha256:2266b162f42e24e784d6c16d018ec255177dd8bb3c48a9b82b2db81cc3a5fa1e
                  Version: 39.20240407.3.0

**For all images**
- Confirm you cannot repro on a uBlue base image

I had the user one (who disappear on reboot) but not the rtkit-daemon one on ublue

**Comment by RoyalOughtness** [comment]
Strange. What logs do you see in journalctl for rtkit-daemon?

**Comment by ghost** [comment]
the error is : 
Apr 28 22:23:36 localhost.localdomain systemd[1]: Starting rtkit-daemon.service - RealtimeKit Scheduling Policy Service...
Apr 28 22:23:36 localhost.localdomain systemd[1]: Started rtkit-daemon.service - RealtimeKit Scheduling Policy Service.
Apr 28 22:23:36 localhost.localdomain rtkit-daemon[1285]: Failed to find user 'rtkit'.
Apr 28 22:23:36 localhost.localdomain systemd[1]: rtkit-daemon.service: Deactivated successfully.

**Comment by RoyalOughtness** [comment]
Is this the user based error or the other one?

**Comment by ghost** [comment]
it's the output of : sudo systemctl status rtkit-daemon

**Comment by RoyalOughtness** [comment]
It would appear it's still missing the user then

**Comment by ghost** [comment]
> It would appear it's still missing the user then

I guess for the server it can be securely disabled because of : 

rpm -q --whatrequires rtkit
pipewire-1.0.5-1.fc39.x86_64

Since server rarely use sound but I may have missed something.

**Comment by RoyalOughtness** [comment]
What is pulling in pipewire? do you have anything layered?

Can you post `rpm-ostree status`?

**Comment by ghost** [comment]
birdinfire@localhost:~$ rpm-ostree status
State: idle
AutomaticUpdates: apply; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
* ostree-image-signed:docker://ghcr.io/secureblue/server-main-userns-hardened:latest
                   Digest: sha256:2266b162f42e24e784d6c16d018ec255177dd8bb3c48a9b82b2db81cc3a5fa1e
                  Version: 39.20240407.3.0 (2024-04-28T18:38:28Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/ucore-minimal:stable
                   Digest: sha256:f946596042c3c71f16dbfd2c2a507e28ff400c1393ee7b23bbbdd28c46c6c3cb
                  Version: 39.20240407.3.0 (2024-04-27T23:45:34Z)

**Comment by ghost** [comment]
but I can say that disabling it cause no : immediately visible issue.

**Comment by RoyalOughtness** [comment]
Thanks, I will look into this

**Comment by ghost** [comment]
> Thanks, I will look into this

No problem reported it since I guess it's not a very used image if you need any test or command don't hesitate (only the time I see the post).

**Comment by RoyalOughtness** [comment]
@BirdInFire It's a used image, but I think this hasn't been uncovered until now and I still need to triage it properly.

**Comment by RoyalOughtness** [comment]
@BirdInFire what do you have in `/etc/passwd` and `/usr/etc/passwd`?  I haven't been able to reproduce this

**Comment by ghost** [comment]
> @BirdInFire what do you have in `/etc/passwd` and `/usr/etc/passwd`? I haven't been able to reproduce this

I come back home Thursday I will give you the content of those file (hash removed of course (secureblue is on my lab server witch I cannot access remotely (since it's used to test my next settings before deploying it on my network)).

I could also reinstall fedora silverblue and rebase again (it could be a bug from silverblue now fixed).

Edit : disclaimer as "bug from silverblue" I mean a config file who where in silverblue that generate the bug after the rebase (since this bug did not appear on silverblue beforehand nor ublue images)

**Comment by RoyalOughtness** [comment]
@BirdInFire what did you find?

**Comment by ghost** [comment]
/etc/passwd
```
root:x:0:0:root:/root:/bin/bash
birdinfire:x:1000:1000:birdinfire:/var/home/birdinfire:/bin/bash
setroubleshoot:x:978:978:SELinux troubleshoot server:/var/lib/setroubleshoot:/usr/sbin/nologin
```
/usr/etc/passwd
```
root:x:0:0:Super User:/root:/bin/bash
setroubleshoot:x:992:978:SELinux troubleshoot server:/var/lib/setroubleshoot:/usr/sbin/nologin
usbmuxd:x:113:113:usbmuxd user:/:/sbin/nologin
unbound:x:985:977:Unbound DNS resolver:/var/lib/unbound:/sbin/nologin
rtkit:x:172:172:RealtimeKit:/:/sbin/nologin
geoclue:x:984:976:User for geoclue:/var/lib/geoclue:/sbin/nologin
pipewire:x:983:975:PipeWire System Daemon:/run/pipewire:/usr/sbin/nologin
```

**Comment by RoyalOughtness** [comment]
@BirdInFire 

copy this line to `/etc/passwd`:

```
rtkit:x:172:172:RealtimeKit:/:/sbin/nologin
```

should fix the issue
