### ISSUE TITLE
Secure DNS presets

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#27]
dnscrypt would be good to be preset.

I am not sure how this overlaps / replaces the need of a hardened systemd-resolved config here.

Keep in mind that DNSSec and custom DNS in general break Captive portals, which are shitty, but needed in pretty much every public wifi. Some method of swapping configs or even something in networkmanager may be a solution, but I haven't found that yet

https://discussion.fedoraproject.org/t/turn-on-of-systemd-resolved-override-conf-files-different-security-levels/

Some ideas by a kind AI:

```
#!/bin/bash

# Function to create Network Profile
create_network_profile() {
    sudo nmcli connection add type ethernet con-name $1 ifname $2
    sudo nmcli connection modify $1 ipv4.method auto
    sudo nmcli connection modify $1 ipv6.method auto
}

# Function to configure DNS settings for InsecureProfile
configure_insecure_profile() {
    sudo nmcli connection modify InsecureProfile ipv4.dns-priority -42
    sudo nmcli connection modify InsecureProfile ipv6.dns-priority -42
    sudo nmcli connection modify InsecureProfile ipv4.dns-search ''
    sudo nmcli connection modify InsecureProfile ipv6.dns-search ''
}

# Function to configure DNS settings for SecureProfile
configure_secure_profile() {
    sudo nmcli connection modify SecureProfile ipv4.dns '8.8.8.8,8.8.4.4'
    sudo nmcli connection modify SecureProfile ipv6.dns '2001:4860:4860::8888,2001:4860:4860::8844'
    sudo nmcli connection modify SecureProfile ipv4.dns-search $1
    sudo nmcli connection modify SecureProfile ipv6.dns-search $1
}

# Function to activate a Network Profile
activate_profile() {
    sudo nmcli connection up $1
}

# Function to configure systemd-resolved for DNSSec and DOT
configure_systemd_resolved() {
    sudo sed -i 's/#DNSSEC=no/DNSSEC=yes/' /etc/systemd/resolved.conf
    sudo sed -i 's/#DNSOverTLS=no/DNSOverTLS=yes/' /etc/systemd/resolved.conf
}

# Main Script

# Replace with actual interface name and search domain
interface_name="<your_interface_name>"
search_domain="<your_search_domain>"

# Create Network Profiles
create_network_profile InsecureProfile $interface_name
create_network_profile SecureProfile $interface_name

# Configure DNS settings
configure_insecure_profile
configure_secure_profile $search_domain

# Activate Profiles based on security requirements
activate_profile InsecureProfile
# activate_profile SecureProfile

# Configure systemd-resolved
configure_systemd_resolved

# Restart services
sudo systemctl restart NetworkManager
sudo systemctl restart systemd-resolved
```

https://www.privacy-handbuch.de/handbuch_93d.htm
https://unix.stackexchange.com/questions/444659/how-to-let-resolveconf-update-dns-configuration-when-using-networkmanager

a GUI way woud be easy by creating custom .desktop entries for enabling and disabling. Something more elegant like an app would also be nice, but this should be implemented in the Desktops anyways. I just dont really see Gnome doing that, as its pretty technical, KDE could be imaginable.

It would already be enough to launch a browser instance with "insecure DNS mode". After logging into the captive portal you can use any DNS you want.

**Comment by RoyalOughtness** [comment]
This is a privacy feature and not a security feature and is therefore not in scope for this project.
