### ISSUE TITLE
[Feat] Configure Network manager to ignore DHCP option 121

### ISSUE THREAD

**Issue by ghost** [secureblue/secureblue#270]
A new finding show that DHCP option 121 can be abused by a rogue DHCP to snoop on vpn connexion.
As such I propose to explicitly set Network manager to ignore any route pushed by the DHCP (option 121)

Disclosure I'm not sure it's actually possible so if not just close this issue

source : https://krebsonsecurity.com/2024/05/why-your-vpn-may-not-be-as-secure-as-it-claims/

**Comment by RoyalOughtness** [comment]
I'm reading up on this, thanks for the heads up

**Comment by RoyalOughtness** [comment]
I think there's probably a way to accomplish this, however I'm reluctant to jump in with a config change. The nature of this is such that it's more of a technique utilizing correct behavior of an existing protocol than a vulnerability per se. As such, adding a "quick fix" isn't really appropriate here since there isn't really an urgent need. Instead, it's better to wait and see what if any industry response there is to this and then revisit this question. I'll leave this issue open though.

**Comment by ghost** [comment]
> I think there's probably a way to accomplish this, however I'm reluctant to jump in with a config change. The nature of this is such that it's more of a technique utilizing correct behavior of an existing protocol than a vulnerability per se. As such, adding a "quick fix" isn't really appropriate here since there isn't really an urgent need. Instead, it's better to wait and see what if any industry response there is to this and then revisit this question. I'll leave this issue open though.

I agree, as every change proposed I did not ask for immediate change, but simply add it to a list in case where (like many other vulnerability of this kind) it's ignored as "normal feature issue" (since the bad actor must control dhcp to successfully use this vulnerability).

Edit : but nothing prevent (later on) to add this kind of settings into the same category of the unsafe kernel change) an optional settings user must opt-in.

**Comment by pm4rcin** [comment]
Here's the [statement from Mullvad](https://mullvad.net/en/blog/evaluating-the-impact-of-tunnelvision). From my perspective it looks like any **sane** VPN provider should not be vulnerable.

**Comment by ghost** [comment]
> Here's the [statement from Mullvad](https://mullvad.net/en/blog/evaluating-the-impact-of-tunnelvision). From my perspective it looks like any **sane** VPN provider should not be vulnerable.

Depend as some OS for security purpose reduce the visibility of what can or cannot be done (iOS) so the problem remain in place for majority of people.

it's why I personally have moved to a network solution placed between 2 other network and a very strict isolation of my network and an advanced control of what can connect and what cannot.

for the phone I always use 4G/5G, and I carry another network's one for my tablet / computer, so technically it do not affect me at all.

But again majority of people who rely on cheap solution of their ISP on cheap vpn will be massively vulnerable.

**Comment by RoyalOughtness** [comment]
Closing this as unfortunately I haven't come across actionable steps we can take to mitigate this. If there are any, please reopen this with that info.
