### ISSUE TITLE
Can't rebase to unsigned image with Secure Boot enabled

### ISSUE THREAD

**Issue by ghost** [secureblue/secureblue#271]
**Describe the bug**
Following the pre-install and installation instructions I made sure Secure Boot was enabled before installing Fedora Silverblue and then rebasing to the unsigned image (in this case, silverblue-asus-userns-hardened). Upon rebooting I was greeted with a GRUB error: "Bad shim signature. You need to load the kernel first." Apparently this is due to Secure Boot being enabled.

**To Reproduce**
Steps to reproduce the behavior: Follow the instructions.

**Expected behavior**
Per pre-installation instructions, you should have Secure Boot enabled. Per installation instructions, you are supposed to be able to boot into the unsigned image after rebasing from Silverblue. Then you should rebase again to the signed image.

**Actual behavior**
I was unable to get the unsigned image to boot due to Secure Boot being enabled as recommended in the pre-install instructions. GRUB refuses to boot into the Secureblue unsigned image due to "bad shim signature."

**Your current image**
```
Deployments:
  ostree-unverified-registry:ghcr.io/secureblue/silverblue-asus-userns-hardened:latest
    Digest: sha256:c8a442f2d17c7667af47a2200f2ce24c0268305373e9ba00b9b09fcd390d087
    Version: 40.20240506.0 (2024-05-06T18:21:48Z)
       Diff: 5 upgraded, 16, downgraded, 31 removed, 234 added

· fedora:fedora/40/x86_64/silverblue
    Version: 40.20240507.0 (2024-05-07T00:47:06Z)
       Commit: 808c47f7b3eba1d4d70345835c076cd8fe0cba4d76d5741cf6376a3278542483
     GPGSignature: Valid signature by 115DF9AEF857853EE8445D0A0727707EA15B79CC
```

**Comment by RoyalOughtness** [comment]
Does this happen for non-asus images as well?

**Comment by ghost** [comment]
Actually no! At your suggestion I rebased to silverblue-userns-hardened and it boots just fine.

I do wonder what the issue is with the Asus image, but since all I really need is one extra package (asusctl) maybe a good solution is to stick with the non-asus image and just layer that one package. (I selected the Asus image because I'm running it on an Asus laptop and need to control the fan, backlight etc.)

Thanks!

**Comment by RoyalOughtness** [comment]
Check this comment, it may be the same issue: https://github.com/secureblue/secureblue/issues/255#issuecomment-2080383832

**Comment by RoyalOughtness** [comment]
@OpGWjzFVI reopen this if it's not the same issue
