### ISSUE TITLE
[BUG] generate_secureblue_iso.sh makes no ISO

### ISSUE THREAD

**Issue by Tracker3223** [secureblue/secureblue#273]
**Describe the bug**
After using the generate_secureblue_iso.sh script, I can't find the ISO.

**To Reproduce**
1. Open Ptyxis
2.  run the ./generate_secureblue_iso.sh
3. See it doesn't make the ISO

**Expected behavior**
Script makes the actual ISO Image

**Actual behavior**
It doesn't make the ISO File, or I could not find it.

**Your current image**
 - `State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 14min ago
Deployments:
● ostree-image-signed:docker://ghcr.io/secureblue/bluefin-nvidia-userns-hardened:latest
                   Digest: sha256:fd1a4d598193cc3cc5cc460ea377cf6c57589ff5f44f6adb98c14d1e9701ba7f
                  Version: 40.20240508.0 (2024-05-08T21:41:44Z)`

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/a91172be17b65413bb42870bd608397d2a33fdba
