### ISSUE TITLE
Improved gaming experience

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#284]
Today, gaming is a clunky experience on secureblue. 

The recommended method is to use steam from flathub, which isn't verified so it isn't available by default.

Even with flatpak steam, there are issues loading numerous games.

This issue tracks the information gathering and solution proposals for an improved gaming experience, and potentially a bazzite variant.

**Comment by TommyTran732** [comment]
I don't know if this is worth the time investment. 
- With games, it usually goes straight to the point where there is no security to be had. You want to run mods, you trust random third party software running directly on the host. Does Steam even do any sandboxing with bubblewrap on its own or does it just use it to spin up a Proton environment to run stuff? 
- Security hardening often takes away performance. An example would be the CPU vulnerability mitigations. Are you going to disable stuff like SMT for security, or are you gonna keep the Fedora defaults? You can even improve performance by disabling mitigations too... And if there is no security to be had, why not just disable the mitigations? How are you going to handle this?

**Comment by RoyalOughtness** [comment]
> I don't know if this is worth the time investment.

We already have it working

> You want to run mods, you trust random third party software running directly on the host. 

Not everyone running games is modding..?

> Does Steam even do any sandboxing 

Yes, it uses pressure-vessel: https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/tree/main/pressure-vessel

"to run games in individual game-specific containers."

> Are you going to disable stuff like SMT for security

Yes, that stays the same

**Comment by throwaway43** [comment]
I would personally be in favor of a Bazzite variant.

> The recommended method is to use steam from flathub, which isn't verified so it isn't available by default.
>
> Even with flatpak steam, there are issues loading numerous games.

As for interesting projects/software that are perhaps worth mentioning here for tackling the situation around Steam (in alphabetical order):
- **[Bazzite-Arch](https://github.com/ublue-os/bazzite-arch)**;
    - Steam is included with the image. And can be invoked (within the image) with `steam`.
    - Can only be used on the images with User Namespaces.
    - Works.
    - Container workflow isn't appreciated by everyone.
    - IIRC, Bazzite actually doesn't actively rely on this anymore. As such, I wonder how much it's getting improved and how healthy this project is.
- **[Bottles](https://usebottles.com/)**;
    - Flatpak.
    - Doesn't come with Steam pre-installed. Though, they've put some effort to streamline the process.
    - Unfortunately, for some reason, I wasn't able to open Steam with this using their streamlined approach. Though, it might be an issue on my end.
    - Team behind it is currently working on multiple projects and even on another related project [Bottles Next](https://usebottles.com/blog/bottles-next-a-new-chapter/). Therefore, the project isn't as healthy as it was a year or two ago.
- **[Conty](https://github.com/Kron4ek/Conty)**;
    - Includes Steam out of the box. Can either be opened through Conty's binary (i.e. `./conty.sh steam`) or through Steam's exported .desktop file after invoking the `./conty.sh -d` command; this command exports all .desktop files inside Conty's `/usr/share/applications` to user's `$XDG_DATA_HOME/applications/Conty` folder.
    - Works (with some effort) on all images.
    - Already uses bubblewrap and comes with built-in options for sandboxing.
    - So far, my experiences with updating were cumbersome. But this might be on my end.
    - Looks like a well-maintained project.
    - [*"This repository has GitHub workflows that allows you to make GitHub automatically generate a new Conty binary of your specification, every week or at any time you want."*](https://github.com/Kron4ek/Conty?tab=readme-ov-file#automated-github-actions); I'm sure this will be useful.
- **[RPM-fusion's Steam](https://github.com/rpmfusion/steam)**:
    - I couldn't find a lot on this in combination with Fedora Atomic. I guess it should work, but don't quote me on this.

I'm by no means an expert, but Conty seems most promising to me.

Just my two cents.

**Comment by RoyalOughtness** [comment]
@throwaway43 There's no situation to tackle around steam, it works well out of the box. Also, secureblue will not be inventing a new gaming variant, so anything related to that is offtopic and out of scope. The purpose of this project is to harden existing uBlue/Fedora Atomic images.

> I couldn't find a lot on this in combination with Fedora Atomic.

This is what bazzite uses.

**Comment by TommyTran732** [comment]
One note is that you really should be enabling SquashFS by default with the Bazzite variant - they ship a lot of AppImages ootb.

**Comment by RoyalOughtness** [comment]
@TommyTran732 done https://github.com/secureblue/secureblue/commit/442eaae49652d35ada4550f71a015ca567932fd7

**Comment by RoyalOughtness** [comment]
Abandoning the bazzite variants in staging. Users are instructed to use the flatpak or layer the steam rpm.

https://github.com/secureblue/secureblue/commit/9f92777c95174d7a316569d53e0184cb1b1fb4a3
https://github.com/secureblue/secureblue/commit/6180c4f4c8bfc1172fb9090c8c19174e8919debf
