### ISSUE TITLE
[FEAT] Enable USB-Guard and Configure it for Workstation Usage

### ISSUE THREAD

**Issue by monsieuremre** [secureblue/secureblue#295]
Question: Why not already? Is there a specific reason? Is this out of the scope of this project?

Anyway, just depend on it and create a very generic configuration to block bad-usb and suspicious combos. I can create a pull if you are open. Else just close the issue.

**Comment by RoyalOughtness** [comment]
Because the upstream package is broken.

Upstream recently responded: https://bugzilla.redhat.com/show_bug.cgi?id=2259249

It needs to be investigated further.

**Comment by monsieuremre** [comment]
Didn't have a detailed look, but it looks like the issue can be solved by disabling audit logging for USB Guard. Otherwise the file path can be changed in the usbguard configuration file too for the logs. I also suspect just creating an empty file with the right ownership might also solve the issue.

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/99ff4757ec10d24619eb652fc90286474cbffabf
