### ISSUE TITLE
Remove suid from binaries where possible

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#298]

**Comment by RoyalOughtness** [comment]
some candidates

```
/usr/bin/chage
/usr/bin/chfn
/usr/bin/chsh
/usr/bin/fusermount
/usr/bin/fusermount3
/usr/bin/gpasswd
/usr/bin/mount
/usr/bin/newgrp
/usr/bin/nvidia-modprobe
/usr/bin/umount
```

**Comment by TommyTran732** [comment]
`/usr/bin/passwd` writes to `/etc/shadow` so I do not see how it can work without SUID.

`/usr/bin/pkexec` is polkit so you really need to be careful with this. Need to double check if can work without SUID like run0 or not.

**Comment by RoyalOughtness** [comment]
@TommyTran732 yep, those shouldn't have been listed as candidates

same with nvidia-modprobe


here's what I'm starting with: https://github.com/secureblue/secureblue/blob/staging/config/scripts/removesuid.sh

**Comment by TommyTran732** [comment]
Reads like badness enumeration. I don't know if that's the best approach. Personally, I would:
- Make a list of things that absolutely needs SUID and is used by most people.
- find / -type f -perm 4000 > foo.txt
- If a binary is in the whitelist, remove from foo.txt
- chmod u-s everything else in there

**Comment by RoyalOughtness** [comment]
@TommyTran732 Agreed, the script in staging is just for testing. The logic will need to be reversed.
