### ISSUE TITLE
Restore full jitless behavior

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#304]
https://github.com/GrapheneOS/Vanadium/blob/main/patches/0170-Revert-M122-content-make-disable-jit-actually-disabl.patch

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/a25075faccacde0c7ba4698b4637a1b137d5f296

**Comment by RKNF404** [comment]
Didn't want to make a new issue but this isn't fully solved. The way the DefaultJavaScriptJitSetting or V8 JS Optimizations toggle seem to work is they keep Web Assembly enabled when the optimizations are disabled, even if --jitless is passed. It only properly enforces JITless mode when DefaultJavaScriptJitSetting is set to 1 (or enabled) to allow the flag to be passed. See for yourself: https://webassembly.org/features/

**Comment by RoyalOughtness** [comment]
@RKNF404 Thanks for bringing this up. Can you clarify what I'm supposed to be looking for on that site?

**Comment by RoyalOughtness** [comment]
related https://github.com/secureblue/secureblue/issues/309

**Comment by RKNF404** [comment]
@qoijjj The website is a feature test for web assembly, specifically the Your Browser section of the table. If JIT is fully disabled (wasm included), then that side should be red X's and question marks only. Anything else (green checkmarks) indicates wasm is still enabled. Testing DefaultJavaScriptJitSetting with 2 (JIT disabled) keeps wasm enabled, and allows wasm to be disabled when set to 1 (JIT enabled) when passing in --jitless.

**Comment by RKNF404** [comment]
Don't know how much it will help but I'll post it separately. I ran into the issue and just opt to keep the policy [enabled](https://codeberg.org/Rootkit404/chromium-harden/src/commit/3c23111fb623e2b21abfde6be8523c81466f94e9/conf/chromium-harden-policy.json#L22), adding for clarity and context. But, with #309 the linked Vanadium patch will also fix it.

**Comment by RoyalOughtness** [comment]
@RKNF404 Yikes, this is an unfortunate design. So you're saying that the Vanadium patch (which just [passes --jitless to the renderer](https://github.com/GrapheneOS/Vanadium/blob/main/patches/0170-Revert-M122-content-make-disable-jit-actually-disabl.patch)) doesn't suffer from this problem for some reason? Do you know why this is? Why would --jitless have no effect on WASM when passed to the browser, but have an effect when passed to the renderer?

**Comment by RKNF404** [comment]
@qoijjj I had the exact same question, I thought they changed how --jitless worked, since on Windows it enables extra mitigations like ACG but when I checked it wasn't enabled. My basic understanding is when disabling JIT the proper way (policy or setting), it passes specific flags directly to the renderer and ignores the flag provided to the browser. Currently, chromium will pass "--no-maglev,--no-turbofan" to the renderer which just disables JS JIT, not wasm. It will pass --jitless but only to PDF renderers it seems, since it calls IsPdf(). The Vanadium patch overrides that behavior to always pass --jitless, regardless of renderer type or browser flags (I assume).

**Comment by RKNF404** [comment]
My speculation is, they intend to add a WASM interpreter (soon?) similar to Edge to allow JITless WASM. But that is a hunch.

**Comment by RoyalOughtness** [comment]
@RKNF404 this is fixed now, thanks for bringing it up

This is really a temporary fix though, we need https://github.com/secureblue/secureblue/issues/309

**Comment by RKNF404** [comment]
Happy to help, thank you for your work.
