### ISSUE TITLE
[feat] build chromium with vanadium patches

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#309]
Increasingly, new hardening changes are needed in the form of code changes and can't be sufficiently replicated with config or policy changes.

**Comment by TommyTran732** [comment]
Maybe you can kang some old ones from Hexavalent

https://github.com/Hexavalent-Browser/Hexavalent-Archive

**Comment by RoyalOughtness** [comment]
@TommyTran732 those are largely just a subset of the vanadium ones I believe.

The time consuming part here is the CICD. Pulling in patches is the easy part :smile:

**Comment by RoyalOughtness** [comment]
I'm working on it here https://github.com/qoijjj/chromium-copr-experimental

**Comment by TommyTran732** [comment]
Oh yeah, speaking of which, is there a reason why you don't bring these to the secureblue's namespace?

I mean, you have the builds under secureblue on copr, but the source is on your personal

**Comment by RoyalOughtness** [comment]
@TommyTran732 what? That is incorrect. All of the rpm specs currently shipped in secureblue are in the secureblue organization https://github.com/orgs/secureblue/repositories

I'm currently playing around with this in a sandbox repo in my personal github and copr accounts, which seems appropriate given the current stage of development. Why would I move it to the secureblue org now before it's ready?

**Comment by TommyTran732** [comment]
Okay fair.

Hardened Malloc is still inside of your personal account through and not the org, at least according to this: https://copr.fedorainfracloud.org/coprs/secureblue/hardened_malloc/build/7573649/

**Comment by TommyTran732** [comment]
Edit: 

Looks like you moved it recently but might be a good idea to update the copr to it stops referencing the old URL as well.

**Comment by RoyalOughtness** [comment]
@TommyTran732 ah you're right, that hasn't been updated since the repo moved to the secureblue org. i'll do it now

**Comment by TommyTran732** [comment]
Might be a good idea to have to have a look at this as well: https://simonwillison.net/2024/Jul/9/hangout_servicesthunkjs/
I just noticed its also in Edge's build for macOS and Linux... very jackwagon

**Comment by RoyalOughtness** [comment]
@TommyTran732 for specific chromium hardening improvements, please open a new issue. this issue is just for tracking the effort to move to a custom build

Also, that's probably relevant to vanadium as well. Might be worth asking them.

**Comment by TommyTran732** [comment]
Already did privately. Will lyk.

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/hardened-chromium
