### ISSUE TITLE
add back COPR command

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#31]
[I wrote my own solution in bash](https://github.com/trytomakeyouprivate/COPR-command), it uses polkit so only necessary commands need elevated privileges.

[34N0 has their own one in Go](https://github.com/34N0/rpm-copr)

I guess we have to fight, they do basically the same

**Comment by RoyalOughtness** [comment]
> [I wrote my own solution in bash](https://github.com/trytomakeyouprivate/COPR-command), it uses polkit so only necessary commands need elevated privileges.
> 
> [34N0 has their own one in Go](https://github.com/34N0/rpm-copr)
> 
> I guess we have to fight, they do basically the same

Regardless, this is an upstream issue. Please file an issue at https://github.com/ublue-os/main

**Comment by boredsquirrel** [comment]
https://github.com/ublue-os/main/issues/435

Ok lol that was a ride. I reported the lack of a copr command on the Silverblue tracker, they referred me to the coreos rpm-ostree tracker, they referred to some random issue and closed it, and also referred back to the silverblue tracker.

Gave them a heads up that there is no open issue about this trivial feature anymore ;D
