### ISSUE TITLE
Enable SELinux Confined Users

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#32]
This will not work yet probably. But when the DEs are fixed, it should.

https://fedoraproject.org/wiki/SELinux/ConfinedUsers

https://discussion.fedoraproject.org/t/security-enthusiasts-wanted-from-beginners-up-to-selinux-experts-to-make-up-the-selinux-confined-users-sig-to-foster-fedoras-security-capabilities/89127

**Comment by RoyalOughtness** [comment]
Closing this as it belongs upstream and is being worked on upstream.

**Comment by boredsquirrel** [comment]
https://fedoraproject.org/wiki/SIGs/ConfinedUsers
