### ISSUE TITLE
warn that these images are using unsigned Fedora images

### ISSUE THREAD

**Issue by secretmango** [secureblue/secureblue#327]
https://quay.io/organization/fedora-ostree-desktops/

These images are the base for uBlues images, which then is the base for secureblue.

This means
1. Secureblue lacks behind on updates a certain time. This maybe can be improved by reducing the times when each image consumes the upstream. The lag may be about 1 or 2 days, but I dont know if this is known and dealt with.
2. Secureblue is signed, and uses signed uBlue images, but the base Fedora images are not signed. This will likely change when bootc and the images are default. But until then, I think a warning would be appropriate

Have a nice day!

**Comment by RoyalOughtness** [comment]
1. we consume upstream within an hour of release, which you can confirm by checking the build.yml of this project vs ublue
2. This is an upstream issue, please create it here: https://gitlab.com/fedora/ostree/ci-test/-/issues
