### ISSUE TITLE
[FEAT] remove "randomize MAC addresses" as it is default in Fedora

### ISSUE THREAD

**Issue by secretmango** [secureblue/secureblue#328]
**Describe the benefit this feature would provide to the project**
Reduce deduplication, show the contact with upstream.

**Describe the solution you'd like**
Remove the mentioning of it, maybe have a list of hardening that was done upstream. Also note that the MAC randomization was not initiated by secureblue, the Fedora Project did this on their own.

**Declaration**
- [x] I declare that I have read the README and my feature request is in-scope.

**Comment by RoyalOughtness** [comment]
Makes sense, can you link to the upstream change? Then I'll remove it

**Comment by secretmango** [comment]
[Change](https://fedoraproject.org/wiki/Changes/StableSSIDMACAddress)

[Discussion](https://discussion.fedoraproject.org/t/f40-change-proposal-wifi-mac-randomization-system-wide/99856/40)

**Comment by RoyalOughtness** [comment]
Their changes only apply to wifi https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/merge_requests/1789/diffs

**Comment by secretmango** [comment]
okay this is pretty strange. Covers most cases, and probably harm reduction for MAC-based authentication systems on Ethernet.

**Comment by RoyalOughtness** [comment]
I'm not sure what you mean. In any case the changes they make are somewhat different anyways. They're using stable-ssid instead of stable. Please reopen this if something changes.

**Comment by secretmango** [comment]
stable-ssid and stable sound like aliases? I made a PR mentioning the restriction on Wifi in Fedoras implementation

**Comment by RoyalOughtness** [comment]
They're not aliases. One uses connectionid, one uses ssid
