### ISSUE TITLE
[FEAT] Investigate on a VPN/Proxy killswitch mechanism

### ISSUE THREAD

**Issue by secretmango** [secureblue/secureblue#329]
**Describe the benefit this feature would provide to the project**
A killswitch for VPNs is implemented on Android natively. This allows to block all connections if they are not done throug the VPN. (system apps are excluded).

This does not exist on Desktop Linux/Fedora, and requires a little scripting. MullvadVPN has implemented [a systemd service for early-boot-blocking](https://github.com/mullvad/mullvadvpn-app/blob/main/dist-assets/linux/mullvad-early-boot-blocking.service), and it seems to be pretty airtight. But using their app extends the attack surface (and the app uses Electron).

The implementation seems to be part of [mullvad-daemon](https://github.com/mullvad/mullvadvpn-app/tree/main/mullvad-daemon).

The benefit is for all people that need an airtight system. It may interfere with things like Captive Portal logins though.

**Describe the solution you'd like**
Implement a killswitch solution which only allows access to a configured proxy/VPN, and blocks everything else. After an established connection, the traffic would go through the VPN anyways. Not sure how this would be handled with a proxy.

[Carburetor](https://framagit.org/tractor/carburetor) can be used in combination, serving a locally accessible tor proxy, sandboxed with bubblewrap.

This sounds like a combination between systemd-resolved (DNS) and NetworkManager (networking). Maybe firewalld for extra security.

**Describe alternatives you've considered**
Use a third party app from an external repository that is tied to a specific VPN service.

**Declaration**
- [x] I declare that I have read the README and my feature request is in-scope.

**Comment by RoyalOughtness** [comment]
I don't see how this is in scope.

Also, given that some vpn providers are already implementing this, it would be reinventing the wheel.

**Comment by secretmango** [comment]
I respect if you think this is not in scope. But the implementation by mullvad is likely intensely tied to their own services, and thus not really a good alternative.

The security impact of a VPN is arguable, when using only encrypted traffic I propably agree with you.

**Comment by RoyalOughtness** [comment]
protonvpn also has a killswitch in their linux client now. if you don't use either, you should reach out to your provider

the reality is that even if this was in scope, vpn providers are already solving this problem and will solve it sooner than secureblue will

**Comment by TommyTran732** [comment]
> protonvpn also has a killswitch in their linux client now

It leaks. It's been leaking for years.

**Comment by RoyalOughtness** [comment]
@TommyTran732 yikes. good to know. not much of a killswitch then.

do you have a link to that issue? I'm curious

**Comment by secretmango** [comment]
poorly neither of them is upstreaming their tools to the appropriate builtin tools... but I will have a look, the MullvadVPN app is really good. This doesnt even currently affect me, but fixing this for all would make me happy.

**Comment by TommyTran732** [comment]
https://privsec.dev/posts/linux/protonvpn-ip-leakage-on-linux-and-workaround/

They told me in the email that they would fix it with their new VPN app. The new VPN app came out, and someone tested it again and it still leaks. `ip info` is on their dns block list so turn that off if you wanna test.

Their are plenty posts on Reddit saying "I use ProtonVPN on Linux and I got DMCAed!!!". This is probably the reason why.
