### ISSUE TITLE
[DOCS] Document that DNSSEC breaks DNS on new installs in a VM

### ISSUE THREAD

**Issue by secretmango** [secureblue/secureblue#331]
I tested it by commenting out a single line.

At least when giving a fixed IP, DOT is not an issue, but for some reason even opportunistic DNSSEC breaks connection.

This may be related to how libvirt handles the network.

Reproduce:
- setup a VM with normal Fedora ISO
- rebase to secureblue unsigned
- try to rebase to signed
- no DNS, `ping 1.1.1.1` works

Workaround:
- set a fixed DNS server in the `/etc/systemd/resolved.conf.d/securedns.conf` like `DNS=9.9.9.9`
- comment out `DNSSEC=opportunistic`

This should be documented. There were 2 issues about this problem.

- [issue 1](https://github.com/secureblue/secureblue/issues/228)
- [issue 2](https://github.com/secureblue/secureblue/issues/240)

@qoijjj locked one after I gave the solution for the issue, where the workaround was simply disabling everything (while DOT is not the issue).

I find this behavior not helpful, as well as closing existing issues that only have a workaround, even more if that workaround is insecure, like disabling DOT.

Locking issues to "contributors only" that quickly very much harms the contribution culture and does not match with what is written in the Code of Conduct.

**Comment by RoyalOughtness** [comment]
Yes, this should be added to the FAQ. PRs welcome.

**Comment by RoyalOughtness** [comment]
@firefoxlover Issues can only be locked that way unfortunately, if I could have locked it completely I would. Issues are closed when they are not actionable anymore, either via resolution or determining that it's an upstream issue. Opening a new issue like you did here to request docs is the right approach.

That said, please read these:

- https://world.hey.com/dhh/open-source-is-neither-a-community-nor-a-democracy-606abdab
- https://gist.github.com/richhickey/1563cddea1002958f96e7ba9519972d9

Entitled attitudes are not welcome here, including entitlement to dictate how the project issues page is managed. Consider this a formal warning.

**Comment by secretmango** [comment]
I understand that one can only "dictate" for oneself. But I dont think asking for something is "dictating". This is totally up to you of course, I just never saw this on any project where I contributed.

Also, here my point was that both issues were not resolved. It was a workaround, and an insecure one. DNSSEC seems to be broken, as quad9 supports it.

https://quad9.com/service/service-addresses-and-features/

This is really strange, I will try to find the cause and make a PR on the postinstall readme.

**Comment by RoyalOughtness** [comment]
@firefoxlover thanks yeah and if the cause is upstream, please create an issue upstream as well

**Comment by RoyalOughtness** [comment]
the root cause if I remember right is that the resolved behavior had issues, and so an issue will probably need to be created to resolved. But an FAQ item until that gets done is a good idea

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/7132b12816c673e700c69d0dec39a811831b4ae6
