### ISSUE TITLE
[DOCS] SELinux confined users 

### ISSUE THREAD

**Issue by secretmango** [secureblue/secureblue#338]
**Describe the benefit this feature would provide to the project**
SELinux confined users are a very important step towards securing the desktop applications and access to the user directory, including ssh keys, etc. 

There are different levels of confinement, where `sysadm_u` can do the most, `staff_u` and `user_u` have less privileges. The latter 2 dont even have access to piping in scripts, which could be problematic for a lot of used scripts in the OS.

**Describe the solution you'd like**
I will try to test a separate user with `sysadm_u` in the coming weeks.

**Describe alternatives you've considered**
Minimizing the system, using different isolation methods like Flatpak and Containers.

**Declaration**
- [x] I declare that I have read the README and my feature request is in-scope.

**Comment by RoyalOughtness** [comment]
dup of https://github.com/secureblue/secureblue/issues/32

**Comment by RoyalOughtness** [comment]
this isn't something we can build into images. it's either something we wait for fedora to add to the installer, or create documentation around.

There is already documentation here, https://fedoraproject.org/wiki/SELinux/ConfinedUsers

Translating that into secureblue postinstall steps might be valuable

**Comment by secretmango** [comment]
agree, but the testing can be done here (see my PR) and we should be aware that some ublue/just/custom tooling may break if pipes are blocked.

**Comment by RoyalOughtness** [comment]
I was curious so I started testing this out, and confining my non-wheel user caused gnome to fail to start. 

It seems like selinux confined users aren't ready for primetime yet on fedora

**Comment by secretmango** [comment]
there seems to be a hashtag on discussion.fedoraproject.org on that topic, seems to be an ongoing process making that work.

A user reported that a `user_u` confined user was working, while the others where not launching.

Pretty strange.

**Comment by RoyalOughtness** [comment]
It's definitely not ready then. The policy probably needs significant adjustments before this can be recommended. Please reopen this if upstream announces general availability of this functionality.

**Comment by ftgjhf** [comment]
> I was curious so I started testing this out, and confining my non-wheel user caused gnome to fail to start.
> 
> It seems like selinux confined users aren't ready for primetime yet on fedora 

Supposedly, the KDE edition is usable with confined users. 
https://discussion.fedoraproject.org/t/f40-selinux-confined-users-the-first-fedora-kde-to-be-productive-with-enabled-selinux-confined-user-with-restrictions/113165
