### ISSUE TITLE
[FEAT] Disable XWayland by default whenever possible

### ISSUE THREAD

**Issue by TommyTran732** [secureblue/secureblue#339]
**Describe the benefit this feature would provide to the project**

This helps against:
- Any kind of bugs/design issues with sandboxing solutions that still expose the x11 socket to apps
- Apps accidentally using the x11 socket

**Describe the solution you'd like**
At least on GNOME, this can be done by creating `/etc/systemd/user/org.gnome.Shell@wayland.service.d/override.conf` with:

```
[Service]
ExecStart=
ExecStart=/usr/bin/gnome-shell --no-x11
```

We should a ujust command or something to allow users to reenable XWayland.

**Describe alternatives you've considered**
None. There is none that I can think of.

**Declaration**
- [x] I declare that I have read the README and my feature request is in-scope.

**Comment by secretmango** [comment]
Why is the first ExecStart= line empty? 

Note that for Flatpaks one can also just block the `x11` permission entirely, by using a global override in `~/.local/share/flatpak/overrides/global`. Here is mine:

```
[Context]
filesystems=xdg-run/pipewire-0:ro;!~/.ssh;!~/.gnupg;
sockets=!x11;!pulseaudio;wayland;
shared=!ipc;

[Environment]
QT_QPA_PLATFORM=wayland
ELECTRON_OZONE_PLATFORM_HINT=wayland
```

This forces apps to use Wayland. `fallback-x11` ensures that x11 is only used when wayland is not working. This may be used by an app, but then it should be pretty likely that it really doesnt work.

**Comment by secretmango** [comment]
On Kinoite it looks like

```
systemctl status | grep xwayland
             ├─  1806 /usr/bin/kwin_wayland_wrapper --xwayland
             ├─  1818 /usr/bin/kwin_wayland --wayland-fd 7 --socket wayland-0 --xwayland-fd 8 --xwayland-fd 9 --xwayland-display :0 --xwayland-xauthority /run/user/1003/xauth_xViBEW --xwayland
             ├─  2316 /usr/bin/xwaylandvideobridge
             └─121498 rg xwayland
```

**Comment by TommyTran732** [comment]
> Why is the first ExecStart= line empty?
> 

To override the default ExecStart.

> Note that for Flatpaks one can also just block the `x11` permission entirely, by using a global override in `~/.local/share/flatpak/overrides/global`. Here is mine:

The first point is to address the situation where this is not enough with Flatpak.
