### ISSUE TITLE
Rebrand every config file

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#34]
- [ ] [Boot menu](https://github.com/secureblue/secureblue/blob/live/boot_menu.yml) (not sure what it does and what can be changed)
- [ ] [Containerfile](https://github.com/secureblue/secureblue/blob/live/Containerfile) referring to ublue a lot
- [ ] `/.github/CODEOWNERS`
- [ ] `/config/file/usr/share/ublue-os/firstboot`

**Comment by RoyalOughtness** [comment]
CODEOWNERS can change, but the other references aren't documentation references but legitimate references to upstream information

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/557f75c71f438f4727eb58f55cc565eae9dbb485
