### ISSUE TITLE
[FEAT] Add USBGuard Polkit Rules to enable Gnome Integration

### ISSUE THREAD

**Issue by RKNF404** [secureblue/secureblue#341]
**Describe the benefit this feature would provide to the project**
There are USBGuard polkit rules to enable the Gnome USBGuard integration, without the rules the integration will not work.

**Describe the solution you'd like**
Adding the rules described [here](https://wiki.archlinux.org/title/USBGuard) in section 3.2.1 to the defined polkit rules folder.

**Describe alternatives you've considered**
There are none to get the integration working, currently.

**Declaration**
- [x] I declare that I have read the README and my feature request is in-scope.

**Comment by secretmango** [comment]
Are you referring to [this rule](https://bbs.archlinux.org/viewtopic.php?pid=2025191#p2025191)?

```
polkit.addRule(function(action, subject) {
    if ((action.id == "org.usbguard.Policy1.listRules" ||
	 action.id == "org.usbguard.Devices1.listDevices") &&
        subject.user == "your_username" )
    {
        return polkit.Result.YES;
    }
});
```

Or [this one](https://wiki.archlinux.org/title/USBGuard#Grant_GNOME_access_to_the_USBGuard_daemon) from the ArchWiki? That one sounds like quite some privileges

```
// Allow users in wheel group to communicate with USBGuard
polkit.addRule(function(action, subject) {
    if ((action.id == "org.usbguard.Policy1.listRules" ||
         action.id == "org.usbguard.Policy1.appendRule" ||
         action.id == "org.usbguard.Policy1.removeRule" ||
         action.id == "org.usbguard.Devices1.applyDevicePolicy" ||
         action.id == "org.usbguard.Devices1.listDevices" ||
         action.id == "org.usbguard1.getParameter" ||
         action.id == "org.usbguard1.setParameter") &&
        subject.active == true && subject.local == true &&
        subject.isInGroup("wheel")) {
            return polkit.Result.YES;
    }
});
```

I would edit the rule and use

```
// Allow users in wheel group to communicate with USBGuard
polkit.addRule(function(action, subject) {
    if ((action.id == "org.usbguard.Policy1.listRules" ||
         action.id == "org.usbguard.Devices1.listDevices" ||
         action.id == "org.usbguard1.getParameter" ||
        subject.active == true && subject.local == true) {
            return polkit.Result.YES;
    }
});

polkit.addRule(function(action, subject) {
    if ((action.id == "org.usbguard.Policy1.appendRule" ||
         action.id == "org.usbguard.Policy1.removeRule" ||
         action.id == "org.usbguard.Devices1.applyDevicePolicy" ||
         action.id == "org.usbguard1.setParameter") &&
        subject.active == true && subject.local == true &&
        subject.isInGroup("wheel")) {
            return polkit.Result.AUTH_ADMIN;
    }
});
```

Just by how the rules look, all users should be able to see the used rules, but editing requires wheel. Instead, we could also use `return polkit.Result.YES;` for not requiring a wheel users password.

We could also add a `usbguard` group to the rule like

```
        subject.active == true && subject.local == true && (
        subject.isInGroup("wheel") || subject.isInGroup("usbguard") )) {
```

To remove the need for wheel.

And afaik AUTH_ADMIN can also be used without `wheel` requirement, and all users could authenticate as the admin. So

```
polkit.addRule(function(action, subject) {
    if ((action.id == "org.usbguard.Policy1.appendRule" ||
         action.id == "org.usbguard.Policy1.removeRule" ||
         action.id == "org.usbguard.Devices1.applyDevicePolicy" ||
         action.id == "org.usbguard1.setParameter") &&
        subject.active == true && subject.local == true) {
            return polkit.Result.AUTH_ADMIN;
    }
});
```

Thinking about it, AUTH_ADMIN sounds like it would lock people into using a wheel account, which is suboptimal.

Instead, using a custom `usbguard` group and AUTH_SELF could be used.

**Comment by RKNF404** [comment]
@secretmango is there a point to allowing any user to view rules? Also, is there an existing usbguard group? You say it is custom so I assume it doesn't exist?

**Comment by RoyalOughtness** [comment]
following discussion and testing with @RKNF404 on discord, I'll be closing this and removing usbguard-dbus from the ujust script.

the usbguard systemd service is strongly sandboxed by systemd, but usbguard-dbus is not.

The gnome integration is consistently broken using a variety of combinations of polkit rules, including displaying popups that don't function properly and/or inconsistently showing the UI. 

This may change in F41 after fedora ships systemd service hardening, so we can check back on this issue then.

**Comment by RoyalOughtness** [comment]
```
usbguard-dbus.service                      9.6 UNSAFE    😨
usbguard.service                           2.8 OK        🙂
```

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/084fe1a40ca8f83c08ebf6930ba1628a4c37862a
