### ISSUE TITLE
[BUG] Secureblue's yafti does not start with Bluefin-dx image

### ISSUE THREAD

**Issue by fine2006** [secureblue/secureblue#348]
**Describe the bug**
After installing the `bluefin-dx-main-userns-hardened` (using rebase) , a yafti screen pops up that is not the same as the one that shows up when `ujust rerun-yafti` is ran. The welcome messages are different too

Initial Setup Screen:

When `ujust rerun-yafti` is ran:

**To Reproduce**
1. Install `bluefin-dx-main-userns-hardened` using the rebase method in the README
2. Check Yafti

**Expected behavior**
![image](https://github.com/user-attachments/assets/a6dd0578-aab3-4d95-a836-e7485d3f2f79)

**Actual behavior**
![image](https://github.com/user-attachments/assets/fae0ac9a-5c5b-4492-bf87-0afdb429d657)

**Your current image**
 - `rpm-ostree status` contents
 ```
❯ rpm-ostree status -v
State: idle
warning: Failed to query journal: couldn't find current boot in journal
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/secureblue/bluefin-dx-main-userns-hardened:latest (index: 0)
                   Digest: sha256:5e722d1e3a56204ca90ea3f6848100eb7d733ab14495b0e04d72c671db16eff8
                  Version: 40.20240729.0 (2024-07-29T17:11:39Z)
                   Commit: 36728f4c23af65bb59c9e4f6ab251741abdfa54bd8621f48879b2a8f07fc93b4
                   Staged: no
                StateRoot: default

  ostree-image-signed:docker://ghcr.io/secureblue/bluefin-dx-main-userns-hardened:latest (index: 1)
                   Digest: sha256:5e722d1e3a56204ca90ea3f6848100eb7d733ab14495b0e04d72c671db16eff8
                  Version: 40.20240729.0 (2024-07-29T17:11:39Z)
                   Commit: 36728f4c23af65bb59c9e4f6ab251741abdfa54bd8621f48879b2a8f07fc93b4
                StateRoot: default

```

**If you're using a secureblue Bluefin image**
Haven't checked

**For all images**
Haven't checked

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/b31aff0994c0d2d73623e0ab08bdd6e7219e05cc
