### ISSUE TITLE
[FEAT] allow "sudo ostree admin" actions with polkit

### ISSUE THREAD

**Issue by secretmango** [secureblue/secureblue#349]
**Describe the benefit this feature would provide to the project**
for example `sudo ostree admin pin 0` is an action that is often useful, and there are others.

These are privileged in a sense, but if pinning is a high privilege, the ability to choose the older deployment in GRUB is one too. (The danger here being preventing a security update from being applied).

These actions are currently not done with polkit but require sudo.

**Describe the solution you'd like**
Helping upstream develop a polkit rule, by testing here, and then upstreaming.

**Describe alternatives you've considered**
use sudo.

**Declaration**
- [x] I declare that I have read the README and my feature request is in-scope.

**Comment by RoyalOughtness** [comment]
secureblue is not a testing ground. 

please stop opening PRs/issues whose sole purpose is to give nonwheel users more privileges.
