### ISSUE TITLE
Love this project! Can I donate?

### ISSUE THREAD

**Issue by birds-swim** [secureblue/secureblue#354]
I have been searching for a project like this for a very long time for my home PC. 

Two years ago, I discovered Graphene OS. This motivated me to look for a harden setup for my Linux PC. This took me on a journey and discovery to find that most Linux distributions aren't shipping their disc images with hardening out of the box. I was pretty disappointed by this discovery. 

I did not have the skill or the time to try to accomplish a hardened setup with Arch Linux. So I knew I had to find a Linux distro or a GitHub project that could do the security hardening for me. For a while, that was Debian+Kicksecure. It worked okay, until I introduce too much complexity that I broke my system (I made a Franken system by using Spiral Linux as my base and converting over to Kicksecure).

So to see a Fedora-based immutable distro that has taken much inspiration from Kicksecure and GOS has me very excited about this project. 

I feel like, at last, I have found the Linux system that just right for me.

Do you have a page somewhere that accepts recurring donations? I would love to support this project in any way I can.

**Comment by RKNF404** [comment]
There is a github sponsor section for the mastermind himself on the main page of this repository.

**Comment by birds-swim** [comment]
> There is a github sponsor section for the mastermind himself on the main page of this repository.

Thank you! I'll check there.

**Comment by RoyalOughtness** [comment]
Thanks! Github Sponsors is preferred, yes

https://github.com/secureblue/secureblue/blob/live/DONATE.md
