### ISSUE TITLE
[BUG] Long blackscreen after entering login details and seemingly random logout after a while

### ISSUE THREAD

**Issue by kreativK** [secureblue/secureblue#356]
**Describe the bug**
After I start the system and enter my login details there is a very long wait with just a plain black screen until I hear the boot sound and the system actually starts. After this there is a chance that the screen just randomly goes black again after which I have to log in for a second time. This time the screen goes black again but the system never starts, even after I hear the boot up sound.

**To Reproduce**
Boot up system and login

**Expected behavior**
The system starts shortly after the correct login details are entered and doesn't log me out

**Actual behavior**
The system is very slow to start after entering the correct login details. Sometimes the screen goes black again after a seemingly random amount of time and I'm logged out, after which I have to restart the system if I want to be able to start again.

**Your current image**
kinoite-asus-nvidia-userns-hardened

It may have something to do with nvidia drivers, I found someone having a similar issue: https://discussion.fedoraproject.org/t/fedora-kde-40-freezing-shortly-after-login-kde-6-8-10-300-fc40-x86-64/118804

The only thing I have done with nvidia drivers is running 
rpm-ostree kargs \
    --append-if-missing=rd.driver.blacklist=nouveau \
    --append-if-missing=modprobe.blacklist=nouveau \
    --append-if-missing=nvidia-drm.modeset=1

I am dual booting with windows 11 if that maybe has something to do with it.

**Comment by RoyalOughtness** [comment]
can you reproduce this on a non-asus image?

and what about on a non-secureblue image?

**Comment by kreativK** [comment]
I'm sorry but actually I can't reproduce this issue again, everything boots like it should right now. I have no idea what caused it or what has changed, maybe it will come back again tomorrow or something, or it's just straight up fixed. I'll just continue to use the system as usual and see.

**Comment by RoyalOughtness** [comment]
okay :smile:

if it happens again please test on a non-asus image and also a non-secureblue image to narrow down the issue
