### ISSUE TITLE
[BUG] the Fedora installer touches pam/authselect files, which show up as overrides

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#358]
This prevents changes in the image from being applied properly. This should be fixed on first rebase, either by yafti or some other method

Related to https://github.com/secureblue/secureblue/issues/310

**Comment by RoyalOughtness** [comment]
@34N0 let me know if you have any ideas on this. Otherwise I'm thinking we can just have yafti ensure that the pam/authselect files for /usr and /etc match on first rebase

**Comment by wandapeter** [comment]
Looking at the failed build logs it seems like authselect expects the profile files to be inside `/etc`  but at build level the files are still only in `/usr/etc`? 

I think a yafti command like "harden pam" would be a good solution to make sure `/etc` and `usr` match and then use the authselect command to select our custom profile. 

I forgot exactly how bluebuild works, are we able to define a `/etc` at build level which is not `/usr/etc`?

**Comment by RoyalOughtness** [comment]
> I forgot exactly how bluebuild works, are we able to define a /etc at build level which is not /usr/etc?

I don't believe so, but also that would be undesirable.

/etc is for user-overrides. /usr is for the image

> I think a yafti command like "harden pam" would be a good solution to make sure /etc and usr match and then use the authselect command to select our custom profile.

There are two different issues here. The image itself should already be hardened out of the box, which is what you're already working on. The problem is that for users that rebase from Fedora Atomic, the installer will have already set overrides in /etc, so we'll need to undo those on initial install

**Comment by RoyalOughtness** [comment]
FYI I added a check for this to `ujust audit-secureblue`
