### ISSUE TITLE
remove fedora-chromium-config-gnome and fedora-chromium-config-kde

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#359]

**Comment by symbiogenesis** [comment]
Can you explain the rationale for this one, for documentation purposes.

**Comment by RoyalOughtness** [comment]
@symbiogenesis we're not using fedora's chromium. we're building and shipping our own: https://github.com/secureblue/hardened-chromium

**Comment by symbiogenesis** [comment]
This package provides KDE integration. Makes sense to remove it for security, but are there any integration features that could be safely added to hardened-chromium? Maybe they already are? I can see you took fedora patches
