### ISSUE TITLE
[FEAT] hardened Unprivileged user namespaces by Apparmor

### ISSUE THREAD

**Issue by Bammede** [secureblue/secureblue#374]
**Describe the benefit this feature would provide to the project**
Unprivileged user namespaces blocked on system level, but available for some apps/packages.

With this settings, podman, distrobox, flatpak could work with no extra workarounds. 
Namespaces available just for selected apps.

**Describe the solution you'd like**
Apparmor: https://gitlab.com/apparmor/apparmor/-/wikis/unprivileged_userns_restriction

**Describe alternatives you've considered**
no alternative

**Declaration**
I declare that I have read the README and my feature request is in-scope.

**Comment by TheHooly** [comment]
Not directly applicable since Fedora uses SELinux, not AppArmor.

IIRC this AppArmor restriction also relies on a downstream patch in Ubuntu's kernel and as such is not available in all kernels.

IMHO figuring out how to replicate Ubuntu's behaviour regarding UUNs with SELinux would be worthwhile, though.

**Comment by TheHooly** [comment]
On second thought this doesn't sound like a good idea anymore. A malicious process could simply call podman/distrobox/bubblewrap (the not-SUID variant) to set up a user namespace with additional capabilities, enabling the same security concerns as having them available to any process by default.

Especially bubblewrap specifies that it does not consider itself a security boundary when user namespaces are used:
https://github.com/containers/bubblewrap/security#system-security

**Comment by RoyalOughtness** [comment]
mixing selinux and apparmor is a recipe for disaster :smile:

**Comment by RoyalOughtness** [comment]
if there's another way to accomplish this, please reopen this. until then this isn't actionable
