### ISSUE TITLE
[FEAT] Some additional hardening I used on various distros

### ISSUE THREAD

**Issue by Bammede** [secureblue/secureblue#375]
Here are some hardening options I used on various distros, perhaps some of them could be implemented here.
Haven't found these on secureblue, so maybe they are useless on Atomic distro?

1. Umask system wide 0027
2. Umask home directories 0077
3. Coredumps another settings:
`/etc/systemd/coredump.conf.d/disable.conf`

```
[Coredump]
Storage=none
ProcessSizeMax=0
```

4. Lock all empty password accounts, if existed:
`passwd -l ....`
5. Make sure no non-root accounts have UID set to 0
`awk -F: '($3 == "0") {print}' /etc/passwd`
6. Disable CTRL+ALT+DEL reboot systemd service
ctrl-alt-del.target
7. RKhunter
8. Set default firewalld zone to block
9. Block other applications to make changes via sudo or wheel in firewalld:
`firewall-cmd --lockdown-on`
10. Disable Printer sharing in CUPS:
`cupsctl --no-share-printers`
11. Sshd config if enabled:
```
      Port ............
      ListenAddress 0.0.0.0
      PasswordAuthentication no
      PermitUserEnvironment no
      Protocol 2
      AllowTcpForwarding no
      AllowStreamLocalForwarding no
      GatewayPorts no
      UseDNS no
      Compression no
      TCPKeepAlive no
      AllowAgentForwarding no
      PermitTunnel no
      PermitEmptyPasswords no
      PubkeyAuthentication yes
      PermitRootLogin no
      IgnoreRhosts yes
      HostbasedAuthentication no
      ClientAliveInterval 600
      X11Forwarding no
      ChallengeResponseAuthentication no
      UsePAM yes
      PrintMotd no
      maxauthtries 2
      maxsessions 2
      AllowGroups ...........
      AcceptEnv LANG LC_*
```

**Comment by RoyalOughtness** [comment]
1/2.  umask is already set system wide to 027, 077 is probably aggressive as a default

3. coredumps are already disabled in multiple places. 

4. can cause significant breakage last I tested it, also I don't think it has any effect at image build time

5. users aren't managed at build time

6. why? this disables functionality while providing unclear/dubious security benefit

7. this just confused users with false positives. users that want it can install it with brew. there's no need to put it in the image

8. why? this disables functionality while providing unclear/dubious security benefit

9. this seems highly dubious. if an application is running as wheel, you've already granted it too much

10. cups is already completely disabled by default

11. already largely covered

Please make sure you're searching the repo to make sure you're not suggesting things that are already covered. If there are incremental improvements that can be made, please resubmit them as individual issues or pull requests.
