### ISSUE TITLE
[BUG] Issue with re-enabling xwayland on Kinoite main image

### ISSUE THREAD

**Issue by moonlitOrca** [secureblue/secureblue#390]
Following the switch to default disable of xwayland on the main images, I tried to re-enable xwayland on Kinoite using the command `ujust toggle-xwayland`.  After selecting KDE Plasma as the DM, the terminal displays a successful enabling of xwyaland.   However, none of the applications that attempt to access the display manager using that subsystem are successful.  In my case, I am attempting to use Zoom Flatpak, Brave, and Synology Drive Flatpak.  

1. on Kinoite image, re-enable Xwayland using `ujust toggle-xwayland` command
2. reboot
3. Attempt to run an application that must fallback to X11 display mode
4. See error that the application is unable to access the display manager

The expectation is that this toggle will re-enable the necessary service and the applications can normally run.

Actual Behavior:
However, the display server remains inaccessible.

**Your current image**
 ostree-image-signed:docker://ghcr.io/secureblue/kinoite-main-userns-hardened:latest
                   Digest: sha256:7f8efb0c069f16f8b445122f9980fbc131ed64cff874ca2769c24d9b99577ed8
                  Version: 40.20240821.0 (2024-08-22T19:18:30Z)

**Comment by RoyalOughtness** [comment]
please provide the output of:

```
cat /etc/systemd/user/plasma-kwin_wayland.service.d/override.conf
```
and

```
ps aux | grep kwin
```

**Comment by moonlitOrca** [comment]
the first command returned:
`cat: /etc/systemd/user/plasma-kwin_wayland.service.d/override.conf: No such file or directory`

the second command returns:
```
dj          4887  0.0  0.0 13350827624 19812 ?   Ssl  01:26   0:00 /usr/bin/kwin_wayland_wrapper --xwayland
dj          4900  3.2  0.4 13411281936 267916 ?  Sl   01:26   0:49 /usr/bin/kwin_wayland --wayland-fd 7 --socket wayland-0 --xwayland-fd 8 --xwayland-fd 9 --xwayland-display :0 --xwayland-xauthority /run/user/1000/xauth_XeJXlW --xwayland
dj          8915  0.0  0.0 13433085304 5772 pts/1 S+  01:51   0:00 grep --color=auto kwin

```

**Comment by RoyalOughtness** [comment]
xwayland is enabled successfully and kwin is running with xwayland

are these flatpaks and did you revoke their x11 access?

**Comment by RoyalOughtness** [comment]
also FYI, if you're using Brave as a flatpak, don't: https://forum.vivaldi.net/topic/33411/flatpak-support/192

**Comment by moonlitOrca** [comment]
OK!  two things: 
1. After your response, I messed with the flatseal permissions. I realized that I had granted wayland permissions to Synology Drive and Zoom, and somehow that prevented it from using X11 even though it had both permissions.  So I had to remove the Wayland permission from them and now they work.

2.  I was indeed using the Brave flatpak, but I will switch to the native install then.  I love the hardened Chromium you have bundled, btw.  I just use two different browsers to separate different browsing tasks.

I apologize for apparently opening an mistaken issue!  Thanks for your help.  I didn't realize that granting Wayland permissions could somehow interefere with X permissions on some flatpaks

**Comment by RoyalOughtness** [comment]
> I just use two different browsers to separate different browsing tasks.

You can use profiles, that's what they're for :smile: 

>  didn't realize that granting Wayland permissions could somehow interefere with X permissions on some flatpaks

That is strange. It would make more sense if it was fallback-x11.

> I apologize for apparently opening an mistaken issue! 

no problem
