### ISSUE TITLE
[FEAT] Disable Passim Cache Server

### ISSUE THREAD

**Issue by Bammede** [secureblue/secureblue#397]
**Describe the benefit this feature would provide to the project**
Close 27500 port.

**Describe the solution you'd like**
Disable and Mask passim.service, so 27500 port will not be opened. It is not mandatory service.

**Describe alternatives you've considered**
N/A

**Declaration**
- I declare that I have read the README and my feature request is in-scope.

**Comment by RoyalOughtness** [comment]
secureblue disables all incoming ports by default

as far as attack surface reduction goes, this seems low priority since it's already relatively well sandboxed by systemd:
```
passim.service                             3.4 OK        🙂
```

**Comment by Bammede** [comment]
BTW. Fedora 41 is gonna harden systemd. https://fedoraproject.org/wiki/Changes/SystemdSecurityHardening

**Comment by RoyalOughtness** [comment]
@Bammede yep, good stuff! 😄

**Comment by RoyalOughtness** [comment]
According to `rpm -q`, the only package in our images pulling in passim is fwupd, and it's only a recommended package. So this can just be removed.

**Comment by Bammede** [comment]
yes fwupd uses passim.service to open port for packages distribution. fwupd doesn't need it to work, so disabling and masking passim.service will do no harm to the system, just close the port.

**Comment by RoyalOughtness** [comment]
@Bammede no need, I'm just going to uninstall it :)

**Comment by Bammede** [comment]
Ok, not sure you can remove passim, masking and disabling passim.service could be the only option. Anyway, thanks for the effort.
