### ISSUE TITLE
[BUG] Can't update my system or do a rebase anymore (bluefin nvidia image)

### ISSUE THREAD

**Issue by Tracker3223** [secureblue/secureblue#407]
**Describe the bug**
── 15:04:03 - System update ────────────────────────────────────────────────────
note: automatic updates (stage) are enabled
Pulling manifest: ostree-image-signed:docker://ghcr.io/secureblue/bluefin-nvidia-userns-hardened:latest
error: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: A signature was required, but no signature exists
System update failed: 
   0: Command failed: `/usr/bin/rpm-ostree upgrade`
   1: `/usr/bin/rpm-ostree` failed: exit status: 1

Location:
   src/steps/os/linux.rs:273
Retry? (y)es/(N)o/(s)hell/(q)uit

Where do i get those signatures again?

**To Reproduce**
I try to rebase to unverified image here:

```rpm-ostree rebase ostree-unverified-registry:ghcr.io/secureblue/bluefin-nvidia-userns-hardened:latest
Pulling manifest: ostree-unverified-registry:ghcr.io/secureblue/bluefin-nvidia-userns-hardened:latest
error: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: A signature was required, but no signature exists
```

Still not working! What's wrong here?

**Expected behavior**
Updates and rebase is working as intended.

**Actual behavior**
Update or rebasing to bluefin image not working

**Your current image**
 - `rpm-ostree status` contents
```State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 1 day 4h ago
Deployments:
● ostree-image-signed:docker://ghcr.io/secureblue/bluefin-nvidia-userns-hardened:latest
                   Digest: sha256:f160de612b6d4a75ad24377723540e703af83e3a741a021ee81c3a62c44b07de
                  Version: 40.20240827.0 (2024-08-28T05:33:17Z)

  ostree-image-signed:docker://ghcr.io/secureblue/bluefin-nvidia-userns-hardened:latest
                   Digest: sha256:0e45ee07c73152db65f4b44b373cee7551a325d89256e3a90b96b736a9faf830
                  Version: 40.20240826.0 (2024-08-27T05:30:44Z)
```
**If you're using a secureblue Bluefin image**
 - Confirm you can repro on a secureblue silverblue image
Can't confirm, that silverblue image works:
`rpm-ostree rebase ostree-image-signed:docker://ghcr.io/secureblue/silverblue-nvidia-userns-hardened:latest`

**For all images**
- Confirm you cannot repro on a uBlue base image
`rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-nvidia:latest`
That upstream bluefin image works too!

**Comment by Rubiginosa** [comment]
Facing the same issue on my own image downstream from secureblue.

**Comment by RoyalOughtness** [comment]
Given that aurora-nvidia-userns and bluefin-main-userns both work fine, i think this is a transient signing failure that should go away after the next daily build

**Comment by RoyalOughtness** [comment]
New build is running due to a recent commit. https://github.com/secureblue/secureblue/actions/runs/10620402620

The server images will fail due to kernel package drift. However the others will succeed. Please try again once the image in question is done building @Tracker3223

**Comment by RoyalOughtness** [comment]
looks fixed now
