### ISSUE TITLE
[BUG] Rebase custom image based in Secureblue - rejected by policy

### ISSUE THREAD

**Issue by Bammede** [secureblue/secureblue#416]
**Describe the bug**
Custom Bluebuild image based on Secureblue-Silverblue cannot be signed:

`rpm-ostree rebase ostree-unverified-registry:ghcr.io......` works
` rpm-ostree rebase ostree-image-signed:docker://ghcr.io.....` does not.

**To Reproduce**
Setting up own Bluebuild custom image. All private and public keys are set due to BlueBuild instructions.

**Expected behavior**
Should be able to rebase with signed image.

**Actual behavior**
After running ` rpm-ostree rebase ostree-image-signed:docker://ghcr.io.....` 
error occur:
`Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: Running image docker://ghcr.io/...... is rejected by policy.`

My policy.json file contains paths to public key of my repo and others, but because you have hardened it and set all other settings to `reject` maybe I should modify it, but how, what to change?

**Comment by Rubiginosa** [comment]
Could you share your policy.json? I have a similar issue (also downstream from secureblue via bluebuild) but it's a little different.

**Comment by Bammede** [comment]
```
{
  "default": [
    {
      "type": "reject"
    }
  ],
  "transports": {
    "docker": {
      "ghcr.io/Bammede/custom-name": [
        {
          "type": "sigstoreSigned",
          "keyPath": "/usr/etc/pki/containers/custom-name.pub",
          "signedIdentity": {
            "type": "matchRepository"
          }
        }
      ],
      "ghcr.io/secureblue": [
        {
          "type": "sigstoreSigned",
          "keyPath": "/usr/etc/pki/containers/secureblue.pub",
          "signedIdentity": {
            "type": "matchRepository"
          }
        }
      ],
      "ghcr.io/zelikos": [
        {
          "type": "sigstoreSigned",
          "keyPath": "/usr/etc/pki/containers/davincibox.pub",
          "signedIdentity": {
            "type": "matchRepository"
          }
        }
      ],
      "ghcr.io/jasonn3": [
        {
          "type": "sigstoreSigned",
          "keyPath": "/usr/etc/pki/containers/build-container-installer.pub",
          "signedIdentity": {
            "type": "matchRepository"
          }
        }
      ],
      "registry.access.redhat.com": [
        {
          "type": "signedBy",
          "keyType": "GPGKeys",
          "keyPath": "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"
        }
      ],
      "registry.redhat.io": [
        {
          "type": "signedBy",
          "keyType": "GPGKeys",
          "keyPath": "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"
        }
      ],
      "quay.io/toolbx-images": [
        {
          "type": "sigstoreSigned",
          "keyPath": "/etc/pki/containers/quay.io-toolbx-images.pub",
          "signedIdentity": {
            "type": "matchRepository"
          }
        }
      ],
      "ghcr.io/ublue-os": [
        {
          "type": "sigstoreSigned",
          "keyPath": "/etc/pki/containers/ublue-os.pub",
          "signedIdentity": {
            "type": "matchRepository"
          }
        }
      ],
      "": [
        {
          "type": "reject"
        }
      ]
    },
    "docker-daemon": {
      "": [
        {
          "type": "reject"
        }
      ]
    },
    "atomic": {
      "": [
        {
          "type": "reject"
        }
      ]
    },
    "containers-storage": {
      "": [
        {
          "type": "reject"
        }
      ]
    },
    "dir": {
      "": [
        {
          "type": "reject"
        }
      ]
    },
    "oci": {
      "": [
        {
          "type": "reject"
        }
      ]
    },
    "oci-archive": {
      "": [
        {
          "type": "reject"
        }
      ]
    },
    "docker-archive": {
      "": [
        {
          "type": "reject"
        }
      ]
    },
    "tarball": {
      "": [
        {
          "type": "reject"
        }
      ]
    }
  }
}

```

**Comment by RoyalOughtness** [comment]
@Bammede are you rebasing to the unsigned image before the signed?

If not then `/usr/etc/pki/containers/custom-name.pub` won't be present, so it will fail

**Comment by Bammede** [comment]
@qoijjj  Yes, first I rebase to unsigned image then try to rebase to signed one.

`rpm-ostree rebase ostree-unverified-registry:ghcr.io......` works
`rpm-ostree rebase ostree-image-signed:docker://ghcr.io.....` does not.

**Comment by RoyalOughtness** [comment]
@qoijjj so then the issue is rebasing from the unverified custom image to the verified custom image? You should be rebasing to unverified first anyways. I'm not sure how this pertains to secureblue if you're able to switch to your unverified custom image already.

**Comment by Rubiginosa** [comment]
I can actually repro this on my own custom image, and I think I understand what @Bammede is saying.

For me:
Install silverblue cleanly.
Rebase to the unverified image. This completes succesfully. rpm-ostree can layer things without any problem.
At this point, though, rpm-ostree upgrade will start failing with a "signature was required, but no signature was found" error. The same issue occurs when attempting to rebase from my unverified image to my verified one.

I haven't had the time to test if this is a problem with bluebuild. I plan to recreate my images using ublue as a base and see what happens.

@qoijjj I think this should be open until we confirm that it's not secureblue-specific.

**Comment by RoyalOughtness** [comment]
> Install silverblue cleanly.
> Rebase to the unverified image. This completes succesfully. rpm-ostree can layer things without any problem.
> At this point, though, rpm-ostree upgrade will start failing with a "signature was required, but no signature was found" error. The same issue occurs when attempting to rebase from my unverified image to my verified one.

This doesn't happen on secureblue. If it's happening on your custom image, then either your policy.json isn't being set properly in your build, or you have local overrides. Either way it's not related to secureblue as far as I can tell.

**Comment by Rubiginosa** [comment]
Just to wrap this up in case anyone comes looking: the same issue occurred when I moved my image to point to ublue's silverblue. I resolved everything by recreating my custom image with the latest template. My guess is that something changed a month or so ago that messed up repos created with the old one.
