### ISSUE TITLE
[BUG] Cannot Rebase to Custom BlueBuild Image Based On SecureBlue

### ISSUE THREAD

**Issue by jacobleblanc-cs** [secureblue/secureblue#418]
**Describe the bug**
When attempting to rebase my system running the `wayblue-hyprland-main-userns-hardened` image with
 `sudo rpm-ostree rebase ostree-image-signed:docker://ghcr.io/jacobleblanc-cs/andromeda:latest` 
the process fails with error: 
`error: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: Running image docker://ghcr.io/jacobleblanc-cs/andromeda:latest is rejected by policy.`
For reference, my custom image is [linked here](https://github.com/jacobleblanc-cs/andromeda). Unsure if I missed a step, but from the documentation I believe I've checked all the boxes.

**To Reproduce**
1. Create a BlueBuild image using the [standard template](https://github.com/blue-build/template)
2. Configure cosign as documented [here](https://blue-build.org/how-to/cosign/)
3. Change base image to a SecureBlue image, in this case `wayblue-hyprland-main-userns-hardened`
4. Attempt to rebase with `rpm-ostree rebase ...` as described above

**Expected behavior**
System rebases to my custom unsigned image, and then I can rebase again to the signed image.

**Actual behavior**
Failure due to rejection by policy.

**Your current image**
 State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 3h 15min ago
Deployments:
  ostree-image-signed:docker://ghcr.io/secureblue/wayblue-hyprland-main-userns-hardened:latest
                   Digest: sha256:06d8f87fd4595f6062127bf9a1da5562d277c3c995c146bf3e7eae61b01a28e8
                  Version: 40.20240905.0 (2024-09-06T05:47:44Z)
                     Diff: 32 upgraded

● ostree-image-signed:docker://ghcr.io/secureblue/wayblue-hyprland-main-userns-hardened:latest
                   Digest: sha256:a8417faac24f32492267fe30e18d054d24d498952c5b5548f315f3260989d39f
                  Version: 40.20240902.0 (2024-09-05T05:46:43Z)

  ostree-unverified-registry:ghcr.io/secureblue/wayblue-hyprland-main-userns-hardened:latest
                   Digest: sha256:a8417faac24f32492267fe30e18d054d24d498952c5b5548f315f3260989d39f
                  Version: 40.20240902.0 (2024-09-05T05:46:43Z)

**Comment by Rubiginosa** [comment]
First rebase to a non-secureblue image. Secureblue's policy rejects containers from unknown repos.

**Comment by jacobleblanc-cs** [comment]
Noted, thank you very much! Problem solved by rebasing to wayblue's hyprland image first then into my secureblue spin.

**Comment by RoyalOughtness** [comment]
you need to rebase to `unverified` first since the cosign pubkey for your custom image isn't present on secureblue

**Comment by jacobleblanc-cs** [comment]
My mistake in the post, I actually pasted the wrong line.  However I did initially try to rebase to unverified first but got the same message. However it's working now so :man_shrugging:
