### ISSUE TITLE
[BUG] securecore: audit checks GNOME extensions

### ISSUE THREAD

**Issue by q-b** [secureblue/secureblue#422]
On securecore, `ujust audit-secureblue` checks if GNOME user extensions are disabled

Image: securecore-main-userns-hardened:latest
Digest: sha256:5c57fe8e01763276acd36eb5d1b295a717f7855cf83aade4d7df8a62074c55be
```
$ ujust audit-secureblue
...
Ensuring GNOME user extensions are disabled...                   [ FAILURE ]
...
```

**Comment by EsseLowNitro** [comment]
The script currently checks for `gsettings` (with `command -v gsettings`) before proceeding with the test, maybe the `securecore` images have it somehow? It doesn't seem to test for it in other DEs. (Edit: in images with GUIs, jtbc)

If no solution lies there, making the script check what is the current image could lead to a fix. MOTD queries `rpm-ostree status` to get the current image string, but I wonder if there is any slightly faster way to do the same thing?

If not, I can implement that.

**Comment by RoyalOughtness** [comment]
@q-b do you have anything layered that would pull in gnome stuff?

**Comment by RoyalOughtness** [comment]
@EsseLowNitro  @q-b I just checked my securecore machine, and it looks like gsettings is being added by glib2, which is pulled in by podman/conmon for some reason.

@EsseLowNitro we could just check for the presence of `gnome-shell` on the terminal?

**Comment by EsseLowNitro** [comment]
@qoijjj yeah, that works much better.
