### ISSUE TITLE
[BUG] Issue with running some applications

### ISSUE THREAD

**Issue by Cicindis** [secureblue/secureblue#425]
**Describe the bug**
I'm trying to run the Krita and GIMP apps but they cannot open, I installed both as flatpaks with the software app, but I also tried running Krita as appimage and the same error happens.
I also tried following the advice on [this](https://discussion.fedoraproject.org/t/how-to-run-application-on-wayland/76949/4) thread, and executed the command `unset QT_QPA_PLATFORM`, but the error still happens.

After trying to run the app with the command `flatpak run org.kde.krita`, this warning appears:
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, xcb.
```

**Your current image**
State: idle
warning: Failed to query journal: couldn't find current boot in journal
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 3h 52min ago
Deployments:
  ostree-image-signed:docker://ghcr.io/secureblue/silverblue-nvidia-userns-hardened:latest
                   Digest: sha256:3448f166b2ab3e57b5d7c611bdea8c3f9f304224f6f8717deb1f5cfcfdea5c90
                  Version: 40.20240911.0 (2024-09-12T05:42:39Z)
                     Diff: 55 upgraded, 1 removed, 1 added

● ostree-image-signed:docker://ghcr.io/secureblue/silverblue-nvidia-userns-hardened:latest
                   Digest: sha256:30e5fc0437c7fc66c1456306c5783568a7c2925dee324b4c8639fa7d7a3c37ae
                  Version: 40.20240908.0 (2024-09-09T05:42:11Z)

  ostree-image-signed:docker://ghcr.io/secureblue/silverblue-nvidia-userns-hardened:latest
                   Digest: sha256:30e5fc0437c7fc66c1456306c5783568a7c2925dee324b4c8639fa7d7a3c37ae
                  Version: 40.20240908.0 (2024-09-09T05:42:11Z)

AvailableUpdate:
   Total layers: 69
           Size: 4.2 GB
 Removed layers: 10
           Size: 2.3 GB
   Added layers: 10
           Size: 2.3 GB

**Comment by RoyalOughtness** [comment]
Xwayland is disabled by default in secureblue. Please consult the FAQ for details and how to enable it if need be.

That said, if you install GIMP from flathub-beta-verified it supports wayland natively. Unsure about Krita. If it doesn't then you can turn Xwayland on via the toggle in the FAQ like I mentioned.

**Comment by EsseLowNitro** [comment]
Neither app supports Wayland, only X11, and secureblue disables XWayland by default, which can be re-enabled with the `ujust toggle-xwayland` command.

By the way, Krita immediately crashed on launch due to some memory corruption bug as I tested forcing these apps to run on Wayland, so you'll have to disable hardened_malloc *for Krita* for it to run.
