### ISSUE TITLE
[FEAT] Poweroff On Lid Close

### ISSUE THREAD

**Issue by Bammede** [secureblue/secureblue#426]
**Describe the benefit this feature would provide to the project**
Closing laptop lid will suspend your system unencrypted, so if you were to lose the laptop or have it taken from you, everything on-disk can still be accessed as the key is in memory.

**Describe the solution you'd like**
OS shut down when I close the lid, rather than suspending

edit the file `/etc/systemd/logind.conf`

Find the lines that start with “HandleLidSwitch”, and type `poweroff`

![image](https://github.com/user-attachments/assets/dedf912d-1eb4-4559-b9dd-c122be30cf53)

**Comment by ghost** [comment]
Not sure if you want this as a default or toggleable option, but I think this shouldn't be a default as it would very likely lead to data loss if not communicated correctly to the end users.

**Comment by Bammede** [comment]
@graphene1over Perhaps Ujust toggle would be better?

**Comment by RoyalOughtness** [comment]
This isn't really a security feature request. Suspend on lid close is expected and normal. If the user wants to shut down the machine, they have numerous other ways to do so.
