### ISSUE TITLE
[BUG] Add initcall_blacklist=simpledrm_platform_driver_init to nvidia image kargs

### ISSUE THREAD

**Issue by kreativK** [secureblue/secureblue#431]
In the [postinstall readme](https://github.com/secureblue/secureblue/blob/live/POSTINSTALL-README.md) , add a blacklist for simplerdm_platform_driver_init like so: 

rpm-ostree kargs \
    --append-if-missing=rd.driver.blacklist=nouveau \
    --append-if-missing=modprobe.blacklist=nouveau \
    --append-if-missing=nvidia-drm.modeset=1 \
    --append-if-missing=initcall_blacklist=simpledrm_platform_driver_init
    
This fixes problems with a fake "unknown" display in system settings, poor performance and graphic bugs in some programs. This fix works for the kinoite-asus-nvidia-userns-hardened image, but have caused issues with other nvidia images before. If it still does, maybe add a separate instruction for nvidia-asus images.

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/e0554019bbf94974872bfe70d594826c49ab48da
