### ISSUE TITLE
[FEAT] add rebase script akin to the iso script that interactively prompts the user and rebases according to their answers

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#443]
it should also ensure that the installed system is fedora atomic

**Comment by Rubiginosa** [comment]
Considering how to get a list of images:
- manually updated list in the script. Each time an image is added or removed, this would need to be updated.
- cloning the git repo and checking the recipe files, maybe checking build.yml. seems wasteful, maybe make use of a sparse clone?
- querying ghcr.io somehow. I know that old images are often still available, and sometimes can't be taken down, so not sure
- A github action that checks which recipes are set to build and generates the script with the image list.

It would also be nice to have some metadata about the images: are the stable, experimental, recommended; are they nvidia or not; give a little information about userns vs none

**Comment by Rubiginosa** [comment]
I suppose on the model of `generate_secureblue_iso.sh` it can just be updated intermittently.
