### ISSUE TITLE
Blacklist modules relating to serial and parallel ports

### ISSUE THREAD

**Issue by symbiogenesis** [secureblue/secureblue#452]
Wondering what you think about blacklisting the following loadable modules:

- ppdev
- parport
- parport_cs
- parport_pc
- parport_serial
- serio_raw

Saw some discussion of serio_raw being a potential vulnerability, but it also sounds potentially necessary for laptop keyboards. The module itself was written in 2004 and most laptop keyboards today shouldn't be using a serial interface.

https://bbs.archlinux.org/viewtopic.php?id=280213

**Comment by mintpilo** [comment]
Asking this not to challenge you, but could you provide a better source? Especially for anybody who looks at this issue later, that forum thread dosen't go in a lot of detail, and seems to mostly being someone making their own interpretation of a situation, followed by people asking for full logs, and context... and then only really being met by radio silence.

**Comment by RoyalOughtness** [comment]
Agreed, the linked thread is just someone vaguely speculating.

Disabling anything that would affect laptop keyboard functionality ootb would need to have crystal clear justification of the severity of the underlying security issue. This is unlike other blacklisted modules like [unused filesystems](https://github.com/secureblue/secureblue/blob/live/files/system/etc/modprobe.d/blacklist.conf#L51) which need very little justification given their nonexistent usage.

Given how far the linked thread is from the necessary justification, I'm closing this pending better sources/rationale.
