### ISSUE TITLE
KDE desktop sharing security

### ISSUE THREAD

**Issue by symbiogenesis** [secureblue/secureblue#453]
krfb is a VNC server that is included in Kinoite by default. It looks like they want to deprecate it in favor of an RDP server based on PipeWire called krdp.

krdp is provided by default, although it doesn't seem to work very well. But krfb is also still there by default, even in Plasma 6.2

When I launched it initially, I believe it gave a warning about unencrypted connections. Perhaps this package should be removed, or hardened to only allow encrypted connections.

https://quantumproductions.info/articles/2023-08/remote-desktop-using-rdp-protocol-plasma-wayland

**Comment by mkkvcs** [comment]
I believe it should be removed, I cannot find any "hardening" settings available, except not announcing the service over the whole network.

**Comment by symbiogenesis** [comment]
> I believe it should be removed, I cannot find any "hardening" settings available, except not announcing the service over the whole network.

I was likewise unable to find any documentation about hardening or restricting unencrypted connections.

krdp, by contrast, required me to set SSH keys and wouldn't launch without that. (also wouldn't launch with them, but that is another issue)

**Comment by mintpilo** [comment]
A PR fixing the issue has been merged, so this should likely be closed.
