### ISSUE TITLE
[FEAT] Disable TCP timestamps

### ISSUE THREAD

**Issue by symbiogenesis** [secureblue/secureblue#459]
[Madaidan's guide](https://madaidans-insecurities.github.io/guides/linux-hardening.html#mac-address-spoofing) linked in the Readme mentions disabling TCP timestamps, but it is not set in [/etc/sysctl.d/hardening.conf
](https://github.com/secureblue/secureblue/blob/live/files/system/etc/sysctl.d/hardening.conf)

Adding this line should disable it:

`net.ipv4.tcp_timestamps=0`

The downside is that it could interfere with network congestion control and other routing performance/reliability features.

**Comment by RoyalOughtness** [comment]
The linked documentation mentions only that this can potentially reveal the local time, which is at most a vague privacy concern and not a security concern of any significance. Therefore it's not in scope, and even if it was it probably wouldn't be worth the reliability impact.
