### ISSUE TITLE
[FEAT] Nvidia Kargs just Command

### ISSUE THREAD

**Issue by mintpilo** [secureblue/secureblue#472]
**Describe the benefit this feature would provide to the project**
This would make it so users would have one less thing to copy and paste, post install. They could instead simply just type in something like `ujust set-kargs-nvidia` (or also copy/paste it)  This would also make things more consistent with the rest of the post install process.

**Describe the solution you'd like**
Have the first [rpm-ostree command](https://github.com/secureblue/secureblue/blob/live/POSTINSTALL-README.md#nvidia) the post install readme asks people to copy/paste ran by a ujust command instead. The second command should remain manual as it only applies to certain setups. Additionally, document these kargs in a separate category in [70-secureblue.just.readme.md](https://github.com/secureblue/secureblue/blob/live/files/system/usr/share/ublue-os/just/70-secureblue.just.readme.md)

**Alternative I've considered**
Would it instead be possible to automatically apply these if somebody is on one of the Nvidia images, potentially via a recipe? Especially as they're fairly harmless, and most users running on the Nvidia images will *want* to apply them.

**Declaration**
- [x] I declare that I have read the README and my feature request is in-scope.

**Comment by RoyalOughtness** [comment]
`ujust configure-nvidia` from upstream has this, but I believe it's missing the fbdev karg

So the options are: get a change made upstream and then recommend upstream's command

or:

use `patch` to patch out upstream's command and add ours instead, to prevent user confusion with two identical commands
