### ISSUE TITLE
[BUG] Issue with "Create a new custom distrobox" Error: ... rejected by policy

### ISSUE THREAD

**Issue by olmet** [secureblue/secureblue#477]
**Describe the bug**
Creating a new distrobox ends with an error: copying system image from manifest list: Source image rejected: Running image docker://debian:latest is rejected by policy.

**To Reproduce**
1. Terminal:
```
ujust distrobox-new debian
Please enter a name for the container: debian
Resolved "debian" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/debian:latest...
```
2. See error
```
copying system image from manifest list: Source image rejected: Running image docker://debian:latest is rejected by policy.
```

**Your current image**
 - `rpm-ostree status` contents
 ```
● ostree-image-signed:docker://ghcr.io/secureblue/silverblue-main-userns-hardened:latest
                   Digest: sha256:26bcb030603e4a10ad3ca987560b6f3a924f5e0056d09e236e169f18f4ec3a41
                  Version: 40.20241020.0 (2024-10-20T06:25:16Z)
```

**Comment by RoyalOughtness** [comment]
Use `ujust distrobox-assemble debian` as described in the FAQ:

https://github.com/secureblue/secureblue/blob/live/FAQ.md#how-do-i-provision-signed-distroboxes
