### ISSUE TITLE
[FEAT] Automatic updates should be enabled by default

### ISSUE THREAD

**Issue by spaceoden** [secureblue/secureblue#485]
The rpm-ostreed-automatic.timer and flatpak-user-update.timer are preset to disabled. If we want automatic updates enabled by default, these may need to be active. Some desktop environments provide systems for automatic updates via rpm-ostree and/or flatpak, and may not need the timers.

**Describe the benefit this feature would provide to the project**
Automatic updates or at least update checks appear to be the norm for PCs. I'd wager most users expect them to be enabled by default.

**Describe the solution you'd like**
I recommend simply enabling said timers on all images. On certain desktops it may be redundant, and may preempt some of the features of said desktops, but it would make certain updates are occurring regularly.

**Describe alternatives you've considered**
Images whose desktops do not already provide automatic update checks (and execution or notification) for rpm-ostree and/or flatpak should ship with the rpm-ostreed-automatic.timer and/or flatpak-user-update.timer enabled. It would be vital to verify which desktops reliably provide automatic updates for both rpm-ostree and flatpak.

**Declaration**
- [x] I declare that I have read the README and my feature request is in-scope.

**Comment by RoyalOughtness** [comment]
We install ublue updates services from config already. What gaps are you seeing?

**Comment by spaceoden** [comment]
The rpm-ostreed-automatic.timer and flatpak-user-update.timer are both preset disabled. In order to enable automatic updates these need to be enabled (except in DEs which offer automatic updates).

The `ujust toggle-updates` command allows users to conveniently enable both of them. Perhaps yafti should offer to run it, or at least it should be added to the post-install instructions.

My initial issue mistakenly suggested the flatpak-user-update.timer was missing, but that was a mistake on my part. I also assumed the move away from uBlue caused the default to them being disabled, but that's not the only possible explanation.

**Comment by RoyalOughtness** [comment]
Let me pull up a fresh VM. Regardless we can force enable all of them in the build

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/b66a70eb600f002c08586c9ccf6c2a24c8607249
