### ISSUE TITLE
[FEAT] LibreWolf browser instead of hardened-chromium

### ISSUE THREAD

**Issue by Bammede** [secureblue/secureblue#494]
**Describe the benefit this feature would provide to the project**
LibreWolf which is hardened Firefox, works well on Wayland with NVidia.

**Describe the solution you'd like**
LibreWolf browser instead of hardened-chromium

**Describe alternatives you've considered**
LibreWolf is the good choice

**Declaration**
I declare that I have read the README and my feature request is in-scope.

**Comment by RoyalOughtness** [comment]
Firefox and derivatives are leagues behind anything chromium-based, security wise. They are therefore out of scope. If you care about browser security, you should be using something chromium-based. chromium's site isolation is far more complete, and the chromium sandboxing is much stronger.

**Comment by RoyalOughtness** [comment]
@Bammede are you having issues with wayland/nvidia/chromium?

If so there are easy ways to get it working, usually. Please let me know

**Comment by Bammede** [comment]
Nvidia 1050, wayland, hardened-chromium not running.

if Xwayland is the solution (x11 is not secured) then LibreWolf is the only workaround.

**Comment by RoyalOughtness** [comment]
@Bammede is this a laptop or a desktop?

**Comment by RoyalOughtness** [comment]
also, does it work if you run `chromium-browser --ozone-platform=wayland`?

**Comment by Bammede** [comment]
it is laptop
`chromium-browser --ozone-platform=wayland` open the app and run very slowly.

**Comment by RoyalOughtness** [comment]
> it is laptop `chromium-browser --ozone-platform=wayland` open the app and run very slowly.

what does `chrome://gpu` show? and what do you mean by very slowly?

**Comment by RoyalOughtness** [comment]
also @Bammede what image are you on?

**Comment by Anonymo** [comment]
One thing I don't like about Librewolf is that they stripped out the Firefox sync.

**Comment by Bammede** [comment]
I don't know what happened, but Hardened Chromium works fine with Nvidia now.
