### ISSUE TITLE
[BUG] Issue with MOTD after rebasing.

### ISSUE THREAD

**Issue by AfterHistory** [secureblue/secureblue#517]
****Describe** the bug**
After rebasing from bluefin-nvidia:stable to secureblue silverblue nvidia hardened, The MOTD stopped working, instead it write this out: sed: -e expression #2, char 16: unknown option to `s' 

**To Reproduce**
1. open the terminal with MOTD toggled on

**Expected behavior**
The configured MOTD shows up.

**Actual behavior**
![Image](https://github.com/user-attachments/assets/105d8bd2-4207-48f5-b3c4-434487d993e3)

**Your current image**
 - ![Image](https://github.com/user-attachments/assets/5373e550-df6d-48b3-ada6-4cab45c02aca)

**If you're using a secureblue Bluefin image**
 No, i am using pure silverblue

**Comment by RoyalOughtness** [comment]
Resolved in discord, needs the `:latest` tag
