### ISSUE TITLE
Electron apps: layering vs flatpak'ing?

### ISSUE THREAD

**Issue by PerAstraAdDeum** [secureblue/secureblue#548]
Hi there,

sorry if noob question.

From what I've gathered Flatpaks can actually worsen the inbuilt security measure of Electron apps. If that is correct, what would be the recommended way of installing apps like FreeTube, Signal-Desktop or Element-Desktop?

Should I install them via Flatpak or layer them on top of the system?

Thanks in advance!

**Comment by TheHooly** [comment]
Many Electron apps don't use the built-in sandbox to begin with. At the very least Discord and FreeTube don't.

**Comment by PerAstraAdDeum** [comment]
> Many Electron apps don't use the built-in sandbox to begin with. At the very least Discord and FreeTube don't.

Thank your for the information! So how did you install e.g. FreeTube then? Just via Flatpak?

**Comment by RoyalOughtness** [comment]
I'd use flatpak if I absolutely had to use electron, but you should avoid it as much as possible (ideally you shouldn't use electron at all).


https://github.com/secureblue/secureblue/blob/live/docs/FAQ.md#should-i-use-electron-apps-why-dont-they-work-well-with-hardened_malloc

And definitely do not use the Signal electron app if you care at all about security.

For freetube, there are alternatives like https://flathub.org/apps/de.schmidhuberj.tubefeeder

**Comment by PerAstraAdDeum** [comment]
> I'd use flatpak if I absolutely had to use electron, but you should avoid it as much as possible (ideally you shouldn't use electron at all).
> 
> https://github.com/secureblue/secureblue/blob/live/docs/FAQ.md#should-i-use-electron-apps-why-dont-they-work-well-with-hardened_malloc
> 
> And definitely do not use the Signal electron app if you care at all about security.
> 
> For freetube, there are alternatives like https://flathub.org/apps/de.schmidhuberj.tubefeeder

The part about Signal hits hard. :-D 
What alternative is there on Secureblue? The same  guy that develops Pipeline apparently develops a Signal alternative as well, yet he states that in the current state his app may very well worsen security compared to the official electron app.

**Comment by RoyalOughtness** [comment]
I wouldn't use signal at all on desktop.

**Comment by PerAstraAdDeum** [comment]
> I wouldn't use signal at all on desktop.

.... sadly not an option. Took me ages to convince friends and family to ditch WhatsApp. If now I tell them to stop using Signal on desktop they'd probably just go back to WhatsApp. :-/

I guess I'll stick to the official Signal-App on Flathub. How bad can it be?

**Comment by ghost** [comment]
> I wouldn't use signal at all on desktop.

Even in a VM?

**Comment by RoyalOughtness** [comment]
> > I wouldn't use signal at all on desktop.
> 
> Even in a VM?

yes

**Comment by Squisho82** [comment]
> > > I wouldn't use signal at all on desktop.
> > 
> > 
> > Even in a VM?
> 
> yes

Hello, I have been wondering, how does using a hardened fork of Signal (Molly) via Waydroid compare in security to using the official Electron app? Both Signal and Molly both allow you to use the Android app as a linked device. 
I could imagine Waydroid's security could be the question here, though I'm sure the isolation would still be better?

**Comment by RoyalOughtness** [comment]
@Squisho82 Please direct informational questions to the Discord instead of resurrecting two year old closed issues.
