### ISSUE TITLE
secureblue org copr account for consistency

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#56]

**Comment by RoyalOughtness** [comment]
https://copr.fedorainfracloud.org/coprs/secureblue/

Existing coprs need to be replaced

**Comment by boredsquirrel** [comment]
What about external repositories like Brave? Should they be built on COPR (sucking their resources) or outsourced?

https://github.com/trytomakeyouprivate/braveinstall-fedora-atomic

**Comment by RoyalOughtness** [comment]
> What about external repositories like Brave? Should they be built on COPR (sucking their resources) or outsourced?
> 
> https://github.com/trytomakeyouprivate/braveinstall-fedora-atomic

We won't be adding brave to this project at least for now, but when a project provides an official repo for an rpm there's no need to use copr.
