### ISSUE TITLE
"setup-kdeconnect" just command

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#57]
This would be a setup of different scripts for layering and moderately securing KDE connect and related firewall settings.

Goal is to make it more accessible and not take one of KDEs coolest Feature, that works over Wifi only and allows you do use your GrapheneOS phone as a remote. Just assume that is safe enought to support an opt-in feature.

**Comment by boredsquirrel** [comment]
[Bug report](https://bugs.kde.org/show_bug.cgi?id=417615)
[Discussion](https://discuss.kde.org/t/how-to-disable-kde-connect/7686)

It seems there is also a way to disable KDE Connect, the issue is at least known. Having it disabled, same with cups, and not uninstalled could make the choice easier

**Comment by firefoxlover** [comment]
```
>> ls /etc/xdg/autostart/
org.kde.kdeconnect.daemon.desktop
org.kde.plasma-welcome.desktop
geoclue-demo-agent.desktop
org.kde.discover.notifier.desktop
vboxclient.desktop
spice-vdagent.desktop
vmware-user.desktop
```

Removing these files will stop the services from autostarting. Users can still add them in their user ~/.config/autostart if they wish to.

This does not only apply to kdeconnect but okay

**Comment by boredsquirrel** [comment]
```
>> ls /etc/xdg/autostart/
org.kde.kdeconnect.daemon.desktop
org.kde.plasma-welcome.desktop
geoclue-demo-agent.desktop
org.kde.discover.notifier.desktop
vboxclient.desktop
spice-vdagent.desktop
vmware-user.desktop
```

Removing these files will stop the services from autostarting. Users can still add them in their user ~/.config/autostart if they wish to

This does not only apply to kdeconnect but okay

**Comment by RoyalOughtness** [comment]
This is being [worked on upstream](https://bugs.kde.org/show_bug.cgi?id=417615), butas of now there's no clean way to enable/disable kdeconnectd since it's not a systemd service.

In the meantime you can just layer back kdeconnect if you need it.

**Comment by boredsquirrel** [comment]
yes afaik its as simple as creating an empty desktop entry for kdeconnectd in the autostart. Such a just file could include the layering though, for the time where there is no clean solution. and the `remove kdeconnect` would unlayer it repectively.

I dont find the time currently, and the new layout has changed a bit, but when I find it I will try to create some just commands and we can see.

**Comment by RoyalOughtness** [comment]
> Such a just file could include the layering though

That would be very messy. The goal should be to include kde connect in all kinoite images but have it disabled by default. This requires changes to the image, not a just command.
