### ISSUE TITLE
[BUG] After removing Brew, errors in terminal

### ISSUE THREAD

**Issue by Bammede** [secureblue/secureblue#572]
**Describe the bug**
After uninstalling Brew, link errors related to Brew's `completions` and settings are shown in bash/fish shells.

**To Reproduce**
1. Use Fish Shell on Fedora Silverblue image
2.  Remove Brew
3. Open the Console to see errors

**Comment by RoyalOughtness** [comment]
We take a dependency on brew and it's built into the profile.d.

You can remove it, but it's not supported. Breakage is to be expected. Especially now that we're going to be installing brew packages by default.
