### ISSUE TITLE
[Question] Is it recommended to use an app rather than a website for a service that implements encryption?

### ISSUE THREAD

**Issue by ghost** [secureblue/secureblue#576]
I read [this discussion](https://github.com/secureblue/secureblue/issues/193) and I'm unsure what the best option would be in the following cases, or if it would even matter:

I'll be referring to MacOS sandboxed apps but same concept can apply to flatpaks.

WhatsApp has a native, sandboxed, MacOS app.

Bitwarden has a sandboxed MacOS app based on Electron.

Both services deal with encryption and both services have a website. Both applications are non-reproducible as well.

Would it make sense to use the WhatsApp application over the website despite the non-reproducability aspect?

Similarly, would it make sense to avoid the Bitwarden application and just use the website as the application is based on Electron anyway?

Thanks in advance!

(I would have asked on Discord but I don't have an account)

**Comment by RoyalOughtness** [comment]
> non-reproducible 

what do you mean by this? fedora itself isn't reproducible, so this doesn't make much sense.

> despite the non-reproducability aspect?

I don't know what this means

> Similarly, would it make sense to avoid the Bitwarden application and just use the website as the application is based on Electron anyway?

that's what I'd do

**Comment by ghost** [comment]
> I don't know what this means
> 
> >

I was referring to your reply in the discussion I linked previously:

>How do you know the native app is actually only running native code? What if it's pulling and running js? The whole point of concern, as I already stated, comes back to not having reproducible builds, which is a genuine issue. It's just not at all specific to webapps.

I meant that the WhatsApp application on MacOS does not have a reproducible build so I cannot guarantee that it is running only native code and is not using javascript to handle the encryption.

In that case my assumption would be that it would not matter if I use the WhatsApp application or the website, correct?

**Comment by ghost** [comment]
> > Similarly, would it make sense to avoid the Bitwarden application and just use the website as the application is based on Electron anyway?
> 
> that's what I'd do

Would it also be easier for a malicious server to target me in this case rather than using the app?
