### ISSUE TITLE
[DOCS] 404 error in link found on `USERNS.md`

### ISSUE THREAD

**Issue by ghost** [secureblue/secureblue#578]
> Ultimately we leave both options available because it's a tradeoff and neither is demonstrably preferable from a security standpoint. It should also be noted that podman, toolbox, and distrobox require unprivileged user namespaces to function and are therefore [removed in the non-userns images](https://github.com/secureblue/secureblue/blob/live/recipes/common/disableuserns-packages.yml).

**Comment by RoyalOughtness** [comment]
we need a markdown linter that also validates all markdown urls don't 404

**Comment by ghost** [comment]
It seems like [this](https://github.com/secureblue/secureblue/blob/live/recipes/common/disableuserns-modules.yml) is what it should link to. However, I don't see podman and distrobox being removed. Is the documentation outdated and they do not require user namespaces anymore?

**Comment by RoyalOughtness** [comment]
no, it's correct. 

it's just not exactly the right wording. it's not so much that they're removed as they are not included to begin with
