### ISSUE TITLE
server edition

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#58]
- no gui
- no yafti
- include sshd and harden it

**Comment by boredsquirrel** [comment]
big focus on getting podman to work. Also using podman as a replacement for `docker-compose` is not completely self explanatory, and with the hardening probably involves more steps.

https://github.com/containers/podman/blob/main/docs/tutorials/socket_activation.md

**Comment by RoyalOughtness** [comment]
> big focus on getting podman to work. Also using podman as a replacement for `docker-compose` is not completely self explanatory, and with the hardening probably involves more steps.
> 
> https://github.com/containers/podman/blob/main/docs/tutorials/socket_activation.md

Getting podman working is not related to creating a server edition.

**Comment by boredsquirrel** [comment]
modern servers, especially CoreOS (which is the origin of rpm-ostree) use Docker and Podman nearly exclusively? That is why for sure I expected that to be a requirement

**Comment by RoyalOughtness** [comment]
> modern servers, especially CoreOS (which is the origin of rpm-ostree) use Docker and Podman nearly exclusively? That is why for sure I expected that to be a requirement

docker is still available and can be installed by layering.

**Comment by boredsquirrel** [comment]
and docker is working without user namespaces??? that would be interesting

**Comment by RoyalOughtness** [comment]
> and docker is working without user namespaces??? that would be interesting

In rootless mode I believe it does, but I haven't tested it.

In any case it's not relevant to this ticket as there are server use cases that don't use either podman or docker. Having them would be nice, but they're not hard requirements.
