### ISSUE TITLE
audit failure: flatpak access to inter-process communications

### ISSUE THREAD

**Issue by Bammede** [secureblue/secureblue#583]
It is not an issue, but It may be good place to ask.

I run the Audit on Fedora Silverblue.

I think all my flatpaks have enabled "inter-process communications access" by default. What IPC do, is it necessary for flatpaks?

Why the audit shows failure to "Ensuring no authselect overrides" as I haven't do any manual changes to PAM etc.

**Comment by RoyalOughtness** [comment]
>  What IPC do, is it necessary for flatpaks?

iirc it gets used to improve xorg integration, @TheHooly knows more about this I believe?

> Why the audit shows failure to "Ensuring no authselect overrides" as I haven't do any manual changes to PAM etc.

You can ignore it for now, it will go away once this merges: https://github.com/secureblue/secureblue/pull/580

**Comment by TheHooly** [comment]
> > What IPC do, is it necessary for flatpaks?
> 
> iirc it gets used to improve xorg integration, [@TheHooly](https://github.com/TheHooly) knows more about this I believe?
> 
It's required for Xorg's shared memory extension, i.e. hardware accelerated rendering under Xorg/XWayland. It's not required per se, especially with native Wayland clients, but performance of X11 clients without this permission will suffer.
