### ISSUE TITLE
[FEAT] break up monolithic justfile into smaller, categorized files

### ISSUE THREAD

**Issue by secretmango** [secureblue/secureblue#589]
**Describe the benefit this feature would provide to the project**
the ujust files are beginning to become pretty messy. Having such spaghetti code just makes no sense, also needing the additional "ujust" in the command is strange.

**Describe the solution you'd like**
Convert all commands to individual scripts that are placed in a system dir and sourced by default in bash.
They could be named `just-name` or just `name`.

**Describe alternatives you've considered**
Using ujust as it is.

**Declaration**
- [x] I declare that I have read the README and my feature request is in-scope.

**Comment by RoyalOughtness** [comment]
this is sort of related to https://github.com/secureblue/secureblue/issues/478

but yes, essentially I'll be pulling in everything from ublue-os/config that we actually use, leaving out stuff we don't, and dropping it directly into the repo

`ujust` itself is pretty minimal and not-spaghetti: <https://github.com/ublue-os/config/blob/main/build/ublue-os-just/lib-ujust/ujust.sh>

Can you link to a specific example of 🍝 ? 😄

**Comment by secretmango** [comment]
interesting, didnt think of that but yes for sure that too

the ujust utility may not need to be removed, but having separate just configfiles and a main just config pointing at all of them might be unneeded?

I am mainly talking about the single, quite large ujust file that I just did a PR on, which contains various things not related to each other.

Having these in separate scripts would make much more sense, be more readable etc.

**Comment by hassanalmasry457** [comment]
****, klmkkj 
lssggihj
blatyu
molto \
/\ <sshhaahhedd

**Comment by RoyalOughtness** [comment]
> but having separate just configfiles and a main just config pointing at all of them might be unneeded?

> I am mainly talking about the single, quite large ujust file that I just did a PR on, which contains various things not related to each other.

These seem contradictory 😄 

You're saying we don't need separate justfiles, but also that having a monolithic justfile should be split up. These are opposites

I agree that we could split up the big justfile into smaller files that group the commands into relevant categories. I can do that when i split up ublue-os/config

**Comment by secretmango** [comment]
no they are not contradictory. Afaik a central justfile needs to source all the individual files.

I think having separate scripts for every thing would be best, but grouping would for sure be an improvement
