### ISSUE TITLE
Create Roadmap

### ISSUE THREAD

**Issue by wandapeter** [secureblue/secureblue#6]
Hi!

I like the rebranding. Like before, i am interested in contributing to this project. I understand as of now the feature list is not fully implmented. would it be possible to create a roadmap, or at least indicate which features are not implemented yet?

Thanks!

**Comment by RoyalOughtness** [comment]
Here you go 

https://github.com/orgs/secureblue/projects/1

**Comment by RoyalOughtness** [comment]
If you have any additional ideas for improved hardening or other changes, feel free to open new issues for discussion.

**Comment by RoyalOughtness** [comment]
@34N0 I assigned you https://github.com/orgs/secureblue/projects/1/views/1?pane=issue&itemId=45480680 as it appears you're already working on it
