### ISSUE TITLE
[FEAT] audit: no suid binaries

### ISSUE THREAD

**Issue by q-b** [secureblue/secureblue#619]
**Describe the benefit this feature would provide to the project**
No root suid is great ! #296
Ability to audit  that the OS remains that way would be welcome :)

**Describe the solution you'd like**
A check in `ujust audit-secureblue` to ensure that `pkexec`, `sudo` etc. are at least not installed (not present would be better but let's start with a simple implementation)

**Declaration**
- [x] I declare that I have read the README and my feature request is in-scope.

**Comment by RoyalOughtness** [comment]
suid isn't fully removed yet :), also this would be better off by simply mounting the entire filesystem as `nosuid`, once it's possible

**Comment by RoyalOughtness** [comment]
#296 dup
