### ISSUE TITLE
rebase to signed broken

### ISSUE THREAD

**Issue by wandapeter** [secureblue/secureblue#62]
the last merge broke rebasing to signed image.

something never occured in development because local builds were never signed.

```
dev@fedora:~$ rpm-ostree rebase ostree-image-signed:docker://ghcr.io/secureblue/silverblue-main-hardened:latest
...
Resolving dependencies... done
Checking out packages... done
error: Checkout bubblewrap-0.8.0-1.fc39.x86_64: Hardlinking 56/2a777238074b750bac4dd0fb6634ea62eae17e2f6869a912d42ca380d713fe.file to bwrap: File exists
```

**Comment by RoyalOughtness** [comment]
is it just signed, or does rebase to ostree-unverified-registry... also fail?

The error doesn't look signing related

**Comment by wandapeter** [comment]
No the initial rebase works as expected. the second rebase to signed fails

**Comment by RoyalOughtness** [comment]
> No the initial rebase works as expected. the second rebase to signed fails

if you rebase to a different unsigned secureblue image, I'm guessing it will also fail. Seems to be something to do with the bubblewrap-suid rpm itself

**Comment by RoyalOughtness** [comment]
as in it's conflicting with itself once installed once

**Comment by wandapeter** [comment]
yes.

It's not the only file with the permissions and ownership in `/usr/bin` so `rpm-ostree` does not have problems with that.

The same error happens when running `rpm override remove bubblewrap` or `rpm override remove bubblewrap-suid`. 

This might be `rpm-ostree` related?

**Comment by RoyalOughtness** [comment]
> yes.
> 
> It's not the only file with the permissions and ownership in `/usr/bin` so `rpm-ostree` does not have problems with that.
> 
> The same error happens when running `rpm override remove bubblewrap` or `rpm override remove bubblewrap-suid`.
> 
> This might be `rpm-ostree` related?

FYI I am unable to reproduce this. I'm guessing it's related to residual artifacts from your local testing?

**Comment by wandapeter** [comment]
unable to reproduce on a fresh VM
