### ISSUE TITLE
[FEAT] make install script detect and process signed secureblue images

### ISSUE THREAD

**Issue by target6404** [secureblue/secureblue#626]
**Describe the benefit this feature would provide to the project**
Currently `install_secureblue.sh` always rebases to unsigned. If the current image is signed secureblue, this is undesirable. The change would make the install script useable for easily switching to different secureblue images (switching DE, configuring USERNS) without other manual input.

**Describe the solution you'd like**
Make `install_secureblue.sh` check whether the current image is signed secureblue and, if it is, rebase to signed.

**Describe alternatives you've considered**
`rpm-ostree rebase` to different secureblue images manually.

**Declaration**
- [x] I declare that I have read the README and my feature request is in-scope.

**Comment by target6404** [comment]
Another potential option: make a `ujust` version of the script, specifically for rebasing secureblue->secureblue

**Comment by spaceoden** [comment]
`wget https://github.com/secureblue/secureblue/releases/latest/download/install_secureblue.sh && sed -i 's,ostree-unverified-registry:,ostree-image-signed:docker://,g' install_secureblue.sh && bash install_secureblue.sh && rm install_secureblue.sh`
This downloads the install script, swaps the unsigned part of the rebase command with the signed version, runs it, then deletes it.
