### ISSUE TITLE
Custom ISO

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#63]
- [ ] fork ublues Installer
- [ ] modify its resources
- [ ] change the branding everywhere
- [ ] add custom icon
- [ ] advertise it on the Readme
- [ ] have an eye on the Anaconda WebUI release

**Comment by RoyalOughtness** [comment]
There is an iso generation action but I currently have it disabled as the ublue iso is not fully mature. The recommended way is to rebase from vanilla silverblue/kinoite, which is more reliable at this point.
