### ISSUE TITLE
[FEAT] Configure Flatpak default global permissions

### ISSUE THREAD

**Issue by ShadowSlayer1441** [secureblue/secureblue#634]
**Describe the benefit this feature would provide to the project**
Flatpak by default grants many unnecessary permissions ujust audit even shows this, and asks us to manually fix it. This proposed change will create much more secure defaults, which people can configure with flatseal as desired.

**Describe the solution you'd like**
Have the setup script edit "~/.local/share/flatpak/overrides/global" (from main user home directory)

And replace it with:
```
[Context]
shared=!ipc;!network
sockets=!gpg-agent;!cups;!pcsc;!ssh-auth;!system-bus;!session-bus;!pulseaudio;!fallback-x11;!x11;!inherit-wayland-socket
devices=!all;!shm;!kvm;!input
features=!per-app-dev-shm;!canbus;!bluetooth;!multiarch;!devel
filesystems=host-os:ro;!home;!host-etc;!host

[Environment]
LD_PRELOAD=/var/run/host/usr/lib64/libhardened_malloc.so

[System Bus Policy]
org.freedesktop.Avahi.*=none
org.freedesktop.login1=none
org.freedesktop.NetworkManager=none
org.freedesktop.UPower=none
org.freedesktop.UDisks2=none

[Session Bus Policy]
org.a11y.Bus=none
org.freedesktop.impl.portal.PermissionStore=none
org.freedesktop.Flatpak=none
org.freedesktop.FileManager1=none
org.freedesktop.Notifications=none
org.freedesktop.PowerManagement=none
org.freedesktop.ScreenSaver=none
org.freedesktop.secrets=none
org.gnome.SessionManager=none
org.gnome.SettingsDaemon=none
org.gnome.SettingsDaemon.MediaKeys=none
org.gnome.Software=none
org.gtk.vfs.*=none
org.kde.*=none
org.kde.kconfig.notify=none
org.kde.KGlobalSettings=none
org.kde.kwalletd5=none
org.kde.StatusNotifierWatcher=none
com.canonical.AppMenu.Registrar=none
com.canonical.indicator.application=none
com.canonical.Unity=none
com.canonical.Unity.LauncherEntry=none
```

**Describe alternatives you've considered**
Other variants of of the config above (created by Rootkit404 from discord) could certainly work, but generally a better default global flatpak should definitely be implemented.

**Declaration**
- [ +] I declare that I have read the README and my feature request is in-scope.

**Comment by RoyalOughtness** [comment]
dup https://github.com/secureblue/secureblue/issues/125
