### ISSUE TITLE
[FEAT] ujust install-steam

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#639]
should present the user with the following choices:

1. add the flathub remote and install the steam flatpak, then unset the hardened_malloc var
2. install the bazzite distrobox and export steam
2. install negativo and layer steam

**Comment by target6404** [comment]
The recipe should be called install-steam or steam-setup, not install-secureblue

**Comment by spaceoden** [comment]
I recommend we create a separate ujust command to add (or swap to) the unverified flathub remote, in case users want it for apps other than steam. This install-steam command could then invoke the unverified flathub ujust command.

**Comment by RoyalOughtness** [comment]
@spaceoden fine by me! I think it should be an addition, not a swap. 

maybe also an install-negativo ujust command that can be invoked if users choose the steam rpm option

also @spaceoden are you working on this? if so I'll assign the issue to you

**Comment by spaceoden** [comment]
@RoyalOughtness yeah I started, and self-assigned. Can you clarify your proposed install-negativo command? My WIP install-steam script only enables the negativo Steam repo. I don't see any benefit to abstracting that to a separate ujust command, given the Steam repo is focused solely on Steam.

**Comment by RoyalOughtness** [comment]
@spaceoden ah right, i forgot negativo has a separate steam repo. nevermind then, that works fine. And thanks for taking this task

Also, this command should --delete-if-present the ia32 karg, and tell the user that it's doing so
