### ISSUE TITLE
Custom Greeting dialogs for GNOME and KDE

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#64]
Both projects offer greeting dialogs that just work by default. If they don't work, you can file bugs upstream.

Both dialogs allowing the creation of custom pages, which can be helpful for explaining the complete concept of this distro.
Images, Screenshots, GIFs can be integrated, as well as links (at least for KDE).

**Comment by RoyalOughtness** [comment]
We can use yafti for this

**Comment by boredsquirrel** [comment]
If upstream Silverblue/Kinoite get customized greeting dialogs for regular problems like installing apps, we should maybe overthink this. Until then, agree

**Comment by RoyalOughtness** [comment]
duplicate of https://github.com/secureblue/secureblue/issues/65
