### ISSUE TITLE
Add yafti back

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#65]
- customize branding
- add description of project
- remove system flatpak in favor of user flatpaks

**Comment by boredsquirrel** [comment]
Also maybe maintain a list of "trusted/recommended Flatpak apps"?

But apart from using `flatpak-verified`, recommending "secure software" is difficult for me. Old projects like Libreoffice, GIMP, Calibre, etc. are probably not very secure

**Comment by RoyalOughtness** [comment]
> Also maybe maintain a list of "trusted/recommended Flatpak apps"?

There's no reason to maintain any such list on top of only enabling flathub-verified by default. 

> Old projects like Libreoffice, GIMP, Calibre, etc. are probably not very secure

This is nonsensical for several reasons. For one, old doesn't mean insecure. Two, none of those projects are old. They are all well-maintained.

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/pull/90
