### ISSUE TITLE
flatpak doesn't honor hardened_malloc setting

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#67]
details: https://www.kicksecure.com/wiki/Hardened_Malloc#Flatpak

**Comment by RoyalOughtness** [comment]
@34N0 if you have any ideas on this, let me know. This is high priority for this project now, since users will generally spend a lot of time in flatpak apps, but as-is those apps won't be using hardened_malloc. We need to find a way to by-default run them using hardened_malloc

**Comment by wandapeter** [comment]
This is what happens when i try to preload the malloc manually:

```
flatpak run --env=LD_PRELOAD=/usr/lib64/libhardened_malloc.so org.gnome.Calculator
ERROR: ld.so: object '/usr/lib64/libhardened_malloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

```

It seems like sandbox does not have permissions to open the file. I quickly tried to set the permissoin in flatseal but i am not sure if ```flatpak run``` respects those changes.

Maybe one solution would be to per default allow all flatpak sandboxes access to ```/usr/lib64/libhardened_malloc.so``` and then set ```LD_PRELOAD``` globally?

**Comment by RoyalOughtness** [comment]
> Maybe one solution would be to per default allow all flatpak sandboxes access to `/usr/lib64/libhardened_malloc.so` and then set `LD_PRELOAD` globally?

If you're able to get that working, then yes that would work.

**Comment by wandapeter** [comment]
flatpak sandboxes run on top of flatpak runtimes:

*"Runtimes provide the basic dependencies that are used by applications. Each application must be built against a runtime, and this runtime must be installed on a host system in order for the application to run (Flatpak can automatically install the runtime required by an application). "*

I think the only way to get `libhardened_malloc.so` be able to get loaded by the applications would be to build a custom, hardened runtime. 

The flatpak runtime which is currently used is:

```
Name                    Application ID                    Version        Branch        Installation
Fedora Platform         org.fedoraproject.Platform        39             f39           system
```
The repository of this runtime is https://src.fedoraproject.org/flatpaks/flatpak-runtime

I think the best way would be to build our own flatpak runtime including `libhardened-malloc`and then either somehow force applications to use our runtime with the `--runtime` flag or just place it *inplace* of the default runtime similar to the `bubblewrap-suid` version.

I think i can do it :smile: .

**Comment by RoyalOughtness** [comment]
> flatpak sandboxes run on top of flatpak runtimes:
> 
> _"Runtimes provide the basic dependencies that are used by applications. Each application must be built against a runtime, and this runtime must be installed on a host system in order for the application to run (Flatpak can automatically install the runtime required by an application). "_
> 
> I think the only way to get `libhardened_malloc.so` be able to get loaded by the applications would be to build a custom, hardened runtime.
> 
> The flatpak runtime which is currently used is:
> 
> ```
> Name                    Application ID                    Version        Branch        Installation
> Fedora Platform         org.fedoraproject.Platform        39             f39           system
> ```
> 
> The repository of this runtime is https://src.fedoraproject.org/flatpaks/flatpak-runtime
> 
> I think the best way would be to build our own flatpak runtime including `libhardened-malloc`and then either somehow force applications to use our runtime with the `--runtime` flag or just place it _inplace_ of the default runtime similar to the `bubblewrap-suid` version.
> 
> I think i can do it 😄 .

Let's keep brainstorming unless you're confident in this model. It would be a lot more straightforward to grant flatpaks access to the existing library and then force them to load with it. Is that model not feasible?

**Comment by RoyalOughtness** [comment]
also, i don't think that runtime is the only runtime that apps use, so this wouldn't apply for all applications if I'm not mistaken. So it wouldn't be a complete solution.

**Comment by wandapeter** [comment]
> Let's keep brainstorming unless you're confident in this model. It would be a lot more straightforward to grant flatpaks access to the existing library and then force them to load with it. Is that model not feasible?

So far no luck in testing. Trying it let me to the runtime model. But i am not that confident in it. I like it since it seems scaleable. Maybe we could even harden the runtime further.

**Comment by wandapeter** [comment]
> also, i don't think that runtime is the only runtime that apps use, so this wouldn't apply for all applications if I'm not mistaken. So it wouldn't be a complete solution.

i was under the impression all of the flatpaks in the fedora repo are using this runtime. But yeah this solution probably would not work for installs from for instance flathub.

but we could force the packages to use our runtime with the `--runtime` flag but maybe that will break it.

**Comment by wandapeter** [comment]
but yeah you are right loading the library from outside the sandbox seems the simpler and more applicable solution. Let's just experiment further for now.

**Comment by RoyalOughtness** [comment]
I asked on the kicksecure/whonix forums since they have a thread discussing this: https://forums.whonix.org/t/hardened-malloc-hardened-memory-allocator/7474/207

**Comment by wandapeter** [comment]
We can override the /usr in the runtime with the hosts /usr with the following flag:
```
--usr-path=/usr
```
And then successfully preload the library:
```
flatpak run --usr-path=/usr --env=LD_PRELOAD=/usr/lib64/libhardened_malloc.so org.gnome.Calculator
```
We can edit the Exec command in `/var/lib/flatpak/exports/share/applications/org.gnome.Calculator.desktop` with the two flags.

The question is how to add those flags in every `.desktop` file.

**Comment by wandapeter** [comment]
This script overrides all desktop entries with the flags set and could run on every login. Kinda hacky though :crying_cat_face: 

```bash
#!/bin/bash

source_folder="/var/lib/flatpak/exports/share/applications/"
local_folder="$HOME/.local/share/flatpak/exports/share/applications"

usr_flag="--usr-path=/usr"
env_flag="--env=LD_PRELOAD=/usr/lib64/libhardened_malloc.so"

# local exports is not created initially
mkdir -p "$local_folder"

# foreach .desktop file in source
for desktop_file in "$source_folder"/*.desktop; do
    if [ -f "$desktop_file" ]; then

        # copy .desktop file to local
        filename=$(basename "$desktop_file")
        local_path="$local_folder/$filename"
        cp "$desktop_file" "$local_path"

        # Add flags to the Exec 
        sed -i "/^Exec=/ s|run|run $usr_flag $env_flag|" "$local_path"
    fi
done

# override entries gnome
if command -v update-desktop-database > /dev/null; then
    update-desktop-database
fi

# TODO: override entries kde
```

**Comment by wandapeter** [comment]
with `gnome-calculator` PID being 4142 we can confirm the hardened malloc is loaded:

```bash
dev@fedora:~$ grep /usr/lib64/libhardened_malloc.so /proc/4142/maps
7f15a4445000-7f15a4447000 r--p 00000000 00:1f 212080                     /usr/lib64/libhardened_malloc.so
7f15a4447000-7f15a444c000 r-xp 00002000 00:1f 212080                     /usr/lib64/libhardened_malloc.so
7f15a444c000-7f15a444e000 r--p 00007000 00:1f 212080                     /usr/lib64/libhardened_malloc.so
7f15a444e000-7f15a444f000 r--p 00008000 00:1f 212080                     /usr/lib64/libhardened_malloc.so
7f15a444f000-7f15a4450000 rw-p 00009000 00:1f 212080                     /usr/lib64/libhardened_malloc.so

```

**Comment by RoyalOughtness** [comment]
> We can override the /usr in the runtime with the hosts /usr with the following flag:
> 
> ```
> --usr-path=/usr
> ```
> 
> And then successfully preload the library:
> 
> ```
> flatpak run --usr-path=/usr --env=LD_PRELOAD=/usr/lib64/libhardened_malloc.so org.gnome.Calculator
> ```
> 
> We can edit the Exec command in `/var/lib/flatpak/exports/share/applications/org.gnome.Calculator.desktop` with the two flags.
> 
> The question is how to add those flags in every `.desktop` file.

This is an interesting approach. Thanks for continuing to investigate this! My concerns on this would be similar to those in this thread: https://github.com/flatpak/flatpak/issues/5435#issuecomment-1589911831

In short, we'd be using a sandbox escape (a security degradation) to enable a security improvement, which is somewhat ironic.

Your method has me thinking though, whether it's possible to install hardened malloc somewhere inside the homedir (maybe inside a flatpak itself) and then grant all flatpaks access to that install location. 

Then the command I'm envisioning would look something like this instead:

> flatpak run --filesystem=~/.local/share/flatpak/some/bin/location --env=LD_PRELOAD=.local/share/flatpak/some/bin/location/libhardened_malloc.so org.gnome.Calculator


thoughts?

**Comment by wandapeter** [comment]
Hmm yeah we can just load a local library read-only without exposing /usr. Makes much more sense to only expose the required file.
```bash
flatpak run --filesystem=~/.local/share/flatpak/lib64/libhardened_malloc.so:ro --env=LD_PRELOAD=.local/share/flatpak/lib64/libhardened_malloc.so org.gnome.Calculator 
```
```bash
dev@fedora:~$ grep libhardened_malloc.so /proc/7405/maps
7fe2ff295000-7fe2ff297000 r--p 00000000 00:1f 3494                       /var/home/dev/.local/share/flatpak/lib64/libhardened_malloc.so
7fe2ff297000-7fe2ff29c000 r-xp 00002000 00:1f 3494                       /var/home/dev/.local/share/flatpak/lib64/libhardened_malloc.so
7fe2ff29c000-7fe2ff29e000 r--p 00007000 00:1f 3494                       /var/home/dev/.local/share/flatpak/lib64/libhardened_malloc.so
7fe2ff29e000-7fe2ff29f000 r--p 00008000 00:1f 3494                       /var/home/dev/.local/share/flatpak/lib64/libhardened_malloc.so
7fe2ff29f000-7fe2ff2a0000 rw-p 00009000 00:1f 3494                       /var/home/dev/.local/share/flatpak/lib64/libhardened_malloc.so
```

Since the library is loaded by the sandboxed process i do not think sandboxing the library itself (building it into a flatpak) makes sense.

I could create a COPR which installs the library into `.local/share/flatpak/lib64/`

**Comment by RoyalOughtness** [comment]
@34N0 great to see that that works, however you won't be able to accomplish this with an rpm as it gets built into the image and can't be installed into the user's homedir. I can think of a couple ways around this. One would be to package hardened malloc into a flatpak, but this has drawbacks of being a lot of effort and having two sources for hardened malloc.

Instead, why don't we do something like this: Add a `just` command like `just setup-flatpak-hardened`. This command will do several things:
1. Copy the libhardened malloc.so file to ~/.local
2. setup a systemd hook to automatically re-copy this whenever the rpm is updated
3. use `flatpak override --filesystem=~/.local/share/flatpak/lib64/libhardened_malloc.so:ro  --env=VARIABLE_NAME=VARIABLE_VALUE ` to set hardened malloc for all flatpaks (updating desktop files won't be necessary if this works). From the flatpak docs, it should work:

>  If the application ID APP is not specified then the overrides
>  affect all applications, but the per-application overrides can
>  override the global overrides.

https://man7.org/linux/man-pages/man1/flatpak-override.1.html
 
Once this is working, we can remove all existing flatpak repos so it won't work out of the box, but also add yafti back and prompt the user to setup flatpak. On user input, we can invoke the just command that sets up flatpak in this hardened way.

**Comment by wandapeter** [comment]
Oh yeah earlier i discarded `flatpak override` since it does not support  the `--usr-path` flag. 

Hmm yeah actually seems kinda clean and not that hacky :+1: 

I tested the global override and can confirm the library is getting loaded in runtime with just the default `run` command.

**Comment by wandapeter** [comment]
Ok so are you gonna work on this? I'm interested in working on #16 #17  and #72

**Comment by RoyalOughtness** [comment]
> Ok so are you gonna work on this? I'm interested in working on #16 #17 and #72

I can, sure. Feel free to work on whatever you please!

**Comment by boredsquirrel** [comment]
should this be a just command or fully automated? For example integrated in yafti, if that is possible?

**Comment by RoyalOughtness** [comment]
> Once this is working, we can remove all existing flatpak repos so it won't work out of the box, but also add yafti back and prompt the user to setup flatpak. On user input, we can invoke the just command that sets up flatpak in this hardened way.

As I already said above:

> Once this is working, we can remove all existing flatpak repos so it won't work out of the box, but also add yafti back and prompt the user to setup flatpak. On user input, we can invoke the just command that sets up flatpak in this hardened way.

**Comment by RoyalOughtness** [comment]
> Hmm yeah we can just load a local library read-only without exposing /usr. Makes much more sense to only expose the required file.
> 
> ```shell
> flatpak run --filesystem=~/.local/share/flatpak/lib64/libhardened_malloc.so:ro --env=LD_PRELOAD=.local/share/flatpak/lib64/libhardened_malloc.so org.gnome.Calculator 
> ```
> 
> ```shell
> dev@fedora:~$ grep libhardened_malloc.so /proc/7405/maps
> 7fe2ff295000-7fe2ff297000 r--p 00000000 00:1f 3494                       /var/home/dev/.local/share/flatpak/lib64/libhardened_malloc.so
> 7fe2ff297000-7fe2ff29c000 r-xp 00002000 00:1f 3494                       /var/home/dev/.local/share/flatpak/lib64/libhardened_malloc.so
> 7fe2ff29c000-7fe2ff29e000 r--p 00007000 00:1f 3494                       /var/home/dev/.local/share/flatpak/lib64/libhardened_malloc.so
> 7fe2ff29e000-7fe2ff29f000 r--p 00008000 00:1f 3494                       /var/home/dev/.local/share/flatpak/lib64/libhardened_malloc.so
> 7fe2ff29f000-7fe2ff2a0000 rw-p 00009000 00:1f 3494                       /var/home/dev/.local/share/flatpak/lib64/libhardened_malloc.so
> ```
> 
> Since the library is loaded by the sandboxed process i do not think sandboxing the library itself (building it into a flatpak) makes sense.
> 
> I could create a COPR which installs the library into `.local/share/flatpak/lib64/`

I'm unable to consistently reproduce the functionality you demonstrated here. Generally I see this:

ERROR: ld.so: object '.local/share/flatpak/lib64/libhardened_malloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

**Comment by wandapeter** [comment]
the following steps work on a fresh build:
```bash
dev@fedora:~$ mkdir -p ~/.local/share/flatpak/lib64
dev@fedora:~$ cp /usr/lib64/libhardened_malloc.so  ~/.local/share/flatpak/lib64/
dev@fedora:~$ flatpak run --filesystem=~/.local/share/flatpak/lib64/libhardened_malloc.so:ro --env=LD_PRELOAD=.local/share/flatpak/lib64/libhardened_malloc.so org.gnome.Calculator 
```

**Comment by RoyalOughtness** [comment]
> the following steps work on a fresh build:
> 
> ```shell
> dev@fedora:~$ mkdir -p ~/.local/share/flatpak/lib64
> dev@fedora:~$ cp /usr/lib64/libhardened_malloc.so  ~/.local/share/flatpak/lib64/
> dev@fedora:~$ flatpak run --filesystem=~/.local/share/flatpak/lib64/libhardened_malloc.so:ro --env=LD_PRELOAD=.local/share/flatpak/lib64/libhardened_malloc.so org.gnome.Calculator 
> ```

So strange that we're seeing different behavior. Does this work for you for any flatpak or just gnome calculator? Can you try with say gwenview or vscodium?

**Comment by wandapeter** [comment]
Rally strange. I'm testing on a snapshot which is just a fresh silverblue install and then rebased to the latest hardened image.

>  Can you try with say gwenview or vscodium?

Both working.

You can use the `--command` flag to spawn a shell inside the sandbox. Can you check if the library is actually there? Iirc this error can also mean the library is nout found.

Spawning a shell inside a gwenview sandbox:

```bash
flatpak run --filesystem=~/.local/share/flatpak/lib64/libhardened_malloc.so:ro --env=LD_PRELOAD=.local/share/flatpak/lib64/libhardened_malloc.so --command=sh org.kde.gwenview 
```

**Comment by RoyalOughtness** [comment]
@34N0 it's probably something on my side. I need to figure out what exactly that is. In the meantime since it's working for you, do you mind checking:

- does it still work with the override (instead of setting it in each `flatpak run`)?
- do a variety of popular apps work? Discord, steam, telegram, gimp, signal, etc?
- if any of them break, do they work with hardened_malloc-light?

**Comment by wandapeter** [comment]
> does it still work with the override (instead of setting it in each flatpak run)?

Can confirm.

> do a variety of popular apps work? Discord, steam, telegram, gimp, signal, etc?

I should be able to find the time tomorrow :smile:

**Comment by RoyalOughtness** [comment]
> I should be able to find the time tomorrow 😄

I setup a fresh testing environment and now it's working for me for most apps I tested, except for steam, vscodium, and discord. They still run but ignore hardened malloc. 

I think this is still worth pursuing even though it's not going to apply to all flatpak apps. Some is better than none.

**Comment by adrelanos** [comment]
Try reporting this upstream at flatpak for a solution in or some insights by upstream?

**Comment by RoyalOughtness** [comment]
> ```shell
> LD_PRELOAD=
> ```

I think I found a solution but I'm not celebrating just yet. It addresses all of the concerns you both have raised @adrelanos @34N0 

```
flatpak override --filesystem=/var/run/host/usr/lib64/libhardened_malloc.so:ro  --env=LD_PRELOAD=/var/run/host/usr/lib64/libhardened_malloc.so
```

then when I run gwenview it shows it as loaded:

```
grep hardened /proc/5451/maps
...    /run/host/usr/lib64/libhardened_malloc.so
```

Please confirm that this works for you as well!

**Comment by RoyalOughtness** [comment]
One additional note on the above method is that it was only working for Gwenview because by default it gets `filesystem=host`.

So this part was having no effect:

```
--filesystem=/var/run/host/usr/lib64/libhardened_malloc.so:ro
```

But this part does work:

```
 --env=LD_PRELOAD=/var/run/host/usr/lib64/libhardened_malloc.so
```

so long as I set either

```
filesystem=host
```

or 

```
filesystem=host-os
```

**Comment by RoyalOughtness** [comment]
It looks like granting 

```
host-os:ro
```

would give all flatpaks readonly access to just /usr. Setting ro is redundant on immutable distros anyways.

According to this thread, sharing subsets of /usr is not possible: https://github.com/flatpak/flatpak/issues/5575#issuecomment-1791018132

So now the question is, which is a better security default:

- using flatpaks without hardened_malloc
- using flatpaks with hardened_malloc but with ro access to /usr

@34N0 @adrelanos thoughts?

**Comment by wandapeter** [comment]
> According to this thread, sharing subsets of /usr is not possible: https://github.com/flatpak/flatpak/issues/5575#issuecomment-1791018132

In theory underlying Bubblewrap does support binding only `/usr/lib64` 
https://wiki.archlinux.org/title/Bubblewrap/Examples

Maybe in the long term this should be implemented upstream. 

In my understanding of flatpak, the app requests its default permission? 
`flatpak build --filesystem=host-os ...`
So wouldn't a malicious app which wants access to the hosts `/usr` already have the permission anyways? (one of the flaws of flaptak and why manually managing permissions with i.e. flatseal is important)

So maybe the negative impact of exposing `/usr` per default is minimal.
What do you guys think? I am just brainstorming.

**Comment by RoyalOughtness** [comment]
> Maybe in the long term this should be implemented upstream.

That would be good, yes

> In my understanding of flatpak, the app requests its default permission? `flatpak build --filesystem=host-os ...` 

No, host-os is not default. Open any app in flatseal and more than likely host-os will be disabled by default.

> So maybe the negative impact of exposing `/usr` per default is minimal. 

I'm inclined to agree, but it's a shame that this can't be accomplished without a significantly more narrow hole in the sandbox. I need to think about this some more.

**Comment by RoyalOughtness** [comment]
Notified upstream: https://github.com/flatpak/flatpak/issues/5575#issuecomment-1837706101

**Comment by adrelanos** [comment]
qoijjj:
> Notified upstream: https://github.com/flatpak/flatpak/issues/5575#issuecomment-1837706101
> 

Easily overlooked / ignored in an already closed ticket about something 
else.

This would be better if a separate ticket discussing hardened malloc 
directly or more generally how to have ld preload's honored by flatpak 
applications.

**Comment by RoyalOughtness** [comment]
> Easily overlooked / ignored in an already closed ticket about something else. This would be better if a separate ticket discussing hardened malloc directly or more generally how to have ld preload's honored by flatpak applications.

https://github.com/flatpak/flatpak/issues/5617

**Comment by adrelanos** [comment]
This is much better. Thank you!

Last option coming to mind on how to phrase this as a request for upstream would be to a feature request against flathub to package hardened malloc as a flatpak.

https://discourse.flathub.org/c/requests/5

**Comment by RoyalOughtness** [comment]
> This is much better. Thank you!
> 
> Last option coming to mind on how to phrase this as a request for upstream would be to a feature request against flathub to package hardened malloc as a flatpak.
> 
> https://discourse.flathub.org/c/requests/5

Here you go: https://discourse.flathub.org/t/flatpak-request-for-hardened-malloc/5593

Please add additional details if you see fit.

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/pull/90

**Comment by RoyalOughtness** [comment]
> This is much better. Thank you!
> 
> Last option coming to mind on how to phrase this as a request for upstream would be to a feature request against flathub to package hardened malloc as a flatpak.
> 
> https://discourse.flathub.org/c/requests/5

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1680

**Comment by ByteCorum** [comment]
Good day, I don’t know how relevant it is now but I think I’ve found a way to preload the `libhardened_malloc.so` into a flatpak without opening a huge hole in the sandbox. If you have found a better solution or I'm wrong please tell me.

Here is my approach:
1. I decided to put `libhardened_malloc.so` in `/opt/hardened_malloc/` dir, as this doesn't conflict with flatpak dirs and preferences.
2. I've protected `/opt/hardened_malloc/`  and `libhardened_malloc.so`  with mod `755` and `644` accordingly and added an immutability bit to `libhardened_malloc.so` 
3. Set the auto-update up using a pacman hook  <- cannot be used in Fedora, but ig it should have smt similar

So than when I start app e.g. Gnome Calculator
```
$ flatpak run \
  --filesystem=/opt/hardened_malloc/:ro \
  --env=LD_PRELOAD=/opt/hardened_malloc/libhardened_malloc.so \
  org.gnome.Calculator
```

You can see here its loaded
```
$ flatpak run --filesystem=/opt/hardened_malloc/:ro --env=LD_PRELOAD=/opt/hardened_malloc/libhardened_malloc.so --command=sh  org.gnome.Calculator -c "cat /proc/self/maps | grep hardened"
7f801062b000-7f801062d000 r--p 00000000 00:23 645135                     /opt/hardened_malloc/libhardened_malloc.so
7f801062d000-7f8010633000 r-xp 00002000 00:23 645135                     /opt/hardened_malloc/libhardened_malloc.so
7f8010633000-7f8010635000 r--p 00008000 00:23 645135                     /opt/hardened_malloc/libhardened_malloc.so
7f8010635000-7f8010636000 r--p 00009000 00:23 645135                     /opt/hardened_malloc/libhardened_malloc.so
7f8010636000-7f8010637000 rw-p 0000a000 00:23 645135                     /opt/hardened_malloc/libhardened_malloc.so
```

Output with `LD_DEBUG=libs`
```
$ export LD_DEBUG=libs
$ flatpak run --filesystem=/opt/hardened_malloc/:ro --env=LD_PRELOAD=/opt/hardened_malloc/libhardened_malloc.so org.gnome.Calculator > output 2>&1
$ grep hardened output
         2:	calling init: /opt/hardened_malloc/libhardened_malloc.so
         2:	calling fini: /opt/hardened_malloc/libhardened_malloc.so [0]
```

BUT if I check is it loaded using your method it outputs nothing
```
$ flatpak ps
Instance   PID   Application                   Runtime
1302534916 10291 org.gnome.Calculator          org.gnome.Platform
3975232359 9306  com.notesnook.Notesnook       org.freedesktop.Platform
2518384101 9274  com.notesnook.Notesnook       org.freedesktop.Platform
368275228  7476  io.gitlab.librewolf-community org.freedesktop.Platform
$ grep hardened /proc/10291/maps
<nothing>
```

**Comment by ByteCorum** [comment]
This looks like a sign that it works, btw it works without `LD_PRELOAD=/opt/hardened_malloc/libhardened_malloc.so`
```
$ flatpak run com.spotify.Client
free(): invalid size
[0402/153310.789142:WARNING:third_party/crashpad/crashpad/handler/linux/exception_handler_server.cc:204] no ptrace
```

**Comment by RoyalOughtness** [comment]
@ByteCorum Interesting, thanks. What do you mean by "opening a huge hole in the sandbox.", though? We allow ro access to /usr which is already mounted ro

**Comment by ByteCorum** [comment]
> [@ByteCorum](https://github.com/ByteCorum) Interesting, thanks. What do you mean by "opening a huge hole in the sandbox.", though? We allow ro access to /usr which is already mounted ro

I mean, giving flatpak permission to host-os even read-only, gives all flatpaks access to all content in the /usr dir and sub-dirs, which increases the possibility of fingerprinting your PC. Some malware may use this data to find vulnerabilities inside your PC to escape a sandbox.
