### ISSUE TITLE
fix duplicate grub entries

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#69]
I dont know if this problem is fixed upstream or if just I fixed it in my normal Kinoite install.

There is a config that you need to apply to remove the duplicate grub entries.

**Comment by RoyalOughtness** [comment]
There should be a new grub entry for every upgrade to enable rollbacks. This is intended and desirable.

**Comment by boredsquirrel** [comment]
Not enough information, sorry. Please reopen this until verified that it does not happen.

The entries are duplicate, so default configuration
- current
- backup
- x pinned images

but every entry is shown twice
- [2yo issue](https://discussion.fedoraproject.org/t/duplicated-grub-entries-on-silverblue-kinoite/33882)
- [1yo issue](https://discussion.fedoraproject.org/t/silverblue-bios-and-grub-show-two-fedora-entries-which-one-should-i-use/78547/5)

On my own Kinoite install I did some tweak that fixed it.

UEFI: `sudo grub2-switch-to-blscfg`

There was a mention of problems with running this command, even though I had none.

**Comment by RoyalOughtness** [comment]
This will not be reopened as even if it is an issue, it's upstream.
