### ISSUE TITLE
[DOCS] Clarify what hasn't been de-Googled and why

### ISSUE THREAD

**Issue by nihil-admirari** [secureblue/secureblue#690]
Hardened Chromium is based on Vanadium patches, and Vanadium [claims](https://grapheneos.org/features#vanadium) that

> Nearly all remote services disabled by default or removed. … There are only 2 default services: component updates such as certificate authority and certificate revocation updates and DNS-over-HTTPS connectivity checks when enabled

If that is the case, then it's better to state explicitly in the README that Hardened Chromium has already been de-Googled.

If, however, it still phones home to Google, then what connections does it still make, and why they have been left intact considering that Vanadium apparently provides the necessary patches to disable them.

**Comment by RKNF404** [comment]
> Vanadium claims that
> state explicitly in the README that Hardened Chromium has already been de-Googled

[hardened-chromium](https://github.com/secureblue/hardened-chromium) does not attempt to "de-Google" chromium, nor claim to. I do not believe Vanadium attempts/claims to either. Many outgoing connections are disabled to improve privacy if it does not negatively affect security, the goal is not to remove Google services as much as possible especially without reason.

> If, however, it still phones home to Google, then what connections does it still make, and why they have been left intact considering that Vanadium apparently provides the necessary patches to disable them.

All desktop relevant patches from Vanadium are used, so it should be parallel to Vanadium with few exceptions. Elaborate on what you mean by "phone home"? Do you mean send data to Google or simply make connections to Google services?

**Comment by RoyalOughtness** [comment]
Like @RKNF404 said, anything in hardened-chromium that happens to "degoogle" is incidental to its intended effect. 

> Clarify what hasn't been de-Googled and why 
> If that is the case, then it's better to state explicitly in the README that Hardened Chromium has already been de-Googled.

No, because it hasn't and it makes no sense to add details on something explicitly out of scope.
