### ISSUE TITLE
[BUG] starting chromium-browser (JSONDecodeError)

### ISSUE THREAD

**Issue by drscream** [secureblue/secureblue#693]
**Describe the bug**

I've installed the latest Fedora Silverblue version 41 and applied the secureblue script. I used the `bluejail-config` to create a `chromium-browser` instance. But when I try to start it I receive the following error:

```
Failed to run instance: chromium-browser
Exception: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**To Reproduce**

1. Basic installation Fedora Silverblue version 41
2. `bash install_secureblue.sh` (follow the installation)
3. Open `bluejail-config`
4. Create instance
5. Keep all defaults and change Default arguments to `/usr/bin/chromium-browser`
6. Try to start chromium-browser vom GNOME UI menu

**Expected behavior**

`chromium-browser` will start.

**Actual behavior**

Popup notification with:

```
Failed to run instance: chromium-browser
Exception: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Your current image**

```
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/secureblue/silverblue-main-hardened:latest
                   Digest: sha256:608e496aeb21ddf327adf0399c3eaee6733fa0eedfcc0fb29af01bc6ef89be9f
                  Version: 41.20241217.0 (2024-12-17T06:48:42Z)

  ostree-unverified-registry:ghcr.io/secureblue/silverblue-main-hardened:latest
                   Digest: sha256:608e496aeb21ddf327adf0399c3eaee6733fa0eedfcc0fb29af01bc6ef89be9f
                  Version: 41.20241217.0 (2024-12-17T06:48:42Z)
```

**For all images**

Not tested on other images

**Comment by RoyalOughtness** [comment]
I wouldn't recommend using bubblewrap/bubblejail for chromium sandboxing. It's unclear if this has a negative impact on chromium's internal sandbox.

But, we are working on confinement via selinux, gradually 😄
