### ISSUE TITLE
[BUG] Incorrect SELinux labeling on fresh installs

### ISSUE THREAD

**Issue by TheHooly** [secureblue/secureblue#696]
**Describe the bug**
Chromium fails to start on fresh installs unless `ujust toggle-unconfined-domain-userns-creation` is used.

Flatpak has failures for the OpenH264 and the Nvidia runtime due to failed user namespace creation.

**To Reproduce**
1. Fresh install of Secureblue
2. Observe Flatpak install failures in Yafti
3. Observe Chromium failure

**Expected behavior**
Chromium and Flatpak should be able to use user namespaces OOTB, without requiring the unconfined domain userns toggle.

**Actual behavior**
See above.

**Your current image**
 - silverblue-nvidia-hardened:latest

**For all images**
- Most likely affects all images

```
hooly@silverblue-laptop:~$ ls -Z /usr/bin/chromium-browser 
system_u:object_r:bin_t:s0 /usr/bin/chromium-browser
hooly@silverblue-laptop:~$ ls -Z /usr/bin/flatpak
system_u:object_r:bin_t:s0 /usr/bin/flatpak

hooly@silverblue-laptop:~$ chromium-browser 
/usr/bin/nvidia-smi
Checking version
  Installed version: 1734319128
  Package version: 1734319128
No need to update, versions match
[4451:4451:1219/121704.642989:FATAL:credentials.cc(131)] Check failed: . : Keine Berechtigung (13)
[1219/121704.643213:WARNING:exception_handler_server.cc(204)] no ptrace
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)

```

Manually running `run0 restorecon` on the affected files obviously has no effect (read-only).![Image](https://github.com/user-attachments/assets/d0982900-abd2-4a9e-80ae-511b9aee2bf6)

**Comment by RoyalOughtness** [comment]
Already documented in the preinstall readme, upgrading and rebooting before rebasing to secureblue is mandatory

**Comment by TheHooly** [comment]
> Already documented in the preinstall readme, upgrading and rebooting before rebasing to secureblue is mandatory

This install was rebased from a Silverblue 40 image, not 41.

**Comment by RoyalOughtness** [comment]
@TheHooly that should also be fine as long as it's up to date with the latest rpm-ostree. But this gives me an idea. We should add a check to the script that makes it refuse to run on old rpm-ostres versions
