### ISSUE TITLE
Enable MAC Address randomization with a good opt-out

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#72]
Pro: Mac addresses normally are device-unique and can completely de-anonymize you 

Con: randomize on every connect completely bloats the DHCP storage. I had problems using a repeater already, or people are randomly logged out, or speed problems, or crashes, ...

So this randomization should be opt-out but easily done, best in a setup dialog explaining how to exclude certain networks, and best already listing the available networks.

afaik poorly this is not integrated in KDE or GNOME yet, in an understandable way. GrapheneOS has this though

**Comment by RoyalOughtness** [comment]
Great suggestion, thanks. A middle-ground that could be viable is a per-network mac address, which is provided by graphene in addition to the per-connection mac address.

**Comment by wandapeter** [comment]
NetworkManager supports this since 1.4.0 (current v is 1.44.2-1.fc39)

```conf
/etc/NetworkManager/conf.d/wifi_rand_mac.conf

[device-mac-randomization]
# "yes" is already the default for scanning
wifi.scan-rand-mac-address=yes
 
[connection-mac-randomization]
# Randomize MAC for every ethernet connection
ethernet.cloned-mac-address=random
# Generate a random MAC for each WiFi and associate the two permanently.
wifi.cloned-mac-address=stable
```
https://wiki.archlinux.org/title/NetworkManager#Configuring_MAC_address_randomization

**Comment by RoyalOughtness** [comment]
> NetworkManager supports this since 1.4.0 (current v is 1.44.2-1.fc39)

This is a very straightforward add then, this can just be dropped into `usr/etc/NetworkManager/conf.d/wifi_rand_mac.conf` in this repo.

**Comment by boredsquirrel** [comment]
good news! this comes upstream in Fedora 40

https://pagure.io/fedora-workstation/issue/350#comment-884894
