### ISSUE TITLE
[BUG] install-brew and remove-brew fail due to lack of sudo

### ISSUE THREAD

**Issue by Rubiginosa** [secureblue/secureblue#721]
Running as regular user:
```
==> Checking for `sudo` access (which may request your password)...
Insufficient permissions to install Homebrew to "/home/linuxbrew/.linuxbrew" (the default prefix).
```

The install script at https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh just checks for the sudo binary and tries to call it directly. It purposefully exits if run as root.

We should either maintain our own install/uninstall methods or remove `ujust install-brew` and `ujust remove-brew`, since they are nonfunctional. I'm in favour of the former but it might be out of scope.

**Comment by RoyalOughtness** [comment]
I'm inclined to remove them, they're both footguns anyways. feel free to pr the removal
