### ISSUE TITLE
[BUG] install_secureblue.sh states rpm-ostree is too old on latest stable fcos

### ISSUE THREAD

**Issue by topaz8** [secureblue/secureblue#725]
**Describe the bug**
install_secureblue.sh states rpm-ostree is too old on latest stable fcos
![Image](https://github.com/user-attachments/assets/cecf7979-0378-48c4-b1b6-d8a7411287c0)

**To Reproduce**
run install_secureblue.sh on fcos stable

**Your current image**
![Image](https://github.com/user-attachments/assets/e571d7f6-687b-4e40-8a40-7ed7875faae5)

**Comment by RoyalOughtness** [comment]
stable is too old, yes 😄
