### ISSUE TITLE
Review other hardening resources for missing tweaks

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#73]
- [ ] [NSA Linux Hardening guides (2y old now)](https://github.com/shaurya-007/NSA-Linux-Hardening-docs)
- [ ] [RHEL 9 official hardening Docs](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/security_hardening/index) ([PDF](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/pdf/security_hardening/red_hat_enterprise_linux-9-security_hardening-en-us.pdf))
- [ ] [Oracle Linux 9 Security tips (don't seem very in depth)](https://docs.oracle.com/en/operating-systems/oracle-linux/9/)
- [ ] [Oracle 8 Hardening guide PDF (somehow nothing found for Oracle 9](https://docs.oracle.com/en/operating-systems/oracle-linux/8/security/OL8-HARDENING.pdf)
- [ ] [Oracle: administering SELinux](https://docs.oracle.com/en/operating-systems/oracle-linux/selinux/selinux-Preface.html#preface)
- [ ] [Oracle: working with Secureboot](https://docs.oracle.com/en/operating-systems/oracle-linux/secure-boot/#Oracle-Linux)
- [ ] [Fedora hardening guides (on archive.org, probably because outdated)](https://web.archive.org/web/20211028035858/https://docs.fedoraproject.org/en-US/Fedora/19/html/Security_Guide/chap-Security_Guide-Basic_Hardening.html)

just check what's already fully integrated or irrelevant

**Comment by RoyalOughtness** [comment]
> * [ ]  [NSA Linux Hardening guides (2y old now)](https://github.com/shaurya-007/NSA-Linux-Hardening-docs)
> * [ ]  [RHEL 9 official hardening Docs](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/security_hardening/index) ([PDF](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/pdf/security_hardening/red_hat_enterprise_linux-9-security_hardening-en-us.pdf))
> * [ ]  [Oracle Linux 9 Security tips (don't seem very in depth)](https://docs.oracle.com/en/operating-systems/oracle-linux/9/)
> * [ ]  [Oracle 8 Hardening guide PDF (somehow nothing found for Oracle 9](https://docs.oracle.com/en/operating-systems/oracle-linux/8/security/OL8-HARDENING.pdf)
> * [ ]  [Oracle: administering SELinux](https://docs.oracle.com/en/operating-systems/oracle-linux/selinux/selinux-Preface.html#preface)
> * [ ]  [Oracle: working with Secureboot](https://docs.oracle.com/en/operating-systems/oracle-linux/secure-boot/#Oracle-Linux)
> * [ ]  [Fedora hardening guides (on archive.org, probably because outdated)](https://web.archive.org/web/20211028035858/https://docs.fedoraproject.org/en-US/Fedora/19/html/Security_Guide/chap-Security_Guide-Basic_Hardening.html)
> 
> just check what's already fully integrated or irrelevant

Please only open issues for specific hardening suggestions. Linking documentation is not helpful. If there's something specific in them that secureblue is missing, cut specific issues for each one. Otherwise do not do so.

**Comment by boredsquirrel** [comment]
this could belong into a wiki then, as I think having a list of good documents can be really helpful for research

https://www.chromium.org/chromium-os/chromiumos-design-docs/system-hardening/

another one

**Comment by RoyalOughtness** [comment]
> this could belong into a wiki then, as I think having a list of good documents can be really helpful for research
> 
> https://www.chromium.org/chromium-os/chromiumos-design-docs/system-hardening/
> 
> another one

maintaining a wiki of security-related documents is completely out of scope for this project.
