### ISSUE TITLE
Preinstalling Repositories?

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#79]
- [ ] Brave stable + key ([my script or something similar](https://github.com/trytomakeyouprivate/braveinstall-fedora-atomic))
- [ ] [MullvadVPN repo](https://mullvad.net/de/help/install-mullvad-app-linux)
- [ ] [ProtonVPN repo](https://protonvpn.com/support/official-linux-vpn-fedora/)
- [ ] [iVPN repo](https://www.ivpn.net/apps-linux/#fedora)

These are VPNs recommended on [PrivacyGuides](https://www.privacyguides.org/en/vpn/#recommended-providers)

Should we pre-install those repositories to make installation easier? It fits the security-focus, and would probably not end up upstream, but also not directly improves security or something

Also this avoids that people install .rpm packages without verification or updates, which is pretty bad.

Windscribe is recommended by Techlore but doesnt have a repo (yet?)

**Comment by RoyalOughtness** [comment]
1. We already have a working browser solution
2. VPNs are not security related.
3. Opinionated application decisions are up to the user and won't be built in to the image. Users can add new repos themselves with rpm-ostree.

**Comment by RoyalOughtness** [comment]
@trytomakeyouprivate Also, please stop opening issues that are solely "privacy" related. This is a formal warning. It has been communicated to you multiple times now and it's in the README that "privacy" is not in scope. If you continue to do so you will receive a temporary ban per the code of conduct.

**Comment by boredsquirrel** [comment]
I mentioned that this is not a privacy only issue, as all these sites hide away they have repos, so users tend to install RPMs without updates. I understand this scope though, but disagree if the privacy benefits are easy to implement and dont harm security.

To the working browser solution, #20 mentioned you where thinking about installing Brave, and I dont know why you closed the issue.

**Comment by RoyalOughtness** [comment]
> I mentioned that this is not a privacy only issue, as all these sites hide away they have repos, so users tend to install RPMs without updates.

Preventing users from installing applications they way they choose is not in scope.

> but disagree if the privacy benefits are easy to implement and dont harm security.

Your disagreement with the scope has no bearing on it. Do not bring up this topic again.

> To the working browser solution, #20 mentioned you where thinking about installing Brave, and I dont know why you closed the issue.

Brave was only being considered because it's updated more frequently. We now pull in chromium from koji candidates from fedora, so there's no need for brave.

**Comment by boredsquirrel** [comment]
> Preventing users from installing applications they way they choose is not in scope.

(or enabling them to do otherwise easily)

> Brave was only being considered because it's updated more frequently. We now pull in chromium from koji candidates from fedora, so there's no need for brave.

okay thanks for the clarification
