### ISSUE TITLE
Enable Contributors

### ISSUE THREAD

**Issue by wandapeter** [secureblue/secureblue#8]
Hey, it would make me very happy if you would enable contributors! :-)

**Comment by RoyalOughtness** [comment]
There isn't actually a setting to enable that view on the front page. I thought it happened automatically when people contribute, but I've sent you a repo invite, that may fix it.

**Comment by RoyalOughtness** [comment]
This still isn't working, reopening

**Comment by RoyalOughtness** [comment]
@34N0 I figured it out. Github doesn't show that section on forks. As another example of this, take a look at:

https://github.com/anthraxx/linux-hardened

vs 

https://github.com/GrapheneOS/linux-hardened

Feel free to add a CONTRIBUTORS file though :)

**Comment by RoyalOughtness** [comment]
@34N0 https://github.com/secureblue/secureblue/blob/live/CONTRIBUTORS.md :smile:
