### ISSUE TITLE
Change the hostname to something generic

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#81]
By default the Anaconda installer sets the hostname in a very unprivate manner, often `fedora` or similar.

Use case: Generic device name in the local network.

afaik this is only set in `/etc/hostname`. 

```
sudo echo "PC" > /etc/hostname
```

unsure if this can be preset in the files, or if it has to be applied afterwards, as Anaconda overwrites it. This needs to be tried out

**Comment by RoyalOughtness** [comment]
This is already available to users via hostnamectl.

**Comment by boredsquirrel** [comment]
yes but the defaults are bad. On GrapheneOS the device has such a generic name, and the fix is rather easy. Proactive security and all

**Comment by RoyalOughtness** [comment]
> yes but the defaults are bad. 

They are not bad from a security perspective. They are security-neutral and have only "privacy" implications. "Privacy" is out of scope and this has been communicated many many times now and you have been issued two formal warnings already. This is your third and final formal warning.
