### ISSUE TITLE
List of main Flatpak apps to recommend

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#82]
I would use this issue to list some apps that we assume are secure and recommended.

Criteria:
- actively developed and used
- Wayland-native, no XWayland
- good use of portals, best no static permissions at all
- best written in memory safe Languages
- preferrably verified origin

---

- [Decoder](https://gitlab.gnome.org/World/decoder/), a QR Code scanner
- [Loupe/ Image Viewer](https://gitlab.gnome.org/GNOME/loupe) a sandboxed Image Viewer
- [Fractal](https://gitlab.gnome.org/GNOME/fractal), a Matrix Client
- Alacritty Terminal?
- [KRDC](https://flathub.org/apps/org.kde.krdc) or [Connections](https://flathub.org/apps/org.gnome.Connections) for connecting to remote Desktops
- [KRFB](https://apps.kde.org/de/krfb/) or [GNOME remote desktop](https://gitlab.gnome.org/GNOME/gnome-remote-desktop) for VNC server
- [RNote](https://flathub.org/apps/com.github.flxzt.rnote) for handwritten notes (no portals)
- [Foliate](https://flathub.org/apps/com.github.johnfactotum.Foliate), a modern E-Book reader
- [KMyMoney](https://flathub.org/apps/org.kde.kmymoney) for finance
- ...

Missing:
- PDF Viewer (GrapheneOS uses a Fork of a really simple webview based one, we could do the same, but I like Okular)
- Text Editor
- Archive Manager ([Peazip](https://peazip.github.io/peazip-sources.html) is written in Pascal but X11 and no portals)
- Terminal Emulator
- Remote Desktop Server (Rustdesk is not on Flathub for some reason and is broken on Wayland. TigerVNC, NoVNC+wayVNC, nothing ready yet)
- Torrent Client (BiglyBT, Deluge & Pika Torrent have minimal permissions, but all use X11 or no Portals), [Gabut Download Manager](https://flathub.org/apps/com.github.gabutakut.gabutdm) has minimal permissions

**Comment by RoyalOughtness** [comment]
As previously mentioned, app recommendations are not in scope.
