### ISSUE TITLE
upowerd is broken without namespace support (dirty fix)

### ISSUE THREAD

**Issue by Sadoon-AlBader** [secureblue/secureblue#85]
upowerd is broken which means (at least on KDE) no battery icon or power handling.

Best workaround I can think of is disabling namespaces for upowerd:

`/etc/systemd/system/upower.service.d/nons.conf`

```
[Service]
PrivateUsers=no
RestrictNamespaces=no
```

Works just fine for me, but am unsure how this can be added to the system image.
Using this on my work laptop so this is absolutely necessary :P

**Comment by RoyalOughtness** [comment]
Thank you for reporting this, I forgot that I had this set locally. It will be fixed once this PR merges: https://github.com/secureblue/secureblue/pull/89

As you can see in this PR, if you want to bake into the image any config changes, all you have to do is put it into `config/files/usr` in this repo.
