### ISSUE TITLE
fix bubblewrap-suid COPR description

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#86]
The description still refers to @34N0 's COPR repo. Also it says "this allows flatpaks on immutable OSTree distributions", but it applies to all distros

> Get the COPR .repo file

> curl -s https://copr.fedorainfracloud.org/coprs/34n0s/bubblewrap-suid/repo/fedora-39/34n0s-bubblewrap-suid-fedora-39.repo | sudo tee /etc/yum.repos.d/34n0s-bubblewrap-suid-fedora-39.repo

> Override bubblewrap (without suid) package

> sudo rpm-ostree override replace --experimental --freeze --from repo='copr:copr.fedorainfracloud.org:34n0s:bubblewrap-suid' bubblewrap-suid

also is this the method that secureblue is using, or does secureblue do a manual

```
rpm-ostree override remove bubblewrap --install bubblewrap-suid
```

**Comment by wandapeter** [comment]
Secureblue is based on  ublueOS and uses the rpm-ostee module for software installation in build. Please refer to the Ublue documentation to verify what command is used.

Both COPR repositories are based on my github repository. But yeah those installation are incorrect.

**Comment by RoyalOughtness** [comment]
Updated the description
