### ISSUE TITLE
Hardened Chromium config

### ISSUE THREAD

**Issue by wandapeter** [secureblue/secureblue#91]
There are ways to harden chromium without touching any codebase.

Currently there is a [STIG draft for the Chromium Browser](https://static.open-scap.org/ssg-guides/ssg-chromium-guide-index.html) which is already packaged into RHEL's SCAP Security Guide. Of course this guide is aimed at "low-tech" users in a corporate/government environment which secureBlue is not. 

But we could drop in a `.conf` file into `/et/chromium/policies/managed` which loosely follows the STIG. Without disabling plugins or custom search engines...

Also disabling JiT (responsible for roughly half of JS vulns) can be configured by launching with the `--js-flags=--jitless`  flag. Flags can be persistet in a `chromium-flags.conf` file under `$HOME/.config/`.

In the end no code would have to be written and no user interaction would be changed to achieve at least some baseline hardening on top of the shortened patch interval.

For exmample, a hardened Chromium config is part @divestedcg  Brace project:
https://github.com/divestedcg/Brace/blob/master/brace/etc/chromium/policies/managed/brace.json

**Comment by RoyalOughtness** [comment]
Great suggestion, this should be implemented.

**Comment by boredsquirrel** [comment]
Custom launch parameters would mean a custom .desktop entry in `/usr/share/applications/` and I think some minor custom branding (Like Vanadium does) could be nice here, to distinguish the browser.

Do you know if these policies apply to Brave to? Probably yes. I can imagine users will like to use Brave instead, so assuring that the configs are mirrored in the matching directories would be good, without any maintenance work.

Thanks for the mention of `~/.config/chromium-flags.conf`, these are pretty important. Afaik you can place files in `/etc/skel/.config/` which will at least put them there when the first user account is created. This might not be helpful though, so a systemd service updating these config overrides needs to be in place to guarantee that these config overrides can be managed and updated.

**Comment by RoyalOughtness** [comment]
> Custom launch parameters would mean a custom .desktop entry in `/usr/share/applications/` 

That is not correct. They can persist in config, no desktop entry is needed.

> and I think some minor custom branding (Like Vanadium does) could be nice here, to distinguish the browser.

That would require recompiling the browser in a copr, which we won't be doing.
 
> Do you know if these policies apply to Brave to? Probably yes. I can imagine users will like to use Brave instead, so assuring that the configs are mirrored in the matching directories would be good, without any maintenance work.

Management of anything brave-related is not in scope. We already have a working browser solution. If users want to use another browser, it's up to them to manage it.

**Comment by RoyalOughtness** [comment]
> There are ways to harden chromium without touching any codebase.
> 
> Currently there is a [STIG draft for the Chromium Browser](https://static.open-scap.org/ssg-guides/ssg-chromium-guide-index.html) which is already packaged into RHEL's SCAP Security Guide. Of course this guide is aimed at "low-tech" users in a corporate/government environment which secureBlue is not.
> 
> But we could drop in a `.conf` file into `/et/chromium/policies/managed` which loosely follows the STIG. Without disabling plugins or custom search engines...
> 
> Also disabling JiT (responsible for roughly half of JS vulns) can be configured by launching with the `--js-flags=--jitless` flag. Flags can be persistet in a `chromium-flags.conf` file under `$HOME/.config/`.
> 
> In the end no code would have to be written and no user interaction would be changed to achieve at least some baseline hardening on top of the shortened patch interval.
> 
> For exmample, a hardened Chromium config is part @divestedcg Brace project: https://github.com/divestedcg/Brace/blob/master/brace/etc/chromium/policies/managed/brace.json

If I'm reading this right, it looks like JIT can also be disabled in policies. That would be preferable to doing anything in the homedir.

**Comment by wandapeter** [comment]
from https://wiki.archlinux.org/title/chromium
> You can put your flags in a chromium-flags.conf file under $HOME/.config/ (or under $XDG_CONFIG_HOME if you have configured that environment variable) or /etc/ for global.

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/a3ddde977bb882385192f52b9fdb50ef82226b1a
