### ISSUE TITLE
Audio issues and disconnects (KDE)

### ISSUE THREAD

**Issue by Sadoon-AlBader** [secureblue/secureblue#92]
Having constant audio disconnects when changing volume and on random occasions, can verify this issue was present on fresh secureblue install but testing now with stock Fedora Kinoite.
I'm trying to find where pipewire stores its logs but no dice :(

```
State: idle
warning: Failed to query journal: couldn't find current boot in journal
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 10min ago
Deployments:
  ostree-image-signed:docker://ghcr.io/secureblue/kinoite-main-hardened:latest (index: 0)
                   Digest: sha256:4fac4934fdf37bb6c493dac28c603bdb2ada89906f2b284a704843470113e13f
                  Version: 39.20231130.0 (2023-11-30T22:39:48Z)
               BaseCommit: dd5626e10b2a5b094cdd3d8edfcaab90ea895accb0a2f0a542a8ec1cd2ccb71c
                   Commit: 8315045542385e9676a6613b362dcae9d0525de1e278b70abb9a80e16a6f28ad
                           ├─ brave-browser (2023-11-29T17:34:14Z)
                           ├─ copr:copr.fedorainfracloud.org:secureblue:bubblejail (2023-11-27T18:33:01Z)
                           ├─ copr:copr.fedorainfracloud.org:secureblue:bubblewrap-suid (2023-11-27T18:45:19Z)
                           ├─ copr:copr.fedorainfracloud.org:secureblue:hardened_malloc (2023-11-27T18:34:44Z)
                           ├─ copr:copr.fedorainfracloud.org:ublue-os:akmods (2023-11-26T23:21:11Z)
                           ├─ fedora (2023-11-01T00:12:39Z)
                           ├─ fedora-cisco-openh264 (2023-03-14T10:57:01Z)
                           ├─ rpmfusion-free (2023-11-04T16:49:08Z)
                           ├─ rpmfusion-free-updates (2023-11-24T19:24:24Z)
                           ├─ rpmfusion-nonfree (2023-11-04T17:26:32Z)
                           ├─ rpmfusion-nonfree-updates (2023-11-24T19:44:29Z)
                           ├─ updates (2023-12-01T01:15:12Z)
                           └─ updates-archive (2023-11-26T03:04:34Z)
                   Staged: yes
                StateRoot: fedora
            SecAdvisories: FEDORA-2023-fa01e4c6ba  Moderate   xen-libs-4.17.2-5.fc39.x86_64
                           FEDORA-2023-fa01e4c6ba  Moderate   xen-licenses-4.17.2-5.fc39.x86_64
                           FEDORA-2023-ad944c2d34  Important  libcap-2.48-8.fc39.x86_64
                 Upgraded: ethtool 2:6.5-1.fc39 -> 2:6.6-1.fc39
                           fedora-appstream-metadata 20231107-1.fc39 -> 20231124-1.fc39
                           fedora-release-common 39-30 -> 39-34
                           fedora-release-identity-kinoite 39-30 -> 39-34
                           fedora-release-kinoite 39-30 -> 39-34
                           fedora-release-ostree-desktop 39-30 -> 39-34
                           kernel 6.5.12-300.fc39 -> 6.6.2-201.fc39
                           kernel-core 6.5.12-300.fc39 -> 6.6.2-201.fc39
                           kernel-modules 6.5.12-300.fc39 -> 6.6.2-201.fc39
                           kernel-modules-core 6.5.12-300.fc39 -> 6.6.2-201.fc39
                           kernel-modules-extra 6.5.12-300.fc39 -> 6.6.2-201.fc39
                           libcap 2.48-7.fc39 -> 2.48-8.fc39
                           liburing 2.4-3.fc39 -> 2.5-1.fc39
                           libwnck3 43.0-5.fc39 -> 43.0-6.fc39
                           qt5-qtbase 5.15.11-6.fc39 -> 5.15.11-7.fc39
                           qt5-qtbase-common 5.15.11-6.fc39 -> 5.15.11-7.fc39
                           qt5-qtbase-gui 5.15.11-6.fc39 -> 5.15.11-7.fc39
                           qt5-qtbase-mysql 5.15.11-6.fc39 -> 5.15.11-7.fc39
                           xen-libs 4.17.2-4.fc39 -> 4.17.2-5.fc39
                           xen-licenses 4.17.2-4.fc39 -> 4.17.2-5.fc39
          LayeredPackages: axel brave-browser kcm_systemd mc openssh-server powertop
                           virt-manager zsh

● ostree-image-signed:docker://ghcr.io/secureblue/kinoite-main-hardened:latest (index: 1)
                   Digest: sha256:64988e75836bf816afdb1b5c82b6cebea8bda1f20ff408441ebc3c73c5c67e99
                  Version: 39.20231129.0 (2023-11-30T03:58:35Z)
               BaseCommit: eb6fa7f593f26400eb42bf00db28cf1ec7130bb2de9262b3a415ecd5882db792
                   Commit: 51bc77242f005fe5413f4d4ab9a4c64953027871097c6d20d0e41c41b15cfce1
                           ├─ brave-browser (2023-11-29T17:34:14Z)
                           ├─ copr:copr.fedorainfracloud.org:secureblue:bubblewrap-suid (2023-11-27T18:45:19Z)
                           ├─ copr:copr.fedorainfracloud.org:secureblue:hardened_malloc (2023-11-27T18:34:44Z)
                           ├─ copr:copr.fedorainfracloud.org:ublue-os:akmods (2023-11-26T23:21:11Z)
                           ├─ fedora (2023-11-01T00:12:39Z)
                           ├─ fedora-cisco-openh264 (2023-03-14T10:57:01Z)
                           ├─ rpmfusion-free (2023-11-04T16:49:08Z)
                           ├─ rpmfusion-free-updates (2023-11-24T19:24:24Z)
                           ├─ rpmfusion-nonfree (2023-11-04T17:26:32Z)
                           ├─ rpmfusion-nonfree-updates (2023-11-24T19:44:29Z)
                           ├─ updates (2023-11-29T01:22:53Z)
                           └─ updates-archive (2023-11-26T03:04:34Z)
                StateRoot: fedora
          LayeredPackages: axel brave-browser kcm_systemd mc openssh-server powertop
                           virt-manager zsh

  ostree-image-signed:docker://ghcr.io/secureblue/kinoite-main-hardened:latest (index: 2)
                   Digest: sha256:5997def03e423a7881a260a2af7f69100c3745b1c8b16db703a31cc595a839e2
                  Version: 39.20231128.0 (2023-11-29T16:42:11Z)
               BaseCommit: d98e544f7ceb87af184a342e9667ca5c19fd094e61ab42e97c4d23cfbdf9e960
                   Commit: 333c3bdbd0b939ec365c81bc752191d4422e2b5ba7b9dbffd65310ec1a5c2acb
                           ├─ brave-browser (2023-11-29T17:34:14Z)
                           ├─ copr:copr.fedorainfracloud.org:secureblue:bubblewrap-suid (2023-11-27T18:45:19Z)
                           ├─ copr:copr.fedorainfracloud.org:secureblue:hardened_malloc (2023-11-27T18:34:44Z)
                           ├─ copr:copr.fedorainfracloud.org:ublue-os:akmods (2023-11-26T23:21:11Z)
                           ├─ fedora (2023-11-01T00:12:39Z)
                           ├─ fedora-cisco-openh264 (2023-03-14T10:57:01Z)
                           ├─ rpmfusion-free (2023-11-04T16:49:08Z)
                           ├─ rpmfusion-free-updates (2023-11-24T19:24:24Z)
                           ├─ rpmfusion-nonfree (2023-11-04T17:26:32Z)
                           ├─ rpmfusion-nonfree-updates (2023-11-24T19:44:29Z)
                           ├─ updates (2023-11-29T01:22:53Z)
                           └─ updates-archive (2023-11-26T03:04:34Z)
                StateRoot: fedora
         InactiveRequests: openssh-server
          LayeredPackages: axel brave-browser kcm_systemd mc powertop virt-manager zsh
```

**Comment by RoyalOughtness** [comment]
Thanks for reporting this. Please update this thread once you've confirmed whether or not the issue persists on stock kinoite

**Comment by RoyalOughtness** [comment]
@Sadoon-AlBader were you able to reproduce this on stock kinoite?

**Comment by Sadoon-AlBader** [comment]
> @Sadoon-AlBader were you able to reproduce this on stock kinoite?

I installed stock Kinoite on a flash drive to test and somehow grub doesn't want to boot it, definitely will test again later when I'm free.

**Comment by RoyalOughtness** [comment]
> > @Sadoon-AlBader were you able to reproduce this on stock kinoite?
> 
> I installed stock Kinoite on a flash drive to test and somehow grub doesn't want to boot it, definitely will test again later when I'm free.

That's not necessary. Just rebase to stock kinoite, test, then rebase back. Should take at most 10 minutes.

One of the advantages of immutable :smile:

**Comment by Sadoon-AlBader** [comment]
> That's not necessary. Just rebase to stock kinoite, test, then rebase back. Should take at most 10 minutes.
> 
> One of the advantages of immutable 😄

That's awesome, just did and as I suspected, no issues on stock Kinoite.

EDIT: removed the meme, was too big lol

Also, I'm trying to look online for where pipewire logs would be placed or how to view them, can't find much.

**Comment by RoyalOughtness** [comment]
> That's awesome, just did and as I suspected, no issues on stock Kinoite.

More than likely pipewire and hardened_malloc aren't playing nice together then. This will need further investigation.

**Comment by Sadoon-AlBader** [comment]
> > That's awesome, just did and as I suspected, no issues on stock Kinoite.
> 
> More than likely pipewire and hardened_malloc aren't playing nice together then. This will need further investigation.

Yup, verified.

`sudo mv /etc/ld.so.preload /etc/ld.so.preload.bak`

No crashes.

```
$ cat /etc/ld.so.preload
/usr/lib64/libhardened_malloc-light.so
```

Works fine with hardened_malloc light.

**Comment by RoyalOughtness** [comment]
> > > That's awesome, just did and as I suspected, no issues on stock Kinoite.
> > 
> > 
> > More than likely pipewire and hardened_malloc aren't playing nice together then. This will need further investigation.
> 
> Yup, verified.
> 
> `sudo mv /etc/ld.so.preload /etc/ld.so.preload.bak`
> 
> No crashes.
> 
> ```
> $ cat /etc/ld.so.preload
> /usr/lib64/libhardened_malloc-light.so
> ```
> 
> Works fine with hardened_malloc light.

I'm unable to reproduce this on GNOME, so I'm thinking whether we should use libhardened_malloc-light just for KDE, or for both, or keep it as is and report this upstream to kde

**Comment by Sadoon-AlBader** [comment]
> I'm unable to reproduce this on GNOME, so I'm thinking whether we should use libhardened_malloc-light just for KDE, or for both, or keep it as is and report this upstream to kde

I'm going to test a couple of things then:
1- Older Haswell laptop to rule out hardware being what's causing this.
2- Terminal volume control (pavucontrol etc) EDIT: oops meant pulsemixer EDITEDIT: alsamixer

So it still crashes when using alsamixer. Weird.

EDIT: I still cannot rule out which binary is causing this, tried to see if pipewire.service or pipewire-pulse.service get restarted when this crash happens, no dice.
I 100% know it's some user application, but I'm still investigating.

**Comment by Sadoon-AlBader** [comment]
Ok finally found the culprit: wireplumber.
Starting wireplumber with:
`bwrap --dev-bind / / --bind /dev/null /usr/lib64/libhardened_malloc.so wireplumber`
..makes it work.
Now how to force the systemd service to do that, or at least bind it to hardened_malloc-light.so..?

**Comment by Sadoon-AlBader** [comment]
Ok finally solved.
We need to edit the systemd unit to override the LD_PRELOAD with hardened_malloc-light.so

`systemctl --user edit wireplumber.service`

Then add these lines

```
[Service]
Environment=LD_PRELOAD=/usr/lib64/libhardened_malloc-light.so
```

then `systemctl --user daemon-reload && systemctl --user restart wireplumber.service`

And voila! Much better than downgrading the whole system to hardened_malloc-light, even if not the cleanest solution.

**Comment by RoyalOughtness** [comment]
> Ok finally solved. We need to edit the systemd unit to override the LD_PRELOAD with hardened_malloc-light.so
> 
> `systemctl --user edit wireplumber.service`
> 
> Then add these lines
> 
> ```
> [Service]
> Environment=LD_PRELOAD=/usr/lib64/libhardened_malloc-light.so
> ```
> 
> then `systemctl --user daemon-reload && systemctl --user restart wireplumber.service`
> 
> And voila! Much better than downgrading the whole system to hardened_malloc-light, even if not the cleanest solution.

Thanks for finding the solution to this!

**Comment by Sadoon-AlBader** [comment]
#97 does fix this indeed, removed my custom edit and it doesn't crash. Thanks!
