### ISSUE TITLE
Custom Branding (?)

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#96]
I am not sure if this is wanted. Differentiation from Fedora could be wished or not.

- [ ] KDE Menu icon
- [ ] "non verbose" boot screen
- [ ] LUKS password entry screen
- [ ] grub entries?
- [ ] `/etc/os-release` (Fedora, but variant "Secureblue", custom URL)

Thats all I know currently. Please check what is unneeded or fixed. Is this wished for?

**Comment by RoyalOughtness** [comment]
As mentioned before, this is not a distribution. The distribution is Fedora. Even upstream uBlue and stock immutable variants do not change this branding.

**Comment by boredsquirrel** [comment]
Is the `/etc/os-release` really excluded here? It should have some indication that this is silverblue-hardened/kinoite-hardened

**Comment by RoyalOughtness** [comment]
> Is the `/etc/os-release` really excluded here? It should have some indication that this is silverblue-hardened/kinoite-hardened

Yes it's excluded. Even upstream ublue doesn't rebrand this.
